//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class SFSharablePassword;

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerCredentialLinks
{
    SFSharablePassword *_credential;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000b69aa
- (void)updatePossibleActions;	// IMP=0x00100000000b6739
- (long long)transferTypes;	// IMP=0x00100000000b6704
- (id)suitableContentsDescription;	// IMP=0x00100000000b6576
- (void)handleAction;	// IMP=0x00100000000b64e0
- (_Bool)canHandleTransfer;	// IMP=0x00100000000b64cb

@end

