//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class SDAirDropHandleriCloudDrive;

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerUnsupportedType
{
    SDAirDropHandleriCloudDrive *_icloudDriveHandler;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000000eebf
- (void)triggerAppStoreSearch;	// IMP=0x001000000000ecb0
- (void)updatePossibleActions;	// IMP=0x001000000000e9c9
- (id)suitableContentsDescription;	// IMP=0x001000000000e8ae
- (_Bool)canHandleTransfer;	// IMP=0x001000000000e826
- (id)initWithTransfer:(id)arg1;	// IMP=0x001000000000e74e

@end

