//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableDictionary, NSString, SDAirDropTransferManager;

__attribute__((visibility("hidden")))
@interface SDAirDropClassroomTransferManager
{
    NSMutableDictionary *_transferIDToProgress;	// 8 = 0x8
    SDAirDropTransferManager *_transferManager;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000018e0c0
@property(retain, nonatomic) SDAirDropTransferManager *transferManager; // @synthesize transferManager=_transferManager;
- (void)connectionInvalidated:(id)arg1;	// IMP=0x001000000018df4c
- (void)connectionEstablished:(id)arg1;	// IMP=0x001000000018de43
- (_Bool)shouldAcceptNewConnection:(id)arg1;	// IMP=0x001000000018de3b
- (id)remoteObjectInterface;	// IMP=0x001000000018de1b
- (id)exportedInterface;	// IMP=0x001000000018dccb
- (id)machServiceName;	// IMP=0x001000000018dcbe
- (void)alertManager:(id)arg1 cancelingTransferWithRecordID:(id)arg2 withFailureReason:(unsigned long long)arg3;	// IMP=0x001000000018dae1
- (void)alertManager:(id)arg1 acceptingTransferWithRecordID:(id)arg2 withDestinationURL:(id)arg3 shouldExtractMediaFromPhotosBundlesForRecordID:(_Bool)arg4;	// IMP=0x001000000018d912
- (void)updateTransferWithIdentifier:(id)arg1 withState:(long long)arg2 information:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x001000000018cf46
- (void)replaceIconValue:(id)arg1 forKey:(id)arg2;	// IMP=0x001000000018ce26
- (id)makeDestinationDirectoryWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000018cba1
- (void)_enumerateRemoteObjectProxiesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000018cb8f
- (void)invalidate;	// IMP=0x001000000018cb60
- (void)activate;	// IMP=0x001000000018cb31
- (id)init;	// IMP=0x001000000018cad4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

