//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CSAttSiriRequestContext : NSObject
{
    unsigned long long _reqSrc;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000006d3a
@property(nonatomic) unsigned long long reqSrc; // @synthesize reqSrc=_reqSrc;
- (id)description;	// IMP=0x0010000000006e1d
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000006dad
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000006d8a
- (id)initWithRequestSource:(unsigned long long)arg1;	// IMP=0x0010000000006d4d
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000006d42

@end

