//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSAudioCircularBuffer, CSAudioStream, CSPlainAudioFileWriter, NSHashTable, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface CSContinuousAudioFingerprintProvider : NSObject
{
    _Bool _isListenPollingStarting;	// 8 = 0x8
    float _currentMaximumBufferSize;	// 12 = 0xc
    NSHashTable *_observers;	// 16 = 0x10
    CSAudioStream *_audioStream;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
    CSAudioCircularBuffer *_audioLoggingBuffer;	// 40 = 0x28
    CSPlainAudioFileWriter *_audioFileWriter;	// 48 = 0x30
    NSMutableDictionary *_inUseServices;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000000bb9d1
@property(nonatomic) float currentMaximumBufferSize; // @synthesize currentMaximumBufferSize=_currentMaximumBufferSize;
@property(retain, nonatomic) NSMutableDictionary *inUseServices; // @synthesize inUseServices=_inUseServices;
@property(retain, nonatomic) CSPlainAudioFileWriter *audioFileWriter; // @synthesize audioFileWriter=_audioFileWriter;
@property(retain, nonatomic) CSAudioCircularBuffer *audioLoggingBuffer; // @synthesize audioLoggingBuffer=_audioLoggingBuffer;
@property(nonatomic) _Bool isListenPollingStarting; // @synthesize isListenPollingStarting=_isListenPollingStarting;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) CSAudioStream *audioStream; // @synthesize audioStream=_audioStream;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
- (void)CSAudioServerCrashMonitorDidReceiveServerRestart:(id)arg1;	// IMP=0x00100000000bb7d3
- (void)audioStreamProvider:(id)arg1 didHardwareConfigurationChange:(long long)arg2;	// IMP=0x00100000000bb7cd
- (void)audioStreamProvider:(id)arg1 audioChunkForTVAvailable:(id)arg2;	// IMP=0x00100000000bb7c7
- (void)audioStreamProvider:(id)arg1 audioBufferAvailable:(id)arg2;	// IMP=0x00100000000bb7c1
- (void)audioStreamProvider:(id)arg1 didStopStreamUnexpectly:(long long)arg2;	// IMP=0x00100000000bb6ae
- (void)CSSiriEnabledMonitor:(id)arg1 didReceiveEnabled:(_Bool)arg2;	// IMP=0x00100000000bb581
- (void)_stopListening;	// IMP=0x00100000000bb3d5
- (void)_startListenPolling;	// IMP=0x00100000000bb2f2
- (void)_startListenWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000bac93
- (void)_startListenPollingWithInterval:(double)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ba8a9
- (void)_reset;	// IMP=0x00100000000ba8a3
- (void)reset;	// IMP=0x00100000000ba842
- (void)unregisterObserver:(id)arg1;	// IMP=0x00100000000ba6b2
- (void)registerObserver:(id)arg1;	// IMP=0x00100000000ba449
- (void)stopWithUUID:(id)arg1;	// IMP=0x00100000000ba0c7
- (void)startWithUUID:(id)arg1 withMaximumBufferSize:(float)arg2;	// IMP=0x00100000000b9c82
- (void)_setMaximumBufferSizeFromInUseServices;	// IMP=0x00100000000b9aa3
- (id)init;	// IMP=0x00100000000b99b9

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

