//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CSOtherAppRecordingStateMonitor
{
}

+ (id)sharedInstance;	// IMP=0x00400000000775ea
- (void)_startObservingSystemControllerLifecycle;	// IMP=0x00400000000778b6
- (void)_systemControllerDied:(id)arg1;	// IMP=0x00100000000777df
- (void)_startObservingOtherAppRecordingState;	// IMP=0x00100000000777d9
- (_Bool)isOtherAppRecording;	// IMP=0x00100000000777d1
- (void)handleOtherAppRecordingStateChange:(id)arg1;	// IMP=0x00100000000776e0
- (void)_stopMonitoring;	// IMP=0x00100000000776da
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x00100000000776ac
- (id)init;	// IMP=0x001000000007763f

@end

