//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CSTrialAssetDownloadMonitor, NSString;

@interface CSSpeakerRecognitionAssetDownloadMonitor
{
    int _notifyToken;	// 8 = 0x8
    unsigned long long _lastUpdatedAssetType;	// 16 = 0x10
    CSTrialAssetDownloadMonitor *_trialAssetMonitor;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x00200000000091ac
- (void).cxx_destruct;	// IMP=0x00200000000096d4
@property(retain, nonatomic) CSTrialAssetDownloadMonitor *trialAssetMonitor; // @synthesize trialAssetMonitor=_trialAssetMonitor;
- (void)trialAssetDownloadMonitorDelegate:(id)arg1 didInstallNewAsset:(_Bool)arg2 assetType:(unsigned long long)arg3;	// IMP=0x001000000000962b
- (void)_notifyObserver:(id)arg1;	// IMP=0x00100000000095c6
- (void)_didInstalledNewAsset;	// IMP=0x00100000000094e6
- (void)_stopMonitoring;	// IMP=0x0010000000009443
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x0010000000009311
- (const char *)_notificationKey;	// IMP=0x0010000000009304
- (id)init;	// IMP=0x0010000000009201

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;

@end

