//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CSVoiceTriggerAssetDownloadMonitor
{
    int _notifyToken;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x00400000000b7bb1
- (void)_notifyObserver:(id)arg1;	// IMP=0x00200000000b7f53
- (void)_didInstalledNewVoiceTriggerAsset;	// IMP=0x00100000000b7e73
- (void)_stopMonitoring;	// IMP=0x00100000000b7dd0
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x00100000000b7cb1
- (const char *)_notificationKey;	// IMP=0x00100000000b7c48
- (id)init;	// IMP=0x00100000000b7c06

@end

