//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <IDSFoundation/IDSBaseMessage.h>

@class NSArray, NSData, NSMutableArray, NSString;

@interface IDSAuthenticateUsersMessage : IDSBaseMessage
{
    NSData *_pushToken;	// 232 = 0xe8
    NSString *_realm;	// 240 = 0xf0
    NSMutableArray *_requests;	// 248 = 0xf8
    NSArray *_authenticationResponses;	// 256 = 0x100
}

- (void).cxx_destruct;	// IMP=0x0020000000331340
@property(retain, nonatomic) NSArray *authenticationResponses; // @synthesize authenticationResponses=_authenticationResponses;
@property(retain, nonatomic) NSMutableArray *requests; // @synthesize requests=_requests;
@property(copy) NSString *realm; // @synthesize realm=_realm;
@property(copy, nonatomic) NSData *pushToken; // @synthesize pushToken=_pushToken;
- (void)handleResponseDictionary:(id)arg1;	// IMP=0x0010000000330e00
- (void)_addRequestWithID:(id)arg1 cert:(id)arg2 sig:(id)arg3 csr:(id)arg4 tag:(id)arg5;	// IMP=0x0010000000330ae0
- (void)addRequestWithID:(id)arg1 sig:(id)arg2 csr:(id)arg3 tag:(id)arg4;	// IMP=0x0010000000330a00
- (void)addRequestWithID:(id)arg1 cert:(id)arg2;	// IMP=0x0010000000330970
- (_Bool)allowsServerProvidedLenientAnisetteTimeout;	// IMP=0x0010000000330950
- (double)anisetteHeadersTimeout;	// IMP=0x0010000000330930
- (id)additionalMessageHeaders;	// IMP=0x00100000003307b0
- (id)messageBody;	// IMP=0x00100000003305d0
- (id)requiredKeys;	// IMP=0x0010000000330530
- (id)bagKey;	// IMP=0x0010000000330510
- (_Bool)requiresPushTokenKeys;	// IMP=0x00100000003304f0
- (long long)responseCommand;	// IMP=0x00100000003304d0
- (long long)command;	// IMP=0x00100000003304b0
- (_Bool)wantsBinaryPush;	// IMP=0x0010000000330490
- (_Bool)wantsCompressedBody;	// IMP=0x0010000000330470
- (_Bool)wantsHTTPHeaders;	// IMP=0x0010000000330450
- (_Bool)wantsBagKey;	// IMP=0x0010000000330430
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000003302b0
- (id)init;	// IMP=0x0010000000330180

@end

