//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol IDSDaemonMIGInterfaceDelegate, IDSXPCConnectionProtocol;

@interface IDSDaemonMIGInterface : NSObject
{
    id <IDSXPCConnectionProtocol> _server;	// 8 = 0x8
    int _notifyToken;	// 16 = 0x10
    id _delegate;	// 24 = 0x18
    _Bool _shuttingDown;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x00400000001ba7a0
- (void).cxx_destruct;	// IMP=0x00200000001bbec0
@property __weak id <IDSDaemonMIGInterfaceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)denyIncomingGrantRequests;	// IMP=0x00100000001bbde0
- (void)acceptIncomingGrantRequests;	// IMP=0x00100000001bbcf0
- (void)__setupServer;	// IMP=0x00100000001ba860

@end

