//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSPhoneUser, NSDate, NSString;

@interface IDSTemporaryPhoneUser : NSObject
{
    _Bool _hasBeenProvisioned;	// 8 = 0x8
    _Bool _finishedRegistration;	// 9 = 0x9
    _Bool _hasNotifiedSuccess;	// 10 = 0xa
    NSDate *_expirationDate;	// 16 = 0x10
    IDSPhoneUser *_phoneUser;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000001dfe70
- (void).cxx_destruct;	// IMP=0x00200000001e06c0
@property(retain, nonatomic) IDSPhoneUser *phoneUser; // @synthesize phoneUser=_phoneUser;
@property(nonatomic) _Bool hasNotifiedSuccess; // @synthesize hasNotifiedSuccess=_hasNotifiedSuccess;
@property(nonatomic) _Bool finishedRegistration; // @synthesize finishedRegistration=_finishedRegistration;
@property(nonatomic) _Bool hasBeenProvisioned; // @synthesize hasBeenProvisioned=_hasBeenProvisioned;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000001e0290
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000001e00d0
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000001dfe90
- (_Bool)isIdenticalToUser:(id)arg1;	// IMP=0x00100000001dfc90
- (_Bool)isEqualToUser:(id)arg1;	// IMP=0x00100000001dfc30
- (_Bool)isEqualToTemporaryPhoneUser:(id)arg1;	// IMP=0x00100000001dfaa0
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001dfa00
@property(readonly) unsigned long long hash;
- (_Bool)shouldReplace:(id)arg1;	// IMP=0x00100000001df950
@property(readonly, nonatomic) NSString *labelID;
@property(readonly, nonatomic) NSString *networkCode;
@property(readonly, nonatomic) NSString *countryCode;
@property(readonly, nonatomic) NSString *phoneNumber;
- (id)storageIdentifier;	// IMP=0x00100000001df640
- (id)unprefixedIdentifier;	// IMP=0x00100000001df5d0
- (id)realmPrefixedIdentifier;	// IMP=0x00100000001df560
- (long long)realm;	// IMP=0x00100000001df540
- (id)uniqueIdentifier;	// IMP=0x00100000001df3f0
- (id)temporaryPhoneUserWithNotifiedSuccess;	// IMP=0x00100000001df370
- (id)temporaryPhoneUserWithFinishedRegistration;	// IMP=0x00100000001df2f0
- (id)temporaryPhoneUserWithUpdatedExpirationDate:(id)arg1;	// IMP=0x00100000001df220
- (id)initWithPhoneUser:(id)arg1 expirationDate:(id)arg2 finishedRegistration:(_Bool)arg3;	// IMP=0x00100000001df110
- (id)initWithPhoneUser:(id)arg1;	// IMP=0x00100000001df040

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

