//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSData, NSString;
@protocol OS_dispatch_queue;

@interface IDSValidationSession : NSObject
{
    NSData *_helloMessage;	// 8 = 0x8
    NSString *_UDID;	// 16 = 0x10
    NSString *_serialNumber;	// 24 = 0x18
    NSString *_IMEI;	// 32 = 0x20
    NSString *_MEID;	// 40 = 0x28
    NSData *_scoringNonce;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_queue;	// 56 = 0x38
    long long _stateFlags;	// 64 = 0x40
    NSData *_BAACert;	// 72 = 0x48
    NSData *_intermediateRootCert;	// 80 = 0x50
    long long _mechanism;	// 88 = 0x58
}

+ (id)retrieveLocalUDID;	// IMP=0x00200000001e3560
+ (id)_BAACertTTLInMinutesFromServerBag;	// IMP=0x00100000001e31b0
+ (id)_BAAFetchTimeoutFromServerBag;	// IMP=0x00100000001e30a0
+ (_Bool)_isBAAOptionEnabledByServerBag;	// IMP=0x00100000001e2f60
+ (_Bool)_isAbsintheV3EnabledByServerBag;	// IMP=0x00100000001e2e50
+ (_Bool)isScoringSupported;	// IMP=0x00100000001e2e30
+ (_Bool)isSigningSupported;	// IMP=0x00100000001e2e10
+ (void)purgeCachedCertsForSubsystemMechanism:(long long)arg1;	// IMP=0x00100000001e17c0
+ (void)absintheValidationSessionOnQueue:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001e1590
+ (void)baaOnlyValidationSessionOnQueue:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001e1480
+ (void)validationSessionOnQueue:(id)arg1 mechanism:(long long)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001e13a0
- (void).cxx_destruct;	// IMP=0x00200000001e3900
@property(readonly, nonatomic) long long mechanism; // @synthesize mechanism=_mechanism;
@property(copy, nonatomic) NSData *intermediateRootCert; // @synthesize intermediateRootCert=_intermediateRootCert;
@property(copy, nonatomic) NSData *BAACert; // @synthesize BAACert=_BAACert;
@property(nonatomic) long long stateFlags; // @synthesize stateFlags=_stateFlags;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) NSData *scoringNonce; // @synthesize scoringNonce=_scoringNonce;
@property(copy, nonatomic) NSString *MEID; // @synthesize MEID=_MEID;
@property(copy, nonatomic) NSString *IMEI; // @synthesize IMEI=_IMEI;
@property(copy, nonatomic) NSString *serialNumber; // @synthesize serialNumber=_serialNumber;
@property(copy, nonatomic) NSString *UDID; // @synthesize UDID=_UDID;
@property(copy, nonatomic) NSData *helloMessage; // @synthesize helloMessage=_helloMessage;
- (id)_deviceAbsintheMEID;	// IMP=0x00100000001e35c0
- (id)_deviceAbsintheIMEI;	// IMP=0x00100000001e35b0
- (id)_deviceAbsintheSerialNumber;	// IMP=0x00100000001e35a0
- (id)_deviceAbsintheUDID;	// IMP=0x00100000001e3570
- (_Bool)_shouldUseDebugPiscoLogging;	// IMP=0x00100000001e34b0
- (_Bool)_shouldUseBAACertOption;	// IMP=0x00100000001e33d0
- (_Bool)_shouldUseBAAOnly;	// IMP=0x00100000001e33b0
- (_Bool)_shouldUseAbsintheV4;	// IMP=0x00100000001e32e0
- (_Bool)_shouldUseAbsintheV3;	// IMP=0x00100000001e32c0
@property(readonly, nonatomic) _Bool isUsingBAA;
@property(readonly, nonatomic) _Bool isUsingAbsintheV4;
@property(readonly, nonatomic) _Bool isUsingAbsintheV3;
@property(readonly, nonatomic) _Bool isInitializedForScoring;
@property(readonly, nonatomic) _Bool isInitializedForSigning;
- (void)invalidate;	// IMP=0x00100000001e2b20
- (void)deviceScoreWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001e2970
- (id)headersBySigningData:(id)arg1 serverTimestamp:(id)arg2 error:(id *)arg3;	// IMP=0x00100000001e1cb0
- (id)signData:(id)arg1 serverTimestamp:(id)arg2;	// IMP=0x00100000001e1a40
- (id)activateWithValidationData:(id)arg1 serverKey:(id)arg2 scoringNonce:(id)arg3;	// IMP=0x00100000001e17e0
- (void)dealloc;	// IMP=0x00100000001e1350
- (MISSING_TYPE *)description;	// IMP=0x00100000001e1290
- (id)initWithQueue:(id)arg1 mechanism:(long long)arg2;	// IMP=0x00100000001e11a0

@end

