//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface RequestStore : NSObject
{
    NSObject<OS_dispatch_queue> *_fileAccessQueue;	// 8 = 0x8
    NSString *_fileName;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000169cd
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *fileAccessQueue; // @synthesize fileAccessQueue=_fileAccessQueue;
- (id)_retrieveFile;	// IMP=0x00100000000164f1
- (void)_storeFileWithItems:(id)arg1;	// IMP=0x0010000000016043
- (id)_pathWithFileName:(id)arg1;	// IMP=0x0010000000015cc6
- (id)_filePath;	// IMP=0x0010000000015c67
- (void)_deleteFile;	// IMP=0x00100000000158dc
- (void)storeItems:(id)arg1;	// IMP=0x0010000000015716
- (id)items;	// IMP=0x001000000001546d
- (void)clearCache;	// IMP=0x00100000000152e9
- (id)initWithFileName:(id)arg1;	// IMP=0x0010000000015262

@end

