//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GeoServices/GEOServiceRequestDefaultConfig.h>

@interface _GEOETARequestConfig : GEOServiceRequestDefaultConfig
{
}

+ (id)standardConfig;	// IMP=0x004000000005212d
- (CDStruct_026435ec)dataRequestKindForRequest:(id)arg1 traits:(id)arg2;	// IMP=0x004000000005219a
- (id)serviceTypeNumber;	// IMP=0x001000000005218d
- (unsigned long long)urlType;	// IMP=0x0010000000052182

@end

