//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol APNSPackDecoderDelegate;

@interface APNSPackDecoder : NSObject
{
    id <APNSPackDecoderDelegate> _delegate;	// 8 = 0x8
    void *_decoder;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000065c09
@property(nonatomic) __weak id <APNSPackDecoderDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) void *decoder; // @synthesize decoder=_decoder;
- (void)reset;	// IMP=0x0010000000065bc0
- (id)metrics;	// IMP=0x0010000000065b8a
- (id)valueTable;	// IMP=0x0010000000065a0f
- (id)keyTable;	// IMP=0x0010000000065894
- (id)errorMessage;	// IMP=0x0010000000065857
- (int)errorCode;	// IMP=0x0010000000065849
- (_Bool)hasError;	// IMP=0x001000000006583b
- (_Bool)decodeMessage:(id)arg1 parser:(id)arg2 parameters:(id *)arg3 isInvalid:(_Bool *)arg4 lengthParsed:(unsigned long long *)arg5;	// IMP=0x0010000000065490
- (void)dealloc;	// IMP=0x0010000000065424
- (id)initWithMaxTableSize:(unsigned long long)arg1;	// IMP=0x0010000000065359

@end

