//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface APSCoreAnalyticsLogger : NSObject
{
    NSString *_domain;	// 8 = 0x8
}

+ (id)logger;	// IMP=0x0020000000051eb1
- (void).cxx_destruct;	// IMP=0x002000000005219c
@property(readonly, nonatomic) NSString *domain; // @synthesize domain=_domain;
- (void)logMetric:(id)arg1;	// IMP=0x0010000000051f8b
- (id)initWithDomain:(id)arg1;	// IMP=0x0010000000051f20

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

