//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray, NSString;

@interface PSAppChannelSubscriptionResponse : PBCodable
{
    NSString *_appId;	// 8 = 0x8
    NSMutableArray *_subscriptionChannelResponses;	// 16 = 0x10
    NSMutableArray *_unsubscriptionChannelResponses;	// 24 = 0x18
}

+ (Class)unsubscriptionChannelResponseType;	// IMP=0x002000000006c7c0
+ (Class)subscriptionChannelResponseType;	// IMP=0x001000000006c6ee
- (void).cxx_destruct;	// IMP=0x002000000006d9b9
@property(retain, nonatomic) NSMutableArray *unsubscriptionChannelResponses; // @synthesize unsubscriptionChannelResponses=_unsubscriptionChannelResponses;
@property(retain, nonatomic) NSMutableArray *subscriptionChannelResponses; // @synthesize subscriptionChannelResponses=_subscriptionChannelResponses;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000006d6e2
- (unsigned long long)hash;	// IMP=0x001000000006d675
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000006d57d
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000006d271
- (void)copyTo:(id)arg1;	// IMP=0x001000000006d0ee
- (void)writeTo:(id)arg1;	// IMP=0x001000000006cec2
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000006ceb5
- (id)dictionaryRepresentation;	// IMP=0x001000000006c880
- (id)description;	// IMP=0x001000000006c7d1
- (id)unsubscriptionChannelResponseAtIndex:(unsigned long long)arg1;	// IMP=0x001000000006c7a3
- (unsigned long long)unsubscriptionChannelResponsesCount;	// IMP=0x001000000006c786
- (void)addUnsubscriptionChannelResponse:(id)arg1;	// IMP=0x001000000006c71c
- (void)clearUnsubscriptionChannelResponses;	// IMP=0x001000000006c6ff
- (id)subscriptionChannelResponseAtIndex:(unsigned long long)arg1;	// IMP=0x001000000006c6d1
- (unsigned long long)subscriptionChannelResponsesCount;	// IMP=0x001000000006c6b4
- (void)addSubscriptionChannelResponse:(id)arg1;	// IMP=0x001000000006c64a
- (void)clearSubscriptionChannelResponses;	// IMP=0x001000000006c62d
@property(readonly, nonatomic) _Bool hasAppId;

@end

