//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface AKExpiringCache : NSObject
{
    NSMutableDictionary *_internalCache;	// 8 = 0x8
    struct os_unfair_lock_s _lock;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000001ed44
- (void)_flushCache;	// IMP=0x001000000001eaa4
- (void)setObject:(id)arg1 forKey:(id)arg2 expiresIn:(double)arg3;	// IMP=0x001000000001e8b9
- (void)removeObjectForKey:(id)arg1;	// IMP=0x001000000001e808
- (id)objectForKey:(id)arg1;	// IMP=0x001000000001e6c4
- (id)init;	// IMP=0x001000000001e657

@end

