//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AKGrandSlamRequestProvider
{
    _Bool _authenticatedRequest;	// 8 = 0x8
    unsigned long long _expectedResponseType;	// 16 = 0x10
}

// Error: Property attributes should begin with the type ('T') attribute, property name: expectedResponseType
// Property attributes: (null)

@property(nonatomic) _Bool authenticatedRequest; // @synthesize authenticatedRequest=_authenticatedRequest;
- (_Bool)validateResponseData:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000061fe3
- (_Bool)signRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000061d6e

@end

