//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AKPiggybackRequestingController, NSMutableDictionary, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface AKPiggybackController : NSObject
{
    NSMutableDictionary *_acceptingControllers;	// 8 = 0x8
    NSMutableDictionary *_pendingReplies;	// 16 = 0x10
    AKPiggybackRequestingController *_requestingController;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_piggybackingRequestQueue;	// 32 = 0x20
    NSOperationQueue *_circleRequestProcessingQueue;	// 40 = 0x28
    _Bool _requiresHSA2Repair;	// 48 = 0x30
}

+ (void)tearDown;	// IMP=0x002000000008721c
+ (id)sharedController;	// IMP=0x00100000000870a8
- (void).cxx_destruct;	// IMP=0x002000000008a114
- (double)_processingTimeOut;	// IMP=0x001000000008a106
- (id)performCircleRequestWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000088228
- (id)serviceControllerForContext:(id)arg1;	// IMP=0x00100000000881a6
- (void)startRequestSessionWithController:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000088074
- (void)_removeAcceptingControllerForTransaction:(id)arg1;	// IMP=0x0010000000087fc7
- (id)_acceptingControllerForTransactionId:(id)arg1;	// IMP=0x0010000000087db7
- (_Bool)_processPendingCompletionsForPayload:(id)arg1;	// IMP=0x0010000000087b42
- (_Bool)_hasPrimaryiCloudAccountForPayload:(id)arg1;	// IMP=0x0010000000087aa8
- (void)_processPiggybackPayload:(id)arg1;	// IMP=0x00100000000876af
- (void)processPushMessage:(id)arg1;	// IMP=0x0010000000087575
- (_Bool)shouldSuppressPushMessage:(id)arg1;	// IMP=0x00100000000872d1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

