//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface AKTTRController : NSObject
{
}

+ (id)sharedController;	// IMP=0x002000000008fb2e
- (void)requestTapToRadarWithTitle:(id)arg1 message:(id)arg2 componentName:(id)arg3 componentVersion:(id)arg4 componentID:(id)arg5;	// IMP=0x002000000008fea3
- (void)requestTapToRadarWithTitle:(id)arg1 message:(id)arg2;	// IMP=0x001000000008fe6f
- (void)processPushMessage:(id)arg1;	// IMP=0x001000000008fbb2
- (id)init;	// IMP=0x001000000008fb83

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

