//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ADServiceConnection, AFInstanceContext, NSArray, NSDictionary, NSObject, NSString;
@protocol OS_dispatch_group;

@interface ADBundleService
{
    NSDictionary *_domains;	// 8 = 0x8
    NSDictionary *;	// 16 = 0x10
    NSString *_path;	// 24 = 0x18
    NSString *_clearsDomainObjectsClassName;	// 32 = 0x20
    NSString *_maintenanceClassName;	// 40 = 0x28
    NSArray *_lockRestrictedCommands;	// 48 = 0x30
    _Bool _connectionNeedsContextCleared;	// 56 = 0x38
    ADServiceConnection *_connection;	// 64 = 0x40
    NSObject<OS_dispatch_group> *_group;	// 72 = 0x48
    AFInstanceContext *_instanceContext;	// 80 = 0x50
}

+ (id)requiredInfoDictionaryKeys;	// IMP=0x0020000000224db0
- (void).cxx_destruct;	// IMP=0x00200000002274f1
- (void)serviceConnectionTimedoutForSync;	// IMP=0x00100000002274a5
- (void)reload;	// IMP=0x0010000000227451
- (void)runMaintenanceWorkWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000002273d8
- (void)getInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000227252
- (void)resetExternalResources;	// IMP=0x0010000000227047
- (void)cancelOperationsForRequestID:(id)arg1 forAssistantID:(id)arg2 fromRemote:(_Bool)arg3;	// IMP=0x0010000000227041
- (void)fetchSyncSnapshotForInfo:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000226faf
- (void)beginSyncForInfo:(id)arg1 chunkHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000226e2b
- (void)clearDomainObjects;	// IMP=0x0010000000226d0d
- (void)handleCommand:(id)arg1 forDomain:(id)arg2 executionContext:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0010000000226ad5
- (void)preheatDomain:(id)arg1;	// IMP=0x0010000000226a98
- (id)syncKeys;	// IMP=0x0010000000226a7b
- (_Bool)implementsCommand:(id)arg1 forDomain:(id)arg2;	// IMP=0x00100000002269e7
- (id)commandsForDomain:(id)arg1;	// IMP=0x001000000022698c
- (id)domains;	// IMP=0x001000000022696f
- (id)handle;	// IMP=0x001000000022695a
- (id)initWithBundlePath:(id)arg1 infoDictionary:(id)arg2 instanceContext:(id)arg3;	// IMP=0x00100000002267bc
- (CDUnknownBlockType)_informCommandCenter:(id)arg1 willPerformLaunchApp:(id)arg2;	// IMP=0x0010000000226601
- (id)_connection;	// IMP=0x00100000002264b3
- (_Bool)_isValidRestrictionsDomainInfo:(id)arg1;	// IMP=0x0010000000226191
- (void)_parseInfoDictionary:(id)arg1;	// IMP=0x0010000000224eb9
- (id)lockRestrictedCommands;	// IMP=0x0010000000224d9b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

