//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ADDictationSessionTracker, AFDictationOptions, CoreEmbeddedSpeechRecognizer, NSMutableArray, NSString, NSXPCConnection, NSXPCListener;
@protocol AFDictationServiceDelegate, OS_dispatch_queue;

@interface ADDictationConnection : NSObject
{
    CoreEmbeddedSpeechRecognizer *_localSpeechRecognizer;	// 8 = 0x8
    _Bool _usingLocalSpeechRecognizer;	// 16 = 0x10
    id <AFDictationServiceDelegate> _serviceDelegate;	// 24 = 0x18
    AFDictationOptions *_dictationOptions;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_queue;	// 40 = 0x28
    _Bool _waitingForSpeechRecognition;	// 48 = 0x30
    _Bool _waitingForStructuredResultsOrVoiceSearch;	// 49 = 0x31
    _Bool _waitingForAudioFile;	// 50 = 0x32
    ADDictationSessionTracker *_sessionTracker;	// 56 = 0x38
    NSXPCListener *_pendingSpeechRequestListener;	// 64 = 0x40
    NSXPCConnection *_pendingSpeechRequestConnection;	// 72 = 0x48
    CDUnknownBlockType _pendingSpeechRequestContinue;	// 80 = 0x50
    _Bool _disconnected;	// 88 = 0x58
    CDUnknownBlockType _requestCompletion;	// 96 = 0x60
    _Bool _isDetectingUtterances;	// 104 = 0x68
    _Bool _shouldFinalizeRequestOnNextFinalResult;	// 105 = 0x69
    _Bool _didFinalizeUtteranceDetectionRequest;	// 106 = 0x6a
    NSMutableArray *_audioSessionAssertions;	// 112 = 0x70
    _Bool adSpeechSessionEnded;	// 120 = 0x78
}

- (void).cxx_destruct;	// IMP=0x002000000025df19
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) _Bool adSpeechSessionEnded; // @synthesize adSpeechSessionEnded;
- (void)_continuePendingSpeechRequestFromTimestamp:(double)arg1;	// IMP=0x001000000025dde3
- (oneway void)continuePendingSpeechRequestFromTimestamp:(double)arg1;	// IMP=0x001000000025dd75
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000025dc78
- (void)localSpeechRecognizer:(id)arg1 didCompletionRecognitionWithStatistics:(id)arg2 error:(id)arg3;	// IMP=0x001000000025db07
- (void)localSpeechRecognizer:(id)arg1 didRecognizePackage:(id)arg2;	// IMP=0x001000000025da5e
- (void)localSpeechRecognizer:(id)arg1 didRecognizePhrases:(id)arg2 utterances:(id)arg3;	// IMP=0x001000000025d966
- (void)localSpeechRecognizer:(id)arg1 didRecognizeRawEagerRecognitionCandidate:(id)arg2;	// IMP=0x001000000025d8f9
- (void)localSpeechRecognizer:(id)arg1 didProcessAudioDuration:(double)arg2;	// IMP=0x001000000025d887
- (void)localSpeechRecognizer:(id)arg1 didRecognizeTokens:(id)arg2;	// IMP=0x001000000025d7d7
- (id)_localSpeechRecognizerSupportingBackground:(_Bool)arg1;	// IMP=0x001000000025d649
- (id)_updateDictationOptionsForOnDeviceDictation:(id)arg1 language:(id)arg2;	// IMP=0x001000000025cef8
- (oneway void)reportIssueForError:(id)arg1 eventType:(long long)arg2 subtype:(id)arg3 context:(id)arg4;	// IMP=0x001000000025ccd5
- (oneway void)reportIssueForError:(id)arg1 eventType:(long long)arg2 context:(id)arg3;	// IMP=0x001000000025cad5
- (oneway void)requestOfflineDictationSupportForLanguage:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000025c9be
- (oneway void)requestOfflineAssistantSupportForLanguage:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000025c8a7
- (oneway void)getInstalledOfflineLanguagesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000025c6cf
- (oneway void)_sendEngagementFeedback:(long long)arg1 voiceQueryIdentifier:(id)arg2;	// IMP=0x001000000025c656
- (oneway void)_startDictationWithURL:(id)arg1 isNarrowBand:(_Bool)arg2 language:(id)arg3 options:(id)arg4;	// IMP=0x001000000025c3f0
- (oneway void)addRecordedSpeechSampleData:(id)arg1;	// IMP=0x001000000025c361
- (oneway void)startRecordedAudioDictationWithOptions:(id)arg1 language:(id)arg2 narrowband:(_Bool)arg3 forceSampling:(_Bool)arg4;	// IMP=0x001000000025b9b7
- (oneway void)recordAWDSuccessMetrics;	// IMP=0x001000000025b973
- (oneway void)recordFailureMetricsForError:(id)arg1;	// IMP=0x001000000025b8fd
- (oneway void)endSession;	// IMP=0x001000000025b7f8
- (oneway void)preheatWithRecordDeviceIdentifier:(id)arg1;	// IMP=0x001000000025b701
- (oneway void)preheatTestWithLanguage:(id)arg1 options:(id)arg2;	// IMP=0x001000000025b56e
- (oneway void)preheat;	// IMP=0x001000000025b4f8
- (oneway void)preheatForLanguageCode:(id)arg1;	// IMP=0x001000000025b38d
- (oneway void)sendUserSelectedAlternativeDictationLanguageCode:(id)arg1;	// IMP=0x001000000025b23f
- (oneway void)sendSpeechCorrectionInfo:(id)arg1 interactionIdentifier:(id)arg2;	// IMP=0x001000000025b1b3
- (oneway void)sendSpeechCorrectionInfo:(id)arg1 forCorrectionContext:(id)arg2;	// IMP=0x001000000025b11f
- (oneway void)updateSpeechOptions:(id)arg1;	// IMP=0x001000000025aff7
- (oneway void)stopSpeechWithOptions:(id)arg1;	// IMP=0x001000000025ae75
- (oneway void)cancelSpeech;	// IMP=0x001000000025adb6
- (oneway void)startDictationWithLanguageCode:(id)arg1 options:(id)arg2 speechOptions:(id)arg3;	// IMP=0x001000000025aabd
- (oneway void)startRecordingForPendingDictationWithLanguageCode:(id)arg1 options:(id)arg2 speechOptions:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x001000000025a629
- (void)_invokeRequestCompletion;	// IMP=0x001000000025a5d0
- (oneway void)startRequestActivityWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000025a4e2
- (void)_startDictationWithLanguageCode:(id)arg1 options:(id)arg2 speechOptions:(id)arg3 xpcconnection:(id)arg4;	// IMP=0x001000000025a3fc
- (id)_dictationWillStartWithLanguageCode:(id)arg1 options:(id)arg2 speechOptions:(id)arg3 xpcconnection:(id)arg4;	// IMP=0x001000000025a100
- (void)adSpeechDidBeginLocalRecognitionWithModelInfo:(id)arg1 sessionUUID:(id)arg2;	// IMP=0x001000000025a057
- (void)adSpeechMultilingualSpeechRecognized:(id)arg1 sessionUUID:(id)arg2;	// IMP=0x0010000000259f8b
- (void)adSpeechLanguageDetectorFailedWithError:(id)arg1;	// IMP=0x0010000000259ee2
- (void)adSpeechRecordingDidDetectLanguage:(id)arg1 confidenceScores:(id)arg2 isConfident:(_Bool)arg3;	// IMP=0x0010000000259df7
- (_Bool)adWaitingForAudioFile;	// IMP=0x0010000000259d4e
- (void)adAudioFileFinishedWriting:(id)arg1 error:(id)arg2 context:(id)arg3;	// IMP=0x0010000000259bb3
- (void)adPronunciationRecognized:(id)arg1 usingSpeechModel:(id)arg2 sessionUUID:(id)arg3;	// IMP=0x0010000000259887
- (void)adSpeechLocalRecognitionDidSucceedWithSessionUUID:(id)arg1;	// IMP=0x0010000000259695
- (void)adSpeechRecognitionDidFail:(id)arg1 sessionUUID:(id)arg2;	// IMP=0x00100000002594e6
- (void)adSpeechRecognizedStructuredResult:(id)arg1 usingSpeechModel:(id)arg2 sessionUUID:(id)arg3;	// IMP=0x0010000000259146
- (void)adSpeechRecordingDidRecognizePhrases:(id)arg1 utterances:(id)arg2 sessionUUID:(id)arg3 refId:(id)arg4;	// IMP=0x0010000000258c9d
- (void)adSpeechRecordingDidRecognizeTokens:(id)arg1 sessionUUID:(id)arg2;	// IMP=0x0010000000258c80
- (void)adSpeechDidFindVoiceSearchFinalResult:(id)arg1;	// IMP=0x0010000000258ae2
- (void)adSpeechDidFindVoiceSearchPartialResult:(id)arg1;	// IMP=0x00100000002589bb
- (void)adSpeechRecognizedPartialResult:(id)arg1;	// IMP=0x0010000000258848
- (void)adSpeechRecognized:(id)arg1 usingSpeechModel:(id)arg2 sessionUUID:(id)arg3;	// IMP=0x0010000000258502
- (void)adSpeechRecordingDidFail:(id)arg1 context:(id)arg2;	// IMP=0x001000000025828c
- (void)adSpeechRecordingDidCancelWithContext:(id)arg1;	// IMP=0x0010000000258005
- (void)adSpeechRecordingDidEndWithContext:(id)arg1;	// IMP=0x0010000000257f34
- (void)adSpeechRecordingDidChangeAVRecordRoute:(id)arg1 bluetoothDevice:(id)arg2 isDucking:(_Bool)arg3 isTwoShot:(_Bool)arg4 speechEndHostTime:(unsigned long long)arg5 context:(id)arg6;	// IMP=0x0010000000257f2e
- (void)adSpeechRecordingDidBeginOnAVRecordRoute:(id)arg1 audioSessionID:(unsigned int)arg2 bluetoothDevice:(id)arg3 sessionRequestUUID:(id)arg4 dictationOptions:(id)arg5 context:(id)arg6;	// IMP=0x0010000000257de2
- (void)adSpeechRecordingWillBeginWithInputAudioPowerXPCWrapper:(id)arg1 context:(id)arg2;	// IMP=0x0010000000257dcc
- (void)_removeAllAudioSessionAssertionsForReason:(id)arg1;	// IMP=0x0010000000257a15
- (void)_addAudioSessionAssertion:(id)arg1;	// IMP=0x00100000002579bb
- (void)_speechRecordingDidFinish;	// IMP=0x00100000002578d5
- (void)_updateDictationOptions:(id)arg1;	// IMP=0x00100000002578a8
- (void)connectionDisconnected;	// IMP=0x00100000002577e2
- (void)dealloc;	// IMP=0x0010000000257772
- (id)initWithServiceDelegate:(id)arg1;	// IMP=0x0010000000257654

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

