//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ADAnnouncementRequest, ADCallObserver, ADExternalNotificationRequestQueue, ADRequestDelayManager, AFNotifyObserver, AFWatchdogTimer, NSString;
@protocol OS_dispatch_queue;

@interface ADExternalNotificationRequestHandler : NSObject
{
    AFWatchdogTimer *_currentNotificationTimer;	// 8 = 0x8
    AFWatchdogTimer *_stateTimer;	// 16 = 0x10
    AFWatchdogTimer *_triggerlessUserReplyTimer;	// 24 = 0x18
    _Bool _triggerlessUserReplyTimerTimedOut;	// 32 = 0x20
    _Bool _triggerlessRequestEnteredListeningState;	// 33 = 0x21
    long long _currentState;	// 40 = 0x28
    ADRequestDelayManager *_currentRequestDelayManager;	// 48 = 0x30
    AFNotifyObserver *_clientStateObserver;	// 56 = 0x38
    ADCallObserver *_callObserver;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_queue;	// 72 = 0x48
    ADAnnouncementRequest *_previousRequest;	// 80 = 0x50
    ADAnnouncementRequest *_currentRequest;	// 88 = 0x58
    unsigned long long _synchronousBurstIndex;	// 96 = 0x60
    ADExternalNotificationRequestQueue *_requestQueue;	// 104 = 0x68
}

+ (id)sharedNotificationRequestHandler;	// IMP=0x002000000026ea1c
- (void).cxx_destruct;	// IMP=0x002000000027570c
- (void)_voicePromptStyleDidChange:(id)arg1;	// IMP=0x0010000000275706
- (void)voicePromptStyleDidChange:(id)arg1;	// IMP=0x0010000000275700
- (void)_adCallStateChangedCallIncoming:(_Bool)arg1;	// IMP=0x001000000027544d
- (void)adCallStateChangedCallIncoming:(_Bool)arg1;	// IMP=0x00100000002753e2
- (void)adCallStateChangedCallInProcess:(_Bool)arg1;	// IMP=0x00100000002753dc
- (void)notifyObserver:(id)arg1 didChangeStateFrom:(unsigned long long)arg2 to:(unsigned long long)arg3;	// IMP=0x001000000027520f
- (void)audioPlaybackService:(id)arg1 didStopRequest:(id)arg2 error:(id)arg3;	// IMP=0x0010000000275209
- (void)audioPlaybackService:(id)arg1 didStartRequest:(id)arg2;	// IMP=0x0010000000274f55
- (void)audioPlaybackService:(id)arg1 willStartRequest:(id)arg2;	// IMP=0x0010000000274f4f
- (void)requestDelayManager:(id)arg1 didStopUnexpectly:(_Bool)arg2;	// IMP=0x0010000000274efa
- (_Bool)requestDelayManager:(id)arg1 interruptedWithType:(long long)arg2;	// IMP=0x0010000000274b82
- (void)requestLifecycleObserver:(id)arg1 requestDidEndWithInfo:(id)arg2 origin:(long long)arg3 client:(id)arg4;	// IMP=0x0010000000274195
- (void)requestLifecycleObserver:(id)arg1 requestWasCancelledWithInfo:(id)arg2 origin:(long long)arg3 client:(id)arg4;	// IMP=0x0010000000273c42
- (void)requestLifecycleObserver:(id)arg1 requestWillBeginWithInfo:(id)arg2 origin:(long long)arg3 client:(id)arg4;	// IMP=0x001000000027356d
- (void)fetchUnreadNotificationsFromThreadAfterNotificationWithID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000027338c
- (void)_startTriggerlessFollowupRequestWithRequestDelayManager:(id)arg1 delayType:(long long)arg2;	// IMP=0x0010000000272d46
- (long long)announcePlatformForCurrentRequest;	// IMP=0x0010000000272bfd
- (void)audioSessionDidEnd;	// IMP=0x00100000002729eb
- (void)_withdrawalAnnouncementRequestForNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000002726de
- (void)withdrawalAnnouncementRequestForNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000272605
- (void)_deactivateForReason:(long long)arg1 source:(long long)arg2 event:(long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000002724b3
- (void)_deactivateCarPlayNotificationAnnouncementRequestForReason:(long long)arg1 notification:(id)arg2 sourceAppId:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000272084
- (void)_deactivateNotificationAnnouncementRequestForReason:(long long)arg1 notification:(id)arg2 sourceAppId:(id)arg3 platform:(long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000271fc3
- (void)deactivateNotificationAnnouncementRequestForReason:(long long)arg1 notification:(id)arg2 sourceAppId:(id)arg3 platform:(long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000271e8c
- (void)_stopCurrentRequestWithReason:(long long)arg1 shouldCancelRequest:(_Bool)arg2;	// IMP=0x0010000000271d0a
- (void)_clearCurrentNotificationTimer;	// IMP=0x0010000000271cd8
- (void)_startTimerToResetStateFrom:(long long)arg1;	// IMP=0x0010000000271bcb
- (void)_startRequestDelayManagerIfNeededForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000002717bc
- (void)_startAnnouncementRequest:(id)arg1;	// IMP=0x00100000002715d0
- (void)_startAnnouncementRequestWithRequestInfo:(id)arg1;	// IMP=0x001000000027126d
- (void)_handleNotification:(id)arg1 onPlatform:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000270b49
- (void)_handleAnnounceIncomingCallRequest:(id)arg1;	// IMP=0x001000000027074b
- (_Bool)_canAnnounceInCarPlay;	// IMP=0x0010000000270619
- (void)_handleAnnounceNotificationRequest:(id)arg1;	// IMP=0x001000000026f2c8
- (void)_handleAnnouncementRequest:(id)arg1;	// IMP=0x001000000026f23f
- (void)handleAnnouncementRequest:(id)arg1;	// IMP=0x001000000026f195
- (void)_changeCurrentStateToState:(long long)arg1;	// IMP=0x001000000026ee8d
- (void)_clearTriggerlessUserReplyTimer;	// IMP=0x001000000026edda
- (void)_clearRequestState;	// IMP=0x001000000026ed14
- (void)_completeNotificationsWithSuccess:(_Bool)arg1 forReason:(long long)arg2;	// IMP=0x001000000026ec85
- (id)_queue;	// IMP=0x001000000026ec77
- (void)_setCurrentRequest:(id)arg1;	// IMP=0x001000000026ec66
- (id)_currentRequest;	// IMP=0x001000000026ec58
- (long long)_currentState;	// IMP=0x001000000026ec4e
- (id)_requestQueue;	// IMP=0x001000000026ec40
- (id)_sharedCommandCenter;	// IMP=0x001000000026ec27
- (id)_init;	// IMP=0x001000000026ea81

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

