//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface ADSyncSnapshot : NSObject
{
    NSMutableDictionary *_pluginCache;	// 8 = 0x8
    NSMutableDictionary *_appsCache;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_saveTimer;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x00400000000a6823
- (void).cxx_destruct;	// IMP=0x00200000000a8c3e
- (void)_save;	// IMP=0x00100000000a863f
- (void)pruneCacheWithCurrentSynapseInfo:(id)arg1;	// IMP=0x00100000000a8574
- (_Bool)_pruneAppsCacheWithTruth:(id)arg1;	// IMP=0x00100000000a801c
- (void)_readFromDisk;	// IMP=0x00100000000a779c
- (_Bool)shouldIgnoreSyncKey:(id)arg1;	// IMP=0x00100000000a7735
- (void)deleteSavedSnapshots;	// IMP=0x00100000000a7675
- (void)noteSendingChunk:(id)arg1;	// IMP=0x00100000000a73ca
- (void)_noteSendingPostGen:(id)arg1 validity:(id)arg2 key:(id)arg3 appMetaData:(id)arg4;	// IMP=0x00100000000a7050
- (void)_scheduleSave;	// IMP=0x00100000000a6f02
- (void)_cancelSaveTimer;	// IMP=0x00100000000a6ecc
- (void)fetchSentAnchorsOnQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a6d91
- (void)_fetchSentAnchorsOnQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a6a72
- (id)_storePath;	// IMP=0x00100000000a6a24
- (id)init;	// IMP=0x00100000000a68a8

@end

