//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SAUIAssistantUtteranceView.h>

@interface SAUIAssistantUtteranceView (ADUIService)
- (void)_adui_notifyOthersOfArrival;	// IMP=0x00100000001ce207
- (_Bool)_adui_should_adui_notifyOthersOfArrival;	// IMP=0x00100000001ce1eb
- (_Bool)ad_shouldUseExtendedFlowTimeout;	// IMP=0x001000000028ae3e
@end

