//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <IDS/IDSDevice.h>

@interface SimulatorIDSDevice : IDSDevice
{
}

- (_Bool)isNearby;	// IMP=0x00400000001d4aa2
- (id)productVersion;	// IMP=0x00100000001d4a95
- (id)productName;	// IMP=0x00100000001d4a88
- (id)modelIdentifier;	// IMP=0x00100000001d4a7b
- (_Bool)isDefaultPairedDevice;	// IMP=0x00100000001d4a73

@end

