//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSXPCListener, VSServerKeepAliveManager;

@interface VSKeepAliveServer : NSObject
{
    NSXPCListener *_keepAliveListener;	// 8 = 0x8
    VSServerKeepAliveManager *_keepAliveManager;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000000eebb
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000000eda1
- (void)resume;	// IMP=0x001000000000ed8b
- (void)dealloc;	// IMP=0x001000000000ed31
- (id)init;	// IMP=0x001000000000ec89

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

