//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface (null) (callservicesd)
- (void)momentsServerDidDisconnect:(id)arg1;	// IMP=0x00200000002a0150
- (void)moments:(id)arg1 didEndProcessingRequest:(id)arg2 stillImageURL:(id)arg3 movieURL:(id)arg4 error:(id)arg5;	// IMP=0x001000000029ffc0
- (void)moments:(id)arg1 didEndProcessingRequest:(id)arg2 url:(id)arg3 error:(id)arg4;	// IMP=0x001000000029ff10
- (void)moments:(id)arg1 didStartProcessingRequest:(id)arg2 error:(id)arg3;	// IMP=0x001000000029fe60
- (void)moments:(id)arg1 didFinishRequest:(id)arg2 error:(id)arg3;	// IMP=0x001000000029fe40
- (void)moments:(id)arg1 capabilitiesDidChange:(unsigned int)arg2;	// IMP=0x001000000029fda0
@end

