//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSDConversationManager, CXProvider, FTDeviceSupport, FTNetworkSupport, NSMutableDictionary, NSMutableSet, NSString;
@protocol CSDConversationServerBag, CSDFaceTimeProviderDelegateManagerDelegate, OS_dispatch_queue, TUFeatureFlags;

@interface CSDFaceTimeConversationProviderDelegate : NSObject
{
    _Bool _audioSessionActive;	// 8 = 0x8
    NSMutableDictionary *_callUUIDsByConversationUUID;	// 16 = 0x10
    NSMutableDictionary *_conversationUUIDsByCallUUID;	// 24 = 0x18
    NSMutableSet *_conversationUUIDsWaitingToJoin;	// 32 = 0x20
    NSMutableSet *_conversationUUIDsWaitingForRemoteJoin;	// 40 = 0x28
    FTNetworkSupport *_networkSupport;	// 48 = 0x30
    id <CSDFaceTimeProviderDelegateManagerDelegate> _faceTimeDemuxerDelegate;	// 56 = 0x38
    id <TUFeatureFlags> _featureFlags;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_queue;	// 72 = 0x48
    NSMutableDictionary *_recentlyDeletedCallUUIDsByConversationUUID;	// 80 = 0x50
    CSDConversationManager *_conversationManager;	// 88 = 0x58
    CXProvider *_provider;	// 96 = 0x60
    CDUnknownBlockType _providerDidBegin;	// 104 = 0x68
    FTDeviceSupport *_deviceSupport;	// 112 = 0x70
    NSMutableSet *_conversationUUIDsAwaitingActiveAudioSession;	// 120 = 0x78
    id <CSDConversationServerBag> _serverBag;	// 128 = 0x80
}

+ (id)callScreenShareAttributesForAction:(id)arg1;	// IMP=0x00200000001404e7
- (void).cxx_destruct;	// IMP=0x002000000014168d
@property(readonly, nonatomic) id <CSDConversationServerBag> serverBag; // @synthesize serverBag=_serverBag;
@property(readonly, nonatomic) NSMutableSet *conversationUUIDsAwaitingActiveAudioSession; // @synthesize conversationUUIDsAwaitingActiveAudioSession=_conversationUUIDsAwaitingActiveAudioSession;
@property(nonatomic, getter=isAudioSessionActive) _Bool audioSessionActive; // @synthesize audioSessionActive=_audioSessionActive;
@property(retain, nonatomic) FTDeviceSupport *deviceSupport; // @synthesize deviceSupport=_deviceSupport;
@property(copy, nonatomic) CDUnknownBlockType providerDidBegin; // @synthesize providerDidBegin=_providerDidBegin;
@property(retain, nonatomic) CXProvider *provider; // @synthesize provider=_provider;
@property(readonly, nonatomic) CSDConversationManager *conversationManager; // @synthesize conversationManager=_conversationManager;
@property(readonly, nonatomic) NSMutableDictionary *recentlyDeletedCallUUIDsByConversationUUID; // @synthesize recentlyDeletedCallUUIDsByConversationUUID=_recentlyDeletedCallUUIDsByConversationUUID;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (id)featureFlags;	// IMP=0x00100000001415f7
@property(nonatomic) __weak id <CSDFaceTimeProviderDelegateManagerDelegate> faceTimeDemuxerDelegate; // @synthesize faceTimeDemuxerDelegate=_faceTimeDemuxerDelegate;
- (void)launchScreenSharingAppIfNecessary;	// IMP=0x00100000001415ca
- (void)provider:(id)arg1 timedOutPerformingAction:(id)arg2;	// IMP=0x001000000014145e
- (void)provider:(id)arg1 didDeactivateAudioSession:(id)arg2;	// IMP=0x00100000001413bd
- (void)provider:(id)arg1 didActivateAudioSession:(id)arg2;	// IMP=0x001000000014130a
- (void)provider:(id)arg1 performSetRelayingCallAction:(id)arg2;	// IMP=0x0010000000140fec
- (void)provider:(id)arg1 performSetVideoPresentationSizeCallAction:(id)arg2;	// IMP=0x0010000000140c8e
- (void)provider:(id)arg1 performSetVideoPresentationStateCallAction:(id)arg2;	// IMP=0x00100000001408a0
- (void)provider:(id)arg1 performSetScreenShareAttributesCallAction:(id)arg2;	// IMP=0x00100000001406cc
- (void)provider:(id)arg1 performEnableVideoCallAction:(id)arg2;	// IMP=0x00100000001400d5
- (void)provider:(id)arg1 performSetSharingScreenCallAction:(id)arg2;	// IMP=0x001000000013fb34
- (void)provider:(id)arg1 performSetSendingVideoCallAction:(id)arg2;	// IMP=0x001000000013f35a
- (void)provider:(id)arg1 performSetMutedCallAction:(id)arg2;	// IMP=0x001000000013f04e
- (void)provider:(id)arg1 performSetHeldCallAction:(id)arg2;	// IMP=0x001000000013ed74
- (void)leaveConversation:(id)arg1 withCallUUID:(id)arg2 reason:(long long)arg3;	// IMP=0x001000000013e8c1
- (void)leaveConversationForCallUUID:(id)arg1 endedReason:(long long)arg2;	// IMP=0x001000000013e4ab
- (void)cleanupConversationWithCallUUID:(id)arg1;	// IMP=0x001000000013e499
- (id)_findPendingConversationWithCallUUID:(id)arg1;	// IMP=0x001000000013e055
- (void)provider:(id)arg1 performEndCallAction:(id)arg2;	// IMP=0x001000000013dd20
- (void)proceedToJoinForConversation:(id)arg1 action:(id)arg2;	// IMP=0x001000000013d285
- (void)proceedToNewPendingConversationForLink:(id)arg1 action:(id)arg2;	// IMP=0x001000000013ce1a
- (void)provider:(id)arg1 performJoinCallAction:(id)arg2;	// IMP=0x001000000013a6d4
- (void)provider:(id)arg1 performAnswerCallAction:(id)arg2;	// IMP=0x001000000013a300
- (void)providerDidReset:(id)arg1;	// IMP=0x001000000013a1f2
- (void)providerDidBegin:(id)arg1;	// IMP=0x001000000013a0b2
- (void)endCallWithUUIDAsLocalHangup:(id)arg1;	// IMP=0x0010000000139fec
- (void)endCallWithUUIDAsDeclinedElsewhere:(id)arg1;	// IMP=0x0010000000139f28
- (void)endCallWithUUIDAsAnsweredElsewhere:(id)arg1;	// IMP=0x0010000000139e64
- (id)upgradeSessionUUIDForCallWithUUID:(id)arg1;	// IMP=0x0010000000139e5c
- (_Bool)hasCallStartedConnectingWithUUID:(id)arg1;	// IMP=0x0010000000139d46
- (id)pendingConversationUUIDForCallWithUUID:(id)arg1;	// IMP=0x0010000000139a98
- (_Bool)isManagingPendingConversationForCallWithUUID:(id)arg1;	// IMP=0x0010000000139812
- (_Bool)isManagingCallWithUUID:(id)arg1;	// IMP=0x00100000001396bf
- (void)_failConversation:(id)arg1 failureReason:(long long)arg2 providerEndedReason:(long long)arg3;	// IMP=0x001000000013942b
- (void)conversationManager:(id)arg1 reportedInvalidLinkForPendingConversation:(id)arg2;	// IMP=0x00100000001393a6
- (void)conversationManager:(id)arg1 reportedLetMeInRejectedForPendingConversation:(id)arg2;	// IMP=0x0010000000139321
- (void)conversationManager:(id)arg1 conversation:(id)arg2 changedBytesOfDataUsed:(long long)arg3;	// IMP=0x0010000000139119
- (void)conversationManager:(id)arg1 removedConversationWithUUID:(id)arg2;	// IMP=0x0010000000138f0f
- (void)conversationManager:(id)arg1 conversation:(id)arg2 removedActiveParticipant:(id)arg3;	// IMP=0x0010000000138c60
- (void)conversationManager:(id)arg1 conversation:(id)arg2 addedActiveParticipant:(id)arg3;	// IMP=0x00100000001386f3
- (void)conversationManager:(id)arg1 conversation:(id)arg2 failedWithContext:(id)arg3;	// IMP=0x0010000000138587
- (void)conversationManager:(id)arg1 reportedNewIncomingConversation:(id)arg2 fromHandle:(id)arg3;	// IMP=0x0010000000138367
- (void)conversationManager:(id)arg1 conversation:(id)arg2 receivedMessage:(id)arg3 fromHandle:(id)arg4 withUpdate:(id)arg5;	// IMP=0x001000000013829e
- (void)conversationManager:(id)arg1 conversationScreenSharingChanged:(id)arg2 forParticipant:(id)arg3;	// IMP=0x00100000001381ac
- (void)conversationManager:(id)arg1 conversationChanged:(id)arg2;	// IMP=0x001000000013727a
- (int)TUCallRemoteVideoPresentationStateFromCXVideoPresentationState:(long long)arg1;	// IMP=0x001000000013725f
- (void)declineConversation:(id)arg1 reason:(long long)arg2 destinations:(id)arg3;	// IMP=0x0010000000136e93
- (void)declineRemoteMembersForConversation:(id)arg1 reason:(long long)arg2;	// IMP=0x0010000000136c18
- (void)declineRemoteDevicesForConversation:(id)arg1 reason:(long long)arg2;	// IMP=0x0010000000136967
- (_Bool)isUnansweredOutgoingOneToOneConversation:(id)arg1;	// IMP=0x00100000001368ab
- (void)startOutgoingOneToOneTimeoutIfNecessary:(id)arg1;	// IMP=0x00100000001364b5
- (void)fullfillPendingJoinActionsForCallUUIDIfNecessary:(id)arg1;	// IMP=0x001000000013611b
- (void)enqueueOrStartAudioForConversationUUID:(id)arg1;	// IMP=0x0010000000136061
- (void)associateCallUUID:(id)arg1 withConversationUUID:(id)arg2 waitingToJoin:(_Bool)arg3;	// IMP=0x0010000000135fc2
- (void)reportNewIncomingCallForConversation:(id)arg1 fromHandle:(id)arg2;	// IMP=0x0010000000135407
- (void)handleRespondedElsewhereMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3;	// IMP=0x001000000013532d
- (void)handleRespondedElsewhereMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3 withAliases:(id)arg4;	// IMP=0x0010000000134e63
- (void)handleInvitationMessageForLetMeIn:(id)arg1 forConversation:(id)arg2 pendingConversation:(id)arg3 link:(id)arg4 fromHandle:(id)arg5;	// IMP=0x0010000000134640
- (void)handleInvitationMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3;	// IMP=0x0010000000133dd6
- (void)handleRemoveMembersMessage:(id)arg1 forConversation:(id)arg2;	// IMP=0x0010000000133b1f
- (void)handleUpgradeMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3 withUpdate:(id)arg4;	// IMP=0x0010000000132b2c
- (void)handleReceivedVideoUpgradeMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3;	// IMP=0x0010000000132610
- (void)handleScreenShareMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3 withUpdate:(id)arg4;	// IMP=0x00100000001325b4
- (void)handleNicknameUpdateMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3 withUpdate:(id)arg4;	// IMP=0x0010000000132429
- (void)handleDeclineMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3 withUpdate:(id)arg4;	// IMP=0x00100000001321c0
- (void)handleMessage:(id)arg1 forConversation:(id)arg2 fromHandle:(id)arg3 withUpdate:(id)arg4;	// IMP=0x0010000000131d67
- (void)cleanUpConversationIfNecessaryForConversationUUID:(id)arg1 failureContext:(id)arg2;	// IMP=0x00100000001317a9
- (void)startAudioForConversationsIfNecessary;	// IMP=0x0010000000131539
- (void)enqueueConversationWaitingForAudioWithConversationUUID:(id)arg1;	// IMP=0x00100000001314ba
- (_Bool)usesAudioSession;	// IMP=0x00100000001314b2
- (void)setWaitingForRemoteJoin:(_Bool)arg1 forConversationUUID:(id)arg2;	// IMP=0x0010000000131405
@property(readonly, nonatomic) NSMutableSet *conversationUUIDsWaitingForRemoteJoin; // @synthesize conversationUUIDsWaitingForRemoteJoin=_conversationUUIDsWaitingForRemoteJoin;
- (_Bool)isWaitingForRemoteJoinForConversationUUID:(id)arg1;	// IMP=0x0010000000131328
- (void)setWaitingToJoin:(_Bool)arg1 forConversationUUID:(id)arg2;	// IMP=0x001000000013127b
- (_Bool)_isWaitingToJoinForConversationUUID:(id)arg1;	// IMP=0x00100000001311de
- (_Bool)isWaitingToJoinForConversationUUID:(id)arg1;	// IMP=0x00100000001310a6
@property(readonly, nonatomic) FTNetworkSupport *networkSupport; // @synthesize networkSupport=_networkSupport;
@property(readonly, nonatomic) NSMutableSet *conversationUUIDsWaitingToJoin; // @synthesize conversationUUIDsWaitingToJoin=_conversationUUIDsWaitingToJoin;
- (void)setConversationUUID:(id)arg1 forCallUUID:(id)arg2;	// IMP=0x0010000000130f3a
- (id)conversationUUIDForCallUUID:(id)arg1;	// IMP=0x0010000000130d8c
@property(readonly, nonatomic) NSMutableDictionary *conversationUUIDsByCallUUID; // @synthesize conversationUUIDsByCallUUID=_conversationUUIDsByCallUUID;
- (void)updateNetworkCriticalStateIfNecessary;	// IMP=0x0010000000130be0
- (void)setCallUUID:(id)arg1 forConversationUUID:(id)arg2;	// IMP=0x00100000001308d1
- (id)callUUIDForConversationUUID:(id)arg1;	// IMP=0x00100000001306fb
@property(readonly, nonatomic) NSMutableDictionary *callUUIDsByConversationUUID; // @synthesize callUUIDsByConversationUUID=_callUUIDsByConversationUUID;
- (id)initWithQueue:(id)arg1 conversationManager:(id)arg2 networkSupport:(id)arg3 serverBag:(id)arg4 featureFlags:(id)arg5;	// IMP=0x00100000001304af
- (id)initWithConversationManager:(id)arg1 queue:(id)arg2;	// IMP=0x0010000000130408

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

