//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSArray, NSMutableDictionary, NSSet, NSString;
@protocol CSDConversationServerBag, CSDIDSGroupSessionDelegate, CSDIDSGroupSessionProvider, TUFeatureFlags;

@interface CSDIDSGroupSession
{
    _Bool _joined;	// 8 = 0x8
    MISSING_TYPE *_delegate;	// 16 = 0x10
    unsigned long long _localParticipantIdentifier;	// 24 = 0x18
    id <TUFeatureFlags> _featureFlags;	// 32 = 0x20
    id <CSDIDSGroupSessionProvider> _sessionProvider;	// 40 = 0x28
    unsigned long long _retryCount;	// 48 = 0x30
    unsigned long long _lightweightRetryCount;	// 56 = 0x38
    id <CSDConversationServerBag> _serverBag;	// 64 = 0x40
    NSMutableDictionary *_preferences;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x002000000010dd13
@property(readonly, nonatomic) NSMutableDictionary *preferences; // @synthesize preferences=_preferences;
@property(retain, nonatomic) id <CSDConversationServerBag> serverBag; // @synthesize serverBag=_serverBag;
@property(nonatomic) unsigned long long lightweightRetryCount; // @synthesize lightweightRetryCount=_lightweightRetryCount;
@property(nonatomic) unsigned long long retryCount; // @synthesize retryCount=_retryCount;
@property(readonly, nonatomic) id <CSDIDSGroupSessionProvider> sessionProvider; // @synthesize sessionProvider=_sessionProvider;
@property(readonly, nonatomic) id <TUFeatureFlags> featureFlags; // @synthesize featureFlags=_featureFlags;
@property(nonatomic) unsigned long long localParticipantIdentifier; // @synthesize localParticipantIdentifier=_localParticipantIdentifier;
@property(nonatomic, getter=isJoined) _Bool joined; // @synthesize joined=_joined;
@property(nonatomic) __weak id <CSDIDSGroupSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)sessionProviderDidReceiveKeyUpdate:(id)arg1;	// IMP=0x001000000010dbbc
- (void)sessionProvider:(id)arg1 didUnregisterPluginAllocationInfo:(id)arg2;	// IMP=0x001000000010db47
- (void)sessionProvider:(id)arg1 didRegisterPluginAllocationInfo:(id)arg2;	// IMP=0x001000000010dad2
- (void)sessionProvider:(id)arg1 didReceiveKickedParticipantIDs:(id)arg2 withCode:(unsigned int)arg3 withType:(unsigned short)arg4 isTruncated:(_Bool)arg5;	// IMP=0x001000000010da42
- (void)sessionProvider:(id)arg1 didReceiveReport:(id)arg2;	// IMP=0x001000000010d9cd
- (void)sessionProvider:(id)arg1 didReceiveActiveLightweightParticipants:(id)arg2 success:(_Bool)arg3;	// IMP=0x001000000010d487
- (void)sessionProvider:(id)arg1 didReceiveActiveParticipants:(id)arg2 success:(_Bool)arg3;	// IMP=0x001000000010cf41
- (void)sessionProviderDidTerminate:(id)arg1;	// IMP=0x001000000010ce5c
- (void)sessionProvider:(id)arg1 didLeaveGroupWithError:(id)arg2;	// IMP=0x001000000010cd3f
- (void)sessionProvider:(id)arg1 didJoinGroupWithParticipantIdentifiers:(id)arg2 localParticipantIdentifier:(unsigned long long)arg3 error:(id)arg4;	// IMP=0x001000000010ca7c
- (void)sessionProvider:(id)arg1 endedWithReason:(unsigned int)arg2 error:(id)arg3;	// IMP=0x001000000010c94a
- (unsigned long long)callTypeForJoinContext:(id)arg1;	// IMP=0x001000000010c929
- (id)idsDestinationForActiveParticipant:(id)arg1;	// IMP=0x001000000010c82d
- (void)addRequiredCapabilities:(id)arg1 requiredLackOfCapabilities:(id)arg2;	// IMP=0x001000000010c72f
@property(readonly, nonatomic) NSSet *requiredLackOfCapabilities;
@property(readonly, nonatomic) NSSet *requiredCapabilities;
- (void)participantIDForAlias:(unsigned long long)arg1 salt:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000010c584
- (unsigned long long)participantIDForAlias:(unsigned long long)arg1 salt:(id)arg2;	// IMP=0x001000000010c491
- (void)addAliasesToConversationContainer:(id)arg1 withSalt:(id)arg2;	// IMP=0x001000000010c393
- (void)requestEncryptionKeyForParticipants:(id)arg1 topic:(id)arg2;	// IMP=0x001000000010c295
- (void)requestDataCryptorForTopic:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000010c197
- (void)allowMember:(id)arg1;	// IMP=0x001000000010c06a
- (void)kickMember:(id)arg1;	// IMP=0x001000000010bf3d
- (void)reconnect;	// IMP=0x001000000010be71
- (void)restart;	// IMP=0x001000000010bd96
- (void)registerPluginWithOptions:(id)arg1;	// IMP=0x001000000010bcb1
- (void)leave;	// IMP=0x001000000010bbe5
- (void)requestActiveParticipants;	// IMP=0x001000000010bb19
- (void)sendLocalParticipantData:(id)arg1;	// IMP=0x001000000010baa7
- (void)addMembers:(id)arg1 toExistingMembers:(id)arg2 participantDestinationIDs:(id)arg3 webDestinationIDs:(id)arg4 activeParticipants:(id)arg5 activitySessions:(id)arg6 link:(id)arg7 otherInvitedHandles:(id)arg8 report:(id)arg9 invitationPreferences:(id)arg10;	// IMP=0x001000000010ad95
- (void)addMembers:(id)arg1 toExistingMembers:(id)arg2 activeParticipants:(id)arg3 activitySessions:(id)arg4 link:(id)arg5 otherInvitedHandles:(id)arg6 report:(id)arg7 invitationPreferences:(id)arg8 requiredCapabilities:(id)arg9 messagesGroupUUID:(id)arg10 messagesGroupName:(id)arg11 addingFromLetMeIn:(_Bool)arg12 triggeredLocally:(_Bool)arg13;	// IMP=0x00100000001096bc
- (void)addMembers:(id)arg1 toExistingMembers:(id)arg2 activeParticipants:(id)arg3 activitySessions:(id)arg4 report:(id)arg5 triggeredLocally:(_Bool)arg6;	// IMP=0x00100000001095af
- (void)removeMembers:(id)arg1 fromExistingMembers:(id)arg2 activeParticipants:(id)arg3 triggeredLocally:(_Bool)arg4;	// IMP=0x0010000000108fc3
- (void)joinUsingContext:(id)arg1 localParticipantAVCData:(id)arg2 members:(id)arg3 otherInvitedHandles:(id)arg4 participantDestinationIDs:(id)arg5 link:(id)arg6 report:(id)arg7;	// IMP=0x00100000001084eb
@property(readonly, copy, nonatomic) NSArray *participantDestinationIDs;
@property(readonly, copy, nonatomic) NSString *idsDestination;
- (id)initWithGroupSessionProvider:(id)arg1;	// IMP=0x00100000001083e7
- (id)initWithGroupSessionProvider:(id)arg1 featureFlags:(id)arg2;	// IMP=0x0010000000108269

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

