//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSDFaceTimeProviderDelegate, MISSING_TYPE, OS_dispatch_queue;

@interface CSDNeighborhoodActivityConduit : NSObject
{
    MISSING_TYPE *messenger;	// 8 = 0x8
    MISSING_TYPE *cancellables;	// 16 = 0x10
    MISSING_TYPE *queue;	// 24 = 0x18
    MISSING_TYPE *conversationManager;	// 32 = 0x20
    MISSING_TYPE *conversationServerBag;	// 40 = 0x28
    MISSING_TYPE *delegatesToQueues;	// 48 = 0x30
    MISSING_TYPE *featureFlags;	// 56 = 0x38
    MISSING_TYPE *activityConversationUUIDsByUserProfileNearbyDevice;	// 64 = 0x40
    MISSING_TYPE *pendingConversationsByIDHash;	// 72 = 0x48
    MISSING_TYPE *currentSplitSession;	// 0 = 0x0
    MISSING_TYPE *pendingSplitSession;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *pendingSplitSessionTimeoutTimer;	// 3608152 = 0x370e58
    MISSING_TYPE *currentUserProfileIdentifier;	// 1328 = 0x530
    MISSING_TYPE *faceTimeProviderDelegate;	// 1936941407 = 0x7373615f
    MISSING_TYPE *proxyMessageDeduplicator;	// 3608152 = 0x370e58
    MISSING_TYPE *idsProxyCleanupTimer;	// 0 = 0x0
    MISSING_TYPE *conversationIDsWithActivities;	// 0 = 0x0
    MISSING_TYPE *stateHandle;	// 0 = 0x0
    MISSING_TYPE *stagedJoinConversationRequests;	// 0 = 0x0
    MISSING_TYPE *conversationMonitorCancellables;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x00400000002ad5d0
- (id)init;	// IMP=0x00100000002c2ab0
- (void)handleIncomingCall:(id)arg1;	// IMP=0x00100000002b77e0
- (void)cancelPendingJoinConversation;	// IMP=0x00100000002b64b0
- (void)joinConversationWithID:(id)arg1 onDevice:(id)arg2 withContext:(long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000002b59e0
- (void)getSplitSessionInfo:(CDUnknownBlockType)arg1;	// IMP=0x00100000002b1e30
- (void)getNearbyConversationsForProfileIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000002b1420
- (void)getNearbyConversations:(CDUnknownBlockType)arg1;	// IMP=0x00100000002b1200
- (void)removeDelegate:(id)arg1;	// IMP=0x00100000002ade50
- (void)addDelegate:(id)arg1 queue:(id)arg2;	// IMP=0x00100000002ada50
- (void)dealloc;	// IMP=0x00100000002ad530
- (id)initWithQueue:(id)arg1 conversationManager:(id)arg2;	// IMP=0x00100000002ab6e0
@property(nonatomic) __weak CSDFaceTimeProviderDelegate *faceTimeProviderDelegate; // @synthesize faceTimeProviderDelegate;
@property(nonatomic, readonly) OS_dispatch_queue *queue; // @synthesize queue;
- (void)userProfileManagerDidUpdate:(id)arg1;	// IMP=0x00100000001a8c00
- (void)proxyGroupUpdate:(id)arg1 forConversationManager:(id)arg2;	// IMP=0x00100000001db3a0
- (_Bool)shouldIgnoreIDSResource:(id)arg1 metadata:(id)arg2 fromID:(id)arg3 context:(id)arg4;	// IMP=0x00100000001db2a0
- (_Bool)shouldIgnoreIDSMessage:(id)arg1 fromID:(id)arg2 context:(id)arg3;	// IMP=0x00100000001db1e0

@end

