//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AVAudioSession, CSDPauseDigitsQueue, CXCallFailureContext, CXCallSource, CXCallUpdate, MISSING_TYPE, NSString, NSUUID, TUCallScreenShareAttributes;
@protocol CSDProviderCallDelegate, TUFeatureFlags;

@interface CSDProviderCall
{
    _Bool _outgoing;	// 8 = 0x8
    _Bool _wantsStagingArea;	// 9 = 0x9
    _Bool _video;	// 10 = 0xa
    _Bool _sharingScreen;	// 11 = 0xb
    _Bool _expanseProvider;	// 12 = 0xc
    _Bool _mixesVoiceWithMedia;	// 13 = 0xd
    _Bool _mediaPlaybackOnExternalDevice;	// 14 = 0xe
    _Bool _held;	// 15 = 0xf
    _Bool _sendingVideo;	// 16 = 0x10
    _Bool _underlyingUplinkMuted;	// 17 = 0x11
    int _ttyType;	// 20 = 0x14
    id <TUFeatureFlags> _featureFlags;	// 24 = 0x18
    long long _bluetoothAudioFormat;	// 32 = 0x20
    TUCallScreenShareAttributes *_screenShareAttributes;	// 40 = 0x28
    id <CSDProviderCallDelegate> _providerCallDelegate;	// 48 = 0x30
    CXCallSource *_backingCallSource;	// 56 = 0x38
    long long _endedReason;	// 64 = 0x40
    CXCallFailureContext *_failureContext;	// 72 = 0x48
    NSString *_backingCallSourceIdentifier;	// 80 = 0x50
    MISSING_TYPE *_displayCallSourceIdentifier;	// 88 = 0x58
    CXCallUpdate *_mergedCallUpdate;	// 96 = 0x60
    CSDPauseDigitsQueue *_pauseDigitsQueue;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x0020000000045558
@property(retain, nonatomic) CSDPauseDigitsQueue *pauseDigitsQueue; // @synthesize pauseDigitsQueue=_pauseDigitsQueue;
@property(retain, nonatomic) CXCallUpdate *mergedCallUpdate; // @synthesize mergedCallUpdate=_mergedCallUpdate;
@property(copy, nonatomic) NSString *displayCallSourceIdentifier; // @synthesize displayCallSourceIdentifier=_displayCallSourceIdentifier;
@property(readonly, copy, nonatomic) NSString *backingCallSourceIdentifier; // @synthesize backingCallSourceIdentifier=_backingCallSourceIdentifier;
@property(retain, nonatomic) CXCallFailureContext *failureContext; // @synthesize failureContext=_failureContext;
@property(nonatomic, getter=isUnderlyingUplinkMuted) _Bool underlyingUplinkMuted; // @synthesize underlyingUplinkMuted=_underlyingUplinkMuted;
@property(nonatomic) _Bool sendingVideo; // @synthesize sendingVideo=_sendingVideo;
@property(nonatomic) long long endedReason; // @synthesize endedReason=_endedReason;
@property(nonatomic, getter=isHeld) _Bool held; // @synthesize held=_held;
@property(retain, nonatomic) CXCallSource *backingCallSource; // @synthesize backingCallSource=_backingCallSource;
@property(nonatomic) __weak id <CSDProviderCallDelegate> providerCallDelegate; // @synthesize providerCallDelegate=_providerCallDelegate;
@property(readonly, nonatomic) _Bool mediaPlaybackOnExternalDevice; // @synthesize mediaPlaybackOnExternalDevice=_mediaPlaybackOnExternalDevice;
@property(readonly, nonatomic, getter=isExpanseProvider) _Bool expanseProvider; // @synthesize expanseProvider=_expanseProvider;
- (id)screenShareAttributes;	// IMP=0x00100000000453f5
- (_Bool)isSharingScreen;	// IMP=0x00100000000453e5
@property(nonatomic) _Bool wantsStagingArea; // @synthesize wantsStagingArea=_wantsStagingArea;
- (_Bool)isOutgoing;	// IMP=0x00100000000453b5
@property(readonly, nonatomic) id <TUFeatureFlags> featureFlags; // @synthesize featureFlags=_featureFlags;
- (oneway void)handleAudioSessionActivationStateChangedTo:(_Bool)arg1;	// IMP=0x001000000004532d
- (void)pauseDigitsQueueChanged:(id)arg1;	// IMP=0x0010000000045271
- (void)_sendSoftPauseDigitsIfNecessary;	// IMP=0x00100000000450f0
- (void)_sendDTMFDigits:(id)arg1 type:(long long)arg2;	// IMP=0x0010000000044f9b
- (id)tuScreenShareAttributesForScreenAttributes:(id)arg1;	// IMP=0x0010000000044d48
- (id)cxScreenShareAttributesForCallAttributes:(id)arg1;	// IMP=0x0010000000044b6c
- (void)dequeueNextPauseDigits;	// IMP=0x0010000000044ab3
- (void)setRemoteVideoPresentationState:(int)arg1;	// IMP=0x001000000004496a
- (void)setRemoteVideoPresentationSize:(struct CGSize)arg1;	// IMP=0x001000000004480c
- (void)playRemoteDTMFToneForKey:(unsigned char)arg1;	// IMP=0x00100000000446de
- (void)sendHardPauseDigits;	// IMP=0x00100000000444e7
- (void)setDownlinkMuted:(_Bool)arg1;	// IMP=0x0010000000044494
@property(nonatomic) int ttyType; // @synthesize ttyType=_ttyType;
- (void)setUplinkMuted:(_Bool)arg1;	// IMP=0x0010000000044040
- (void)setSharingScreen:(_Bool)arg1 attributes:(id)arg2;	// IMP=0x0010000000043d0f
- (void)setSharingScreen:(_Bool)arg1;	// IMP=0x0010000000043bc5
- (void)setScreenShareAttributes:(id)arg1;	// IMP=0x00100000000439cd
- (void)setIsSendingVideo:(_Bool)arg1;	// IMP=0x00100000000438f9
- (void)setProviderFailureReasonIfNecessary:(long long)arg1;	// IMP=0x001000000004380c
- (void)disconnectWithReason:(int)arg1;	// IMP=0x0010000000043746
- (void)ungroup;	// IMP=0x001000000004367e
- (void)groupWithOtherCall:(id)arg1;	// IMP=0x001000000004356e
- (void)_setIsOnHold:(_Bool)arg1;	// IMP=0x0010000000043472
- (void)unhold;	// IMP=0x001000000004342f
- (void)hold;	// IMP=0x00100000000433e9
- (void)answerWithRequest:(id)arg1;	// IMP=0x00100000000431d7
- (void)joinConversationWithRequest:(id)arg1;	// IMP=0x00100000000420cc
- (void)dialWithRequest:(id)arg1 displayContext:(id)arg2;	// IMP=0x0010000000041f73
- (id)startCallActionWithDialRequest:(id)arg1;	// IMP=0x0010000000041c39
- (void)setMediaPlaybackOnExternalDevice:(_Bool)arg1;	// IMP=0x0010000000041b94
- (void)setMixesVoiceWithMedia:(_Bool)arg1;	// IMP=0x0010000000041aef
@property(nonatomic) long long bluetoothAudioFormat; // @synthesize bluetoothAudioFormat=_bluetoothAudioFormat;
- (void)setTTYType:(int)arg1;	// IMP=0x001000000004193e
- (void)setEndpointOnCurrentDevice:(_Bool)arg1;	// IMP=0x0010000000041853
- (void)setDateConnected:(id)arg1;	// IMP=0x00100000000417fb
@property(copy, nonatomic) NSUUID *callGroupUUID;
@property(nonatomic, getter=isVideo) _Bool video; // @synthesize video=_video;
- (void)setOutgoing:(_Bool)arg1;	// IMP=0x00100000000413fe
- (_Bool)usesSystemMuting;	// IMP=0x001000000004132b
- (long long)outputAudioPowerSpectrumToken;	// IMP=0x0010000000041257
- (long long)inputAudioPowerSpectrumToken;	// IMP=0x0010000000041183
- (unsigned long long)initialLinkType;	// IMP=0x00100000000410af
- (CDStruct_6ad76789)providerAuditToken;	// IMP=0x0010000000041051
- (int)providerProcessIdentifier;	// IMP=0x001000000004100d
- (_Bool)isDownlinkMuted;	// IMP=0x0010000000040fc2
- (_Bool)isUplinkMuted;	// IMP=0x0010000000040f21
- (_Bool)isSendingVideo;	// IMP=0x0010000000040f0f
- (int)hardPauseDigitsState;	// IMP=0x0010000000040e52
- (id)hardPauseDigits;	// IMP=0x0010000000040d70
- (_Bool)hasEnded;	// IMP=0x0010000000040d3d
- (_Bool)hasConnected;	// IMP=0x0010000000040d0a
- (_Bool)hasStartedConnecting;	// IMP=0x0010000000040cd7
- (int)callStatusFromUnderlyingSource;	// IMP=0x0010000000040c3c
- (id)displayProvider;	// IMP=0x0010000000040b6e
- (id)backingProvider;	// IMP=0x0010000000040aee
- (_Bool)isConversation;	// IMP=0x0010000000040aaa
- (int)originatingUIType;	// IMP=0x0010000000040a5e
- (_Bool)isMutuallyExclusiveCall;	// IMP=0x0010000000040a1a
- (_Bool)shouldSuppressInCallUI;	// IMP=0x00100000000409d6
- (_Bool)prefersExclusiveAccessToCellularNetwork;	// IMP=0x0010000000040992
- (_Bool)mayRequireBreakBeforeMake;	// IMP=0x001000000004094e
- (id)remoteParticipantHandles;	// IMP=0x001000000004084a
- (id)handoffActivityUserInfo;	// IMP=0x0010000000040738
- (id)handoffDynamicIdentifier;	// IMP=0x00100000000406be
- (_Bool)isFailureExpected;	// IMP=0x001000000004067a
- (_Bool)isEmergency;	// IMP=0x0010000000040636
- (_Bool)supportsTTYWithVoice;	// IMP=0x00100000000405a6
- (_Bool)isOneToOneModeEnabled;	// IMP=0x0010000000040516
- (id)providerContext;	// IMP=0x00100000000404c6
@property(readonly, nonatomic) _Bool ignoresBluetoothDeviceUID;
@property(readonly, nonatomic) _Bool mixesVoiceWithMedia; // @synthesize mixesVoiceWithMedia=_mixesVoiceWithMedia;
- (long long)soundRegion;	// IMP=0x00100000000403ee
- (_Bool)needsManualInCallSounds;	// IMP=0x00100000000403aa
- (id)audioMode;	// IMP=0x00100000000402d9
- (id)audioCategory;	// IMP=0x0010000000040208
@property(readonly, nonatomic) AVAudioSession *proxyAVAudioSession;
- (long long)audioInterruptionOperationMode;	// IMP=0x00100000000400ea
- (long long)audioInterruptionProviderType;	// IMP=0x0010000000040091
- (id)activeRemoteParticipants;	// IMP=0x001000000003ff95
- (id)localSenderIdentityAccountUUID;	// IMP=0x001000000003fe9c
- (id)localSenderIdentityUUID;	// IMP=0x001000000003fe4c
- (id)isoCountryCode;	// IMP=0x001000000003fdfc
- (_Bool)isRemoteUplinkMuted;	// IMP=0x001000000003fdb8
- (long long)videoStreamToken;	// IMP=0x001000000003fd74
- (_Bool)isThirdPartyVideo;	// IMP=0x001000000003fcf1
- (_Bool)isBlocked;	// IMP=0x001000000003fc47
- (_Bool)isUsingBaseband;	// IMP=0x001000000003fb95
- (id)handle;	// IMP=0x001000000003f9ed
- (id)callHistoryIdentifier;	// IMP=0x001000000003f923
- (id)callerNameFromNetwork;	// IMP=0x001000000003f883
- (long long)providerEndedReason;	// IMP=0x001000000003f83f
- (long long)providerErrorCode;	// IMP=0x001000000003f7fb
- (id)endedReasonUserInfo;	// IMP=0x001000000003f79c
- (void)updateForDisconnection;	// IMP=0x001000000003e984
- (void)updateWithCallUpdate:(id)arg1;	// IMP=0x001000000003e285
- (_Bool)canBeControlledByCallSource:(id)arg1;	// IMP=0x001000000003e1c4
- (void)systemMuteStatusChanged:(id)arg1;	// IMP=0x001000000003e078
- (void)dealloc;	// IMP=0x001000000003e003
- (id)initWithHandoffContext:(id)arg1 backingCallSource:(id)arg2;	// IMP=0x001000000003dee8
- (id)initOutgoingWithJoinConversationRequest:(id)arg1;	// IMP=0x001000000003dca1
- (id)initOutgoingWithRequestedStartCallAction:(id)arg1 backingCallSource:(id)arg2;	// IMP=0x001000000003db48
- (id)initOutgoingWithDialRequest:(id)arg1;	// IMP=0x001000000003da2f
- (id)initOutgoingWithUniqueProxyIdentifier:(id)arg1 backingCallSourceIdentifier:(id)arg2 callUpdate:(id)arg3 isVideo:(_Bool)arg4 endpointOnCurrentDevice:(_Bool)arg5;	// IMP=0x001000000003d732
- (id)initIncomingWithBackingCallSource:(id)arg1 UUID:(id)arg2 update:(id)arg3;	// IMP=0x001000000003d294
- (id)initWithUniqueProxyIdentifier:(id)arg1 endpointOnCurrentDevice:(_Bool)arg2;	// IMP=0x001000000003d221
- (id)initWithUniqueProxyIdentifier:(id)arg1 endpointOnCurrentDevice:(_Bool)arg2 featureFlags:(id)arg3;	// IMP=0x001000000003d0d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

