//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface _TtC19appstorecomponentsd11JSLocObject : NSObject
{
    MISSING_TYPE *localizer;	// 0 = 0x0
    MISSING_TYPE *locale;	// 0 = 0x0
    MISSING_TYPE *localeWithCalendar;	// 0 = 0x0
    MISSING_TYPE *localeWithCalendarWithBagFixUp;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x004000000008e3d0
- (id)init;	// IMP=0x001000000008e370
- (id)relativeDate:(id)arg1;	// IMP=0x001000000008e240
- (id)formatDateInSentence:(id)arg1:(id)arg2:(id)arg3;	// IMP=0x001000000008da40
- (id)formatDate:(id)arg1:(id)arg2;	// IMP=0x001000000008d650
- (id)timeAgo:(id)arg1;	// IMP=0x001000000008d630
- (id)formattedCount:(id)arg1;	// IMP=0x001000000008ce70
- (id)fileSize:(id)arg1;	// IMP=0x001000000008ccc0
- (id)decimal:(id)arg1:(long long)arg2;	// IMP=0x001000000008cc30
- (id)stringWithCounts:(id)arg1:(id)arg2;	// IMP=0x001000000008c990
- (id)stringWithCount:(id)arg1:(long long)arg2;	// IMP=0x001000000008c700
- (id)string:(id)arg1;	// IMP=0x001000000008c650
@property(nonatomic, readonly) NSString *arcadeWordmarkAssetName;
@property(nonatomic, readonly) NSString *identifier;

@end

