//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface SRCompactDeviceMotionEffectView : UIView
{
    UIImageView *_effectImageView;	// 8 = 0x8
    _Bool _shouldUpdateOffsetRadians;	// 16 = 0x10
    _Bool _forcefullyUpdateImageViewFrame;	// 17 = 0x11
    double _initialOffsetRadians;	// 24 = 0x18
    long long _cachedInterfaceOrientation;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000708bc
- (long long)_currentInterfaceOrientation;	// IMP=0x001000000007086f
- (id)_currentWindowScene;	// IMP=0x00100000000706dc
- (void)_cleanUpIfNeeded;	// IMP=0x00100000000706d6
- (void)_configureDeviceMotionIfNeeded;	// IMP=0x00100000000704ae
- (void)viewWillBeUpdated;	// IMP=0x001000000007049d
- (void)_updateViewsforTraitCollection:(id)arg1;	// IMP=0x00100000000702ec
- (_Bool)_supportsDeviceMotion;	// IMP=0x00100000000702d2
- (void)layoutSubviews;	// IMP=0x001000000006feaa
- (void)invalidate;	// IMP=0x001000000006fe98
- (void)updateMaskingForView:(id)arg1;	// IMP=0x001000000006fc8d
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x001000000006fbb3
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000006fadc

@end

