//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SiriUI/SiriUISnippetCollectionViewController.h>

@class NSString, SAGuidanceGuideDomainSnippet;

@interface SRGuideDomainViewController : SiriUISnippetCollectionViewController
{
}

- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x002000000003537b
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;	// IMP=0x0010000000035373
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;	// IMP=0x001000000003536b
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0010000000035176
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0010000000035102
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x00100000000350f0
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0010000000035046
- (void)setSnippet:(id)arg1;	// IMP=0x0010000000034fc8
- (id)_phraseForIndexPath:(id)arg1;	// IMP=0x0010000000034efc
- (_Bool)_showsCategoriesForSection:(unsigned long long)arg1;	// IMP=0x0010000000034eb4
- (id)_titleForSection:(unsigned long long)arg1;	// IMP=0x0010000000034e0d
- (_Bool)usePlatterStyle;	// IMP=0x0010000000034e05
- (_Bool)wantsToManageBackgroundColor;	// IMP=0x0010000000034dfd
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x0010000000034aba
- (id)_utterancesForSection:(unsigned long long)arg1;	// IMP=0x0010000000034a13
- (long long)_numberOfSections;	// IMP=0x00100000000349a5
- (struct UIEdgeInsets)_headerViewEdgeInsets;	// IMP=0x0010000000034966
- (long long)_cellTypeForIndexPath:(id)arg1;	// IMP=0x0010000000034855
- (double)desiredHeightForHeaderView;	// IMP=0x001000000003475e
- (void)configureReusableHeaderView:(id)arg1;	// IMP=0x0010000000034696
- (Class)headerViewClass;	// IMP=0x0010000000034685
- (void)loadView;	// IMP=0x00100000000344f6
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000034493

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SAGuidanceGuideDomainSnippet *snippet; // @dynamic snippet;
@property(readonly) Class superclass;

@end

