//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SiriUI/SiriUIContentCollectionViewCell.h>

@class NSString, SiriUITextContainerView;

@interface SRGuideDetailPhraseViewCell : SiriUIContentCollectionViewCell
{
    SiriUITextContainerView *_textContainerView;	// 8 = 0x8
}

+ (id)_font;	// IMP=0x004000000007a237
+ (struct CGSize)sizeThatFits:(struct CGSize)arg1 text:(id)arg2;	// IMP=0x0010000000079e69
- (void).cxx_destruct;	// IMP=0x002000000007a25a
@property(copy, nonatomic) NSString *text;
- (void)prepareForReuse;	// IMP=0x001000000007a1b2
- (void)layoutSubviews;	// IMP=0x001000000007a108
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000079f4d

@end

