//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSHashTable, NSString, NSUUID;
@protocol OS_dispatch_queue;

@interface PCSDevice : NSObject
{
    _Bool _isActivePairedDevice;	// 8 = 0x8
    _Bool _isConnected;	// 9 = 0x9
    _Bool _isTombstone;	// 10 = 0xa
    _Bool _syncingIsRestricted;	// 11 = 0xb
    MISSING_TYPE *_idsDeviceIdentifier;	// 16 = 0x10
    NSString *_watchSize;	// 24 = 0x18
    NSString *_buildVersion;	// 32 = 0x20
    NSString *_osVersion;	// 40 = 0x28
    NSString *_serialNumber;	// 48 = 0x30
    NSString *_UUID;	// 56 = 0x38
    NSHashTable *_observers;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_internalQueue;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0020000000003aa1
@property(readonly) NSObject<OS_dispatch_queue> *internalQueue; // @synthesize internalQueue=_internalQueue;
@property(readonly) NSHashTable *observers; // @synthesize observers=_observers;
@property _Bool syncingIsRestricted; // @synthesize syncingIsRestricted=_syncingIsRestricted;
@property(readonly) NSString *UUID; // @synthesize UUID=_UUID;
@property(readonly) NSString *serialNumber; // @synthesize serialNumber=_serialNumber;
@property(readonly) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(readonly) NSString *buildVersion; // @synthesize buildVersion=_buildVersion;
@property(readonly) NSString *watchSize; // @synthesize watchSize=_watchSize;
@property _Bool isTombstone; // @synthesize isTombstone=_isTombstone;
@property _Bool isConnected; // @synthesize isConnected=_isConnected;
@property _Bool isActivePairedDevice; // @synthesize isActivePairedDevice=_isActivePairedDevice;
@property(readonly) NSString *idsDeviceIdentifier; // @synthesize idsDeviceIdentifier=_idsDeviceIdentifier;
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000038fb
- (unsigned long long)hash;	// IMP=0x00100000000038b7
@property(readonly) NSString *model;
@property(readonly) _Bool isReachable;
- (_Bool)_onQueue_isReachable;	// IMP=0x0010000000003730
@property(readonly) _Bool supportsNewProtocol;
@property(readonly) _Bool supportsPCSKeySync;
@property(readonly) NSUUID *pairingID;
- (void)removeObserver:(id)arg1;	// IMP=0x0010000000003615
- (void)addObserver:(id)arg1;	// IMP=0x0010000000003512
- (id)init;	// IMP=0x001000000000348b

@end

