//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIButton.h>

@class _UIFloatingContentView;

@interface TVSBVideoBulletinChinButton : UIButton
{
    _UIFloatingContentView *_floatingContentView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000001c660
@property(readonly, nonatomic) _UIFloatingContentView *floatingContentView; // @synthesize floatingContentView=_floatingContentView;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000001c560
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000001c480
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000001c3a0
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000001c2c0
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x001000000001c1e0
- (id)init;	// IMP=0x001000000001bba0

@end

