//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TVSBMultiCamBulletinViewController
{
}

- (void)didBeginAnimatingInBulletinView:(id)arg1;	// IMP=0x0040000000025910
- (void)_configureView:(id)arg1 forBulletin:(id)arg2;	// IMP=0x00100000000246e0
- (void)updateBulletinView:(id)arg1 forBulletin:(id)arg2;	// IMP=0x0010000000024640
- (id)bulletinViewForBulletin:(id)arg1;	// IMP=0x00100000000245a0
- (void)willEnterPIP:(id)arg1;	// IMP=0x0010000000024480
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00100000000243e0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0010000000024340
- (void)handleMenuButtonWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000242a0
- (void)bulletinServiceEndUserInteractionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000024030

@end

