//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <QuartzCore/CADisplayMode.h>

@interface CADisplayMode (PineBoard)
- (void)pb_saveAsPreferred;	// IMP=0x00100000002bf980
- (id)description;	// IMP=0x00100000002bf7b0
- (long long)pb_aspectRatio;	// IMP=0x00100000002bf760
@end

