//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PineBoardServices/PBSAppInfoConfiguration.h>

@class NSDictionary, NSString;

@interface PBAppInfoConfiguration : PBSAppInfoConfiguration
{
    NSDictionary *_singleAppModeOptions;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000227110
- (void).cxx_destruct;	// IMP=0x00200000002271a0
@property(readonly, copy, nonatomic) NSDictionary *singleAppModeOptions; // @synthesize singleAppModeOptions=_singleAppModeOptions;
- (_Bool)isPBAppInfoConfiguration;	// IMP=0x0010000000227160
- (Class)classForCoder;	// IMP=0x0010000000227130
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000002270c0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000227090
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000226d30
- (id)initWithConfiguration:(id)arg1;	// IMP=0x0010000000226c00

// Remaining properties
@property(readonly) Class superclass;

@end

