//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, NSMutableArray, NSMutableOrderedSet, NSString, PBOpenAppTransition, TVSConcurrentTransactionManager, TVSSerialTransactionManager;

@interface PBDefaultOpenAppTransitioner : NSObject
{
    TVSSerialTransactionManager *_foregroundOpenAppTransactionManager;	// 8 = 0x8
    TVSConcurrentTransactionManager *_backgroundOpenAppTransactionManager;	// 16 = 0x10
    NSHashTable *_openAppObservers;	// 24 = 0x18
    NSMutableArray *_coldBootQueuedTransitions;	// 32 = 0x20
    NSMutableOrderedSet *_deepLinkingAppHistory;	// 40 = 0x28
    PBOpenAppTransition *_activeTransition;	// 48 = 0x30
}

+ (id)sharedInstance;	// IMP=0x0020000000095a70
+ (id)dependencyDescription;	// IMP=0x00100000000959c0
- (void).cxx_destruct;	// IMP=0x0020000000098bb0
@property(retain, nonatomic) PBOpenAppTransition *activeTransition; // @synthesize activeTransition=_activeTransition;
@property(readonly, nonatomic) NSMutableOrderedSet *deepLinkingAppHistory; // @synthesize deepLinkingAppHistory=_deepLinkingAppHistory;
@property(readonly, nonatomic) NSMutableArray *coldBootQueuedTransitions; // @synthesize coldBootQueuedTransitions=_coldBootQueuedTransitions;
@property(readonly, nonatomic) NSHashTable *openAppObservers; // @synthesize openAppObservers=_openAppObservers;
@property(readonly, nonatomic) TVSConcurrentTransactionManager *backgroundOpenAppTransactionManager; // @synthesize backgroundOpenAppTransactionManager=_backgroundOpenAppTransactionManager;
@property(readonly, nonatomic) TVSSerialTransactionManager *foregroundOpenAppTransactionManager; // @synthesize foregroundOpenAppTransactionManager=_foregroundOpenAppTransactionManager;
- (void)transactionManager:(id)arg1 didInterruptTransaction:(id)arg2 forTransaction:(id)arg3;	// IMP=0x0010000000098820
- (void)transactionManager:(id)arg1 willInterruptTransaction:(id)arg2 forTransaction:(id)arg3;	// IMP=0x0010000000098670
- (void)transactionManager:(id)arg1 didCompleteTransaction:(id)arg2;	// IMP=0x0010000000098010
- (void)transactionManager:(id)arg1 willBeginTransaction:(id)arg2;	// IMP=0x0010000000097d30
- (void)openAppTransition:(id)arg1 willReportSystemCompletionWithError:(id)arg2;	// IMP=0x0010000000097c60
- (void)openAppTransitionWillStartAnimation:(id)arg1;	// IMP=0x0010000000097a20
- (void)openAppTransition:(id)arg1 willLaunchProcess:(id)arg2;	// IMP=0x00100000000977b0
- (void)_handleDeepLinkingForTransaction:(id)arg1;	// IMP=0x0010000000097120
- (void)_deactivateSceneHandle:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000096b90
- (void)_deactivateFocusedAppWithOptions:(id)arg1;	// IMP=0x00100000000967f0
- (void)_addOpenAppTransitionIfPossible:(id)arg1;	// IMP=0x00100000000960a0
- (void)removeObserver:(id)arg1;	// IMP=0x0010000000096030
- (void)addObserver:(id)arg1;	// IMP=0x0010000000095fc0
- (void)handleFocusedAppRequestDeactivationFromFailure:(_Bool)arg1;	// IMP=0x0010000000095ec0
- (void)addOpenAppTransition:(id)arg1;	// IMP=0x0010000000095e60
@property(readonly, nonatomic, getter=isTransitioning) _Bool transitioning;
- (id)init;	// IMP=0x0010000000095b60

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

