//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, NSString;
@protocol OS_dispatch_queue;

@interface PBEARCConfigurator : NSObject
{
    NSObject<OS_dispatch_queue> *_observerQueue;	// 8 = 0x8
    NSHashTable *_observers;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00200000001441d0
- (void).cxx_destruct;	// IMP=0x0020000000144560
@property(readonly, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *observerQueue; // @synthesize observerQueue=_observerQueue;
- (void)removeEARCObserver:(id)arg1;	// IMP=0x00100000001444e0
- (void)addEARCObserver:(id)arg1;	// IMP=0x00100000001444a0
- (void)toggleEARC:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000144370
- (void)enableEARC:(_Bool)arg1;	// IMP=0x0010000000144350
@property(readonly, nonatomic) long long eARCStatus;
- (id)_init;	// IMP=0x00100000001442a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

