//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSLayoutConstraint, PBPIPContainerViewController, PGPictureInPictureApplication, UILayoutGuide;
@protocol OS_dispatch_source;

@interface PBPIPContainerViewControllerLayout : NSObject
{
    _Bool _isKeyboardFocused;	// 8 = 0x8
    int _keyboardFocusedNotifyToken;	// 12 = 0xc
    PBPIPContainerViewController *_containerViewController;	// 16 = 0x10
    long long _state;	// 24 = 0x18
    NSArray *_constraintsFillingParentView;	// 32 = 0x20
    NSArray *_constraintsFittingParentView;	// 40 = 0x28
    NSLayoutConstraint *_heightConstraint;	// 48 = 0x30
    NSLayoutConstraint *_widthConstraint;	// 56 = 0x38
    NSLayoutConstraint *_topConstraint;	// 64 = 0x40
    NSLayoutConstraint *_bottomConstraint;	// 72 = 0x48
    NSLayoutConstraint *_leftConstraint;	// 80 = 0x50
    NSLayoutConstraint *_rightConstraint;	// 88 = 0x58
    UILayoutGuide *_preferredPositionLayoutGuide;	// 96 = 0x60
    NSLayoutConstraint *_preferredHeightConstraint;	// 104 = 0x68
    NSLayoutConstraint *_preferredWidthConstraint;	// 112 = 0x70
    NSLayoutConstraint *_preferredTopConstraint;	// 120 = 0x78
    NSLayoutConstraint *_preferredBottomConstraint;	// 128 = 0x80
    NSLayoutConstraint *_preferredLeftConstraint;	// 136 = 0x88
    NSLayoutConstraint *_preferredRightConstraint;	// 144 = 0x90
    long long _quadrant;	// 152 = 0x98
    NSObject<OS_dispatch_source> *_focusDodgingTimer;	// 160 = 0xa0
    struct CGRect _lastFocusedFrame;	// 168 = 0xa8
}

- (void).cxx_destruct;	// IMP=0x0020000000298f70
@property(readonly, nonatomic) int keyboardFocusedNotifyToken; // @synthesize keyboardFocusedNotifyToken=_keyboardFocusedNotifyToken;
@property(nonatomic) _Bool isKeyboardFocused; // @synthesize isKeyboardFocused=_isKeyboardFocused;
@property(readonly, nonatomic) struct CGRect lastFocusedFrame; // @synthesize lastFocusedFrame=_lastFocusedFrame;
@property(readonly, nonatomic) NSObject<OS_dispatch_source> *focusDodgingTimer; // @synthesize focusDodgingTimer=_focusDodgingTimer;
@property(readonly, nonatomic) long long quadrant; // @synthesize quadrant=_quadrant;
@property(readonly, nonatomic) NSLayoutConstraint *preferredRightConstraint; // @synthesize preferredRightConstraint=_preferredRightConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *preferredLeftConstraint; // @synthesize preferredLeftConstraint=_preferredLeftConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *preferredBottomConstraint; // @synthesize preferredBottomConstraint=_preferredBottomConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *preferredTopConstraint; // @synthesize preferredTopConstraint=_preferredTopConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *preferredWidthConstraint; // @synthesize preferredWidthConstraint=_preferredWidthConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *preferredHeightConstraint; // @synthesize preferredHeightConstraint=_preferredHeightConstraint;
@property(readonly, nonatomic) UILayoutGuide *preferredPositionLayoutGuide; // @synthesize preferredPositionLayoutGuide=_preferredPositionLayoutGuide;
@property(readonly, nonatomic) NSLayoutConstraint *rightConstraint; // @synthesize rightConstraint=_rightConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *leftConstraint; // @synthesize leftConstraint=_leftConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *bottomConstraint; // @synthesize bottomConstraint=_bottomConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *widthConstraint; // @synthesize widthConstraint=_widthConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(readonly, nonatomic) NSArray *constraintsFittingParentView; // @synthesize constraintsFittingParentView=_constraintsFittingParentView;
@property(readonly, nonatomic) NSArray *constraintsFillingParentView; // @synthesize constraintsFillingParentView=_constraintsFillingParentView;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(readonly, nonatomic) PBPIPContainerViewController *containerViewController; // @synthesize containerViewController=_containerViewController;
- (void)_handleKeyboardNotification;	// IMP=0x0010000000298bd0
- (void)_unregisterFromKeyboardNotifications;	// IMP=0x0010000000298b80
- (void)_registerForKeyboardNotifications;	// IMP=0x0010000000298a40
- (id)_allConstraints;	// IMP=0x0010000000298880
- (id)_pipLayoutGuide;	// IMP=0x0010000000298670
- (id)_parentView;	// IMP=0x00100000002985c0
- (void)updateConstraintsForPreferredPictureInPictureSize;	// IMP=0x0010000000298520
- (_Bool)_shouldDodgeFocusedFrame:(struct CGRect)arg1;	// IMP=0x00100000002981a0
- (void)_updateConstraintsForFocusedFrame:(struct CGRect)arg1 shouldDodge:(_Bool)arg2;	// IMP=0x00100000002978e0
- (void)_cancelUpdateForDodgingFocusedFrame;	// IMP=0x0010000000297890
- (void)_stageUpdateForDodgingFocusedFrame;	// IMP=0x0010000000297630
- (void)updateConstraintsForFocusedFrame:(struct CGRect)arg1;	// IMP=0x0010000000297530
- (void)updateConstraintsFittingParentView;	// IMP=0x00100000002974a0
- (void)updateConstraintsFillingParentView;	// IMP=0x0010000000297410
- (void)updateConstraintsForPictureInPictureQuadrant:(long long)arg1;	// IMP=0x0010000000296ff0
- (struct CGRect)preferredPictureInPictureFrameForQuadrant:(long long)arg1 pipInsets:(struct UIEdgeInsets)arg2;	// IMP=0x0010000000296ba0
- (struct CGSize)preferredLandscapeBoundingSize;	// IMP=0x0010000000296b10
- (struct CGRect)preferredIntrinsicFrame;	// IMP=0x0010000000296a00
- (struct CGSize)preferredIntrinsicSize;	// IMP=0x00100000002969c0
- (struct CGSize)preferredFullscreenSize;	// IMP=0x0010000000296920
- (struct CGSize)preferredPictureInPictureInstrisicContentSize;	// IMP=0x00100000002968d0
- (struct CGSize)_preferredPictureInPictureSizeAllowingPortrait:(_Bool)arg1;	// IMP=0x0010000000296710
- (struct CGSize)preferredPictureInPictureSize;	// IMP=0x00100000002966d0
- (double)contentAspectRatio;	// IMP=0x0010000000296660
@property(readonly, nonatomic) PGPictureInPictureApplication *application;
- (void)_setUpConstraints;	// IMP=0x00100000002959d0
- (void)dealloc;	// IMP=0x0010000000295980
- (id)initWithContainerViewController:(id)arg1;	// IMP=0x0010000000295860

@end

