//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface PBSAnimationWatchdogProvider : NSObject
{
    double _timeout;	// 8 = 0x8
}

@property(readonly, nonatomic) double timeout; // @synthesize timeout=_timeout;
- (_Bool)shouldWatchdog:(id *)arg1;	// IMP=0x00100000000ba6a0
- (double)watchdogTimeout;	// IMP=0x00100000000ba620
- (id)initWithTimeout:(double)arg1;	// IMP=0x00100000000ba580

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

