//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ACAccountStore, CUHomeKitManager, NSCountedSet, NSDate, NSHashTable, NSMutableDictionary, NSMutableSet, NSString, NSTimer, PBAccountNotificationCoalescingQueue, PBBulletinPausedAssertion, PBBulletinService, PBSBulletin, PBSGroupRecommendationsSession, PBSUserProfilesSnapshot, PBUserProfileStore, _TtC9PineBoard25PBUserProfilePictureStore;
@protocol BSInvalidatable, OS_dispatch_queue;

@interface PBUserProfileManager : NSObject
{
    _Bool _performingCreateUserProfilesMigration;	// 8 = 0x8
    _Bool _shouldPresentAutomaticWelcomeBackBulletin;	// 9 = 0x9
    PBSGroupRecommendationsSession *_groupRecommendationsSession;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_workQueue;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_observerQueue;	// 32 = 0x20
    ACAccountStore *_accountStore;	// 40 = 0x28
    NSHashTable *_observers;	// 48 = 0x30
    NSMutableDictionary *_userProfileManagerDidUpdateObservers;	// 56 = 0x38
    NSMutableDictionary *_userProfileManagerDidUpdateGroupSessionsObservers;	// 64 = 0x40
    PBUserProfileStore *_userProfileStore;	// 72 = 0x48
    NSTimer *_automaticWelcomeBackBulletinDelayTimer;	// 80 = 0x50
    PBSBulletin *_currentWelcomeBackBulletin;	// 88 = 0x58
    _TtC9PineBoard25PBUserProfilePictureStore *_userProfilePictureStore;	// 96 = 0x60
    NSCountedSet *_ignoringUserProfileAccountNotificationsReasons;	// 104 = 0x68
    PBAccountNotificationCoalescingQueue *_pendingUserProfileAccountNotifications;	// 112 = 0x70
    NSObject<OS_dispatch_queue> *_homeKitQueue;	// 120 = 0x78
    CUHomeKitManager *_homeKitManager;	// 128 = 0x80
    NSMutableSet *_provisioningUserProfileAttributes;	// 136 = 0x88
    PBBulletinService *_bulletinService;	// 144 = 0x90
    PBBulletinPausedAssertion *_pauseBulletinsAssertion;	// 152 = 0x98
    NSDate *_dateLastSystemWake;	// 160 = 0xa0
    id <BSInvalidatable> _stateCaptureHandle;	// 168 = 0xa8
}

+ (void)_removePersonaWithPersonaUniqueString:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x002000000016cc30
+ (void)_createGuestPersonaWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000016c370
+ (void)_setDidShowWelcomeBackBulletinForUserProfile:(id)arg1;	// IMP=0x0010000000162370
+ (_Bool)_didShowWelcomeBackBulletinForUserProfile:(id)arg1;	// IMP=0x0010000000162220
+ (void)_performCreateUserProfilesMigrationWithContext:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000015da30
+ (id)sharedInstance;	// IMP=0x0010000000152d60
+ (id)dependencyDescription;	// IMP=0x0010000000151b50
- (void).cxx_destruct;	// IMP=0x00200000001737a0
@property(retain, nonatomic) id <BSInvalidatable> stateCaptureHandle; // @synthesize stateCaptureHandle=_stateCaptureHandle;
@property(readonly, nonatomic) NSDate *dateLastSystemWake; // @synthesize dateLastSystemWake=_dateLastSystemWake;
@property(readonly, nonatomic) PBBulletinPausedAssertion *pauseBulletinsAssertion; // @synthesize pauseBulletinsAssertion=_pauseBulletinsAssertion;
@property(readonly, nonatomic) PBBulletinService *bulletinService; // @synthesize bulletinService=_bulletinService;
@property(readonly, nonatomic) NSMutableSet *provisioningUserProfileAttributes; // @synthesize provisioningUserProfileAttributes=_provisioningUserProfileAttributes;
@property(readonly, nonatomic) CUHomeKitManager *homeKitManager; // @synthesize homeKitManager=_homeKitManager;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *homeKitQueue; // @synthesize homeKitQueue=_homeKitQueue;
@property(readonly, nonatomic) PBAccountNotificationCoalescingQueue *pendingUserProfileAccountNotifications; // @synthesize pendingUserProfileAccountNotifications=_pendingUserProfileAccountNotifications;
@property(readonly, nonatomic) NSCountedSet *ignoringUserProfileAccountNotificationsReasons; // @synthesize ignoringUserProfileAccountNotificationsReasons=_ignoringUserProfileAccountNotificationsReasons;
@property(readonly, nonatomic) _TtC9PineBoard25PBUserProfilePictureStore *userProfilePictureStore; // @synthesize userProfilePictureStore=_userProfilePictureStore;
@property(readonly, nonatomic) PBSBulletin *currentWelcomeBackBulletin; // @synthesize currentWelcomeBackBulletin=_currentWelcomeBackBulletin;
@property(readonly, nonatomic) NSTimer *automaticWelcomeBackBulletinDelayTimer; // @synthesize automaticWelcomeBackBulletinDelayTimer=_automaticWelcomeBackBulletinDelayTimer;
@property(readonly, nonatomic) _Bool shouldPresentAutomaticWelcomeBackBulletin; // @synthesize shouldPresentAutomaticWelcomeBackBulletin=_shouldPresentAutomaticWelcomeBackBulletin;
@property(readonly, nonatomic) _Bool performingCreateUserProfilesMigration; // @synthesize performingCreateUserProfilesMigration=_performingCreateUserProfilesMigration;
@property(readonly, nonatomic) PBUserProfileStore *userProfileStore; // @synthesize userProfileStore=_userProfileStore;
@property(readonly, nonatomic) NSMutableDictionary *userProfileManagerDidUpdateGroupSessionsObservers; // @synthesize userProfileManagerDidUpdateGroupSessionsObservers=_userProfileManagerDidUpdateGroupSessionsObservers;
@property(readonly, nonatomic) NSMutableDictionary *userProfileManagerDidUpdateObservers; // @synthesize userProfileManagerDidUpdateObservers=_userProfileManagerDidUpdateObservers;
@property(readonly, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) ACAccountStore *accountStore; // @synthesize accountStore=_accountStore;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *observerQueue; // @synthesize observerQueue=_observerQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
- (void)userProfileStore:(id)arg1 didUpdateiTunesForSelectedUserProfile:(id)arg2;	// IMP=0x0010000000173450
- (void)userProfileStore:(id)arg1 didChangeSelectedUserProfile:(id)arg2 previousSelectedUserProfile:(id)arg3;	// IMP=0x0010000000173300
- (void)bulletinService:(id)arg1 didDismissBulletin:(id)arg2 withReason:(unsigned long long)arg3;	// IMP=0x0010000000173130
- (void)presentationElementFocusCoordinator:(id)arg1 didUpdateToActiveLayoutLevel:(long long)arg2 fromLevel:(long long)arg3;	// IMP=0x0010000000172980
- (void)powerManagerDidWakeSystem:(id)arg1 reason:(long long)arg2;	// IMP=0x00100000001728f0
- (void)powerManager:(id)arg1 willWakeSystemWithReason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001727a0
- (void)powerManagerDidSleepSystem:(id)arg1 reason:(long long)arg2;	// IMP=0x0010000000172740
- (id)_validClientProcessWithEntitlement:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000172250
- (void)_workQueue_resetGroupRecommendationsSession;	// IMP=0x0010000000171d30
- (id)_allUsersStateDumpForCustomerLogs;	// IMP=0x0000000000170fa0
- (void)_removeAllIgnoringUserProfileAccountNotificationsWithReason:(id)arg1;	// IMP=0x0010000000170e30
- (void)_workQueue_validateAndFixActiveiTunesAccount;	// IMP=0x0010000000170a80
- (id)_homeKitQueue_selfAccessoryHome;	// IMP=0x0010000000170a00
- (void)_workQueue_initializeUserProfileStorage;	// IMP=0x0010000000170870
- (void)_activateItunesAccountWithUserProfile:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000016fad0
- (void)_workQueue_notifyObserversDidUpdateGroupRecommendationsSession;	// IMP=0x001000000016f4c0
- (void)_workQueue_notifyObserversDidUpdate;	// IMP=0x001000000016eef0
- (void)_workQueue_saveStoreAndNotify;	// IMP=0x001000000016ee00
- (void)_removeGameCenterAccountWithAltDSID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000016e170
- (void)_removeIcloudAccountWithAltDSID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000016d660
- (void)_workQueue_createGuestUserProfileForItunesAccountNotificationWithItunesAltDSID:(id)arg1 homeUserIdentifier:(id)arg2;	// IMP=0x001000000016b6d0
- (void)_workQueue_endIgnoringUserProfileAccountNotificationsWithReason:(id)arg1;	// IMP=0x001000000016b570
- (void)_workQueue_processPendingAccountNotifications;	// IMP=0x001000000016b070
- (void)_batchUpdater_handleDidUpdateItunesAccountNotificationWithBatchUpdater:(id)arg1 itunesAltDSID:(id)arg2 existingUserProfiles:(id)arg3 existingHomeManagedUserProfiles:(id)arg4 addedHomeUserIdentifiers:(id)arg5 removedHomeUserIdentifiers:(id)arg6;	// IMP=0x0010000000167cf0
- (void)_workQueue_handleDidUpdateItunesAccountNotificationWithItunesAltDSID:(id)arg1 existingUserProfiles:(id)arg2 existingHomeManagedUserProfiles:(id)arg3 addedHomeUserIdentifiers:(id)arg4 removedHomeUserIdentifiers:(id)arg5;	// IMP=0x00100000001679d0
- (void)_batchUpdater_didRemoveItunesAccountWithAltDSID:(id)arg1 batchUpdater:(id)arg2;	// IMP=0x0010000000166770
- (void)_workQueue_didRemoveItunesAccountWithAltDSID:(id)arg1;	// IMP=0x0010000000166000
- (void)_workQueue_didUpdateItunesAccountWithIdentifier:(id)arg1;	// IMP=0x0010000000165480
- (void)_workQueue_didAddItunesAccountWithIdentifier:(id)arg1;	// IMP=0x0010000000164370
- (void)_workQueue_didRemoveGameCenterAccountWithAltDSID:(id)arg1;	// IMP=0x0010000000163a50
- (void)_workQueue_didRemoveIcloudAccountWithAltDSID:(id)arg1;	// IMP=0x0010000000163130
- (void)_workQueue_handleUserProfileAccountNotification:(id)arg1;	// IMP=0x0010000000162bb0
- (void)_handleUserProfileAccountNotification:(id)arg1;	// IMP=0x0010000000162650
- (void)_releasePausedBulletinsAssertion;	// IMP=0x0010000000162600
- (void)_workQueue_releasePausedBulletinsAssertion;	// IMP=0x0010000000162530
- (id)_welcomeBulletinProfilePictureDataForUserProfile:(id)arg1;	// IMP=0x0010000000161c10
- (void)_workQueue_presentWelcomeBackBulletinWithReason:(long long)arg1;	// IMP=0x0010000000160fd0
- (void)_workQueue_performCreateUserProfilesMigration;	// IMP=0x0010000000160140
- (void)_workQueue_updateGroupRecommendationsSessionWithUserIdentifiers:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000015cd60
- (void)_workQueue_updateGroupRecommendationsConsent:(long long)arg1 forUserProfileWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000015be70
- (void)_workQueue_effectiveUserProfileWithHomeUserIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000015b830
- (void)_workQueue_removeUserProfileWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000015ae60
- (void)_workQueue_updateUserProfileWithIdentifier:(id)arg1 attributes:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000015a100
- (void)_workQueue_createUserProfileWithAttributes:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000001595d0
- (void)_workQueue_selectUserProfileWithIdentifier:(id)arg1 clientBundleIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000158980
- (oneway void)handleUserProfileAccountNotification:(id)arg1;	// IMP=0x00100000001587f0
- (void)endIgnoringUserProfileAccountNotifications;	// IMP=0x0010000000158660
- (void)beginIgnoringUserProfileAccountNotifications;	// IMP=0x00100000001584d0
- (oneway void)updateGroupRecommendationsSessionWithUserIdentifiers:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000157f10
- (oneway void)updateGroupRecommendationsConsent:(id)arg1 forUserProfileWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000157870
- (oneway void)effectiveUserProfileWithHomeUserIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000001572c0
- (oneway void)removeUserProfileWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000156d10
- (oneway void)updateUserProfileWithIdentifier:(id)arg1 attributes:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000001566d0
- (oneway void)createUserProfileWithAttributes:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000156120
- (oneway void)selectUserProfileWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000155ac0
- (oneway void)fetchGroupRecommendationsSessionWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000001556d0
@property(readonly, nonatomic) PBSGroupRecommendationsSession *groupRecommendationsSession; // @synthesize groupRecommendationsSession=_groupRecommendationsSession;
- (oneway void)fetchUserProfilesSnapshotWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000154fa0
@property(readonly, nonatomic) PBSUserProfilesSnapshot *userProfilesSnapshot;
- (void)sendDailyAnalyticsEvents;	// IMP=0x0010000000153f80
- (void)endIgnoringUserProfileAccountNotificationsWithReason:(id)arg1;	// IMP=0x0010000000153e50
- (void)beginIgnoringUserProfileAccountNotificationsWithReason:(id)arg1;	// IMP=0x0010000000153c30
- (void)removeObserver:(id)arg1;	// IMP=0x0010000000153aa0
- (id)observeUserProfileManagerDidUpdateGroupRecommendationsSessionUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000153670
- (id)observeUserProfileManagerDidUpdateUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000153240
- (void)addObserver:(id)arg1;	// IMP=0x0010000000153110
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x0010000000152ce0
- (id)_init;	// IMP=0x0010000000152bc0
- (id)_initWithAccountStore:(id)arg1 bulletinService:(id)arg2 userProfileStore:(id)arg3 homeKitManager:(id)arg4;	// IMP=0x0010000000151cf0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

