//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface MRDAVOutputContextManager : NSObject
{
    NSMutableDictionary *_activeOutputContexts;	// 8 = 0x8
    NSMutableDictionary *_reservedOutputContexts;	// 16 = 0x10
    NSMutableDictionary *_inactiveOutputContexts;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_serialQueue;	// 32 = 0x20
}

+ (id)sharedManager;	// IMP=0x004000000002a410
- (void).cxx_destruct;	// IMP=0x002000000002c939
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) NSMutableDictionary *inactiveOutputContexts; // @synthesize inactiveOutputContexts=_inactiveOutputContexts;
@property(retain, nonatomic) NSMutableDictionary *reservedOutputContexts; // @synthesize reservedOutputContexts=_reservedOutputContexts;
@property(retain, nonatomic) NSMutableDictionary *activeOutputContexts; // @synthesize activeOutputContexts=_activeOutputContexts;
- (void)processOutputContext:(id)arg1;	// IMP=0x001000000002c0bb
- (void)reloadOutputContexts;	// IMP=0x001000000002be91
- (void)disconnectOutputContextExternalDevices;	// IMP=0x001000000002bc60
- (void)_handleMediaServerDeath;	// IMP=0x001000000002bb4e
- (void)_notifyLocalDeviceDidChangeOutputContext;	// IMP=0x001000000002bb00
- (void)_handleOutputContextDidRemoveLocalDevice:(id)arg1;	// IMP=0x001000000002baee
- (void)_handleOutputContextDidAddLocalDevice:(id)arg1;	// IMP=0x001000000002badc
- (void)outputDevicesDidChangeNotification:(id)arg1;	// IMP=0x001000000002ba8d
- (void)registerCommunicationChannelForOutputContext:(id)arg1;	// IMP=0x001000000002b996
- (void)registerForOutputContextNotifications:(id)arg1;	// IMP=0x001000000002b87d
- (void)registerOutputContext:(id)arg1;	// IMP=0x001000000002b819
- (id)outputContextForOutputDeviceUIDs:(id)arg1 strict:(_Bool)arg2;	// IMP=0x001000000002acaf
- (id)outputContextForOutputDeviceUID:(id)arg1;	// IMP=0x001000000002abf1
- (id)outputContextForOutputDevices:(id)arg1 strict:(_Bool)arg2;	// IMP=0x001000000002ab6b
- (id)outputContextForOutputDevice:(id)arg1;	// IMP=0x001000000002ab09
- (void)registerCommunicationsChannels;	// IMP=0x001000000002a8ac
@property(readonly, nonatomic) NSArray *outputContexts;
- (id)debugDescription;	// IMP=0x001000000002a5a3
- (id)_init;	// IMP=0x001000000002a475

@end

