//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MediaRemote/MRDeviceInfo.h>

@interface MRDeviceInfo (MRDStreamCapacityManagerAdditions)
+ (id)_readDeviceInfo;	// IMP=0x00100000000452bf
+ (void)_writeDeviceInfo:(id)arg1 toPath:(id)arg2;	// IMP=0x0010000000045169
+ (id)_readLegacyDeviceInfoIdentifier;	// IMP=0x00100000000450c0
+ (id)_deviceInfoArchiveClasses;	// IMP=0x0010000000045005
+ (id)_deviceInfoFilePath;	// IMP=0x0010000000044fbf
+ (id)networkIdentifier;	// IMP=0x0010000000044f4b
+ (id)currentDeviceInfo;	// IMP=0x00100000000440ff
@property(readonly, nonatomic) _Bool containsLocalDevice;
@end

