//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, MROSTransaction, SBSLockScreenContentAssertion;

@interface MRDLockScreenAssertion : NSObject
{
    SBSLockScreenContentAssertion *_assertion;	// 8 = 0x8
    MROSTransaction *_transaction;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000587b4
@property(retain, nonatomic) MROSTransaction *transaction; // @synthesize transaction=_transaction;
@property(retain, nonatomic) SBSLockScreenContentAssertion *assertion; // @synthesize assertion=_assertion;
- (void)dealloc;	// IMP=0x001000000005874f
- (void)delayCreateAssertion;	// IMP=0x0010000000058678
- (void)createAssertion;	// IMP=0x0010000000058469
- (MISSING_TYPE *)init;	// IMP=0x0010000000058309

@end

