//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MRDOutputDeviceRoutingDataSource;

@interface MRDMediaServerAVRoutingDataSource
{
    MRDOutputDeviceRoutingDataSource *_oddsShimDataSource;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000567b5
- (id)_oddsShimDataSource;	// IMP=0x0010000000056774
- (void)_notifyDelegateRoutesDidChange;	// IMP=0x0010000000056717
- (id)_descriptionForDiscoveryMode:(unsigned int)arg1;	// IMP=0x00100000000566f5
- (void)_unregisterAVSystemControllerNotifications;	// IMP=0x00100000000565fa
- (void)_registerAVSystemControllerNotifications;	// IMP=0x001000000005610c
- (id)_mediaServerController;	// IMP=0x00100000000560f1
- (void)_avSessionMediaServicesResetNotification:(id)arg1;	// IMP=0x0010000000055fda
- (void)_portStatusDidChangeNotification:(id)arg1;	// IMP=0x0010000000055d1b
- (void)_externalScreenDidChangeNotification:(id)arg1;	// IMP=0x0010000000055cbe
- (void)_postCurrentRouteHasVolumeControlDidChangeNotification:(_Bool)arg1;	// IMP=0x0010000000055bbc
- (void)_currentRouteHasVolumeControlDidChangeNotification:(id)arg1;	// IMP=0x0010000000055b05
- (void)_pickableRoutesDidChangeNotification:(id)arg1;	// IMP=0x0010000000055af3
- (_Bool)unpickAirPlayRoutes;	// IMP=0x00100000000559f4
- (void)userCancelledPickingRoute:(id)arg1;	// IMP=0x001000000005594f
- (_Bool)resetPickedSystemRouteForSource:(unsigned int)arg1;	// IMP=0x001000000005593d
- (_Bool)resetPickedRouteForSource:(unsigned int)arg1;	// IMP=0x00100000000556e8
- (_Bool)setPickedSystemRoute:(id)arg1 withPassword:(id)arg2 forSource:(unsigned int)arg3;	// IMP=0x001000000005554a
- (_Bool)setPickedRoute:(id)arg1 withPassword:(id)arg2 forSource:(unsigned int)arg3;	// IMP=0x0010000000055538
- (_Bool)setPickedRoute:(id)arg1 withPassword:(id)arg2;	// IMP=0x0010000000055523
- (id)pickableRoutesForCategory:(id)arg1 source:(unsigned int)arg2;	// IMP=0x0010000000055145
- (id)pickableRoutesForCategory:(id)arg1;	// IMP=0x0010000000055131
- (id)pickedRoutesForCategory:(id)arg1 source:(unsigned int)arg2;	// IMP=0x0010000000054f84
- (id)pickedRouteForCategory:(id)arg1 source:(unsigned int)arg2;	// IMP=0x0010000000054f34
- (id)pickedRouteForCategory:(id)arg1;	// IMP=0x0010000000054f20
- (id)pickedRoutes;	// IMP=0x0010000000054f02
- (id)pickedRoute;	// IMP=0x0010000000054eb2
- (_Bool)currentRouteSupportsVolumeControl;	// IMP=0x0010000000054e6e
- (unsigned int)externalScreenType;	// IMP=0x0010000000054d6a
- (void)setDiscoveryMode:(unsigned int)arg1;	// IMP=0x0010000000054cf3
- (void)dealloc;	// IMP=0x0010000000054c7e
- (id)init;	// IMP=0x0010000000054bbb

@end

