//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSString.h>

@interface NSString (VOTStringExtras)
+ (id)stringWithUnichar:(unsigned short)arg1;	// IMP=0x0010000000028938
- (id)wordStringFromPosition:(long long)arg1 inDirection:(long long)arg2;	// IMP=0x0020000000028b1b
- (struct _NSRange)wordFromPosition:(long long)arg1 inDirection:(long long)arg2;	// IMP=0x0010000000028ab2
- (struct _NSRange)lineFromPosition:(long long)arg1 inDirection:(long long)arg2;	// IMP=0x0010000000028a49
- (struct _NSRange)paragraphFromPosition:(long long)arg1 inDirection:(long long)arg2;	// IMP=0x00100000000289e0
- (struct _NSRange)sentenceFromPosition:(long long)arg1 inDirection:(long long)arg2;	// IMP=0x0010000000028977
@end

