//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSLock, TTSVoiceAsset;

@interface VOTActiveSiriVoiceManager : NSObject
{
    NSLock *_cachedSiriVoiceLock;	// 8 = 0x8
    TTSVoiceAsset *_cachedSiriVoiceAsset;	// 16 = 0x10
    int _gryphonInstallNotifyToken;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x00400000000c328e
- (void).cxx_destruct;	// IMP=0x00200000000c39eb
- (id)siriVoiceIdentifierForLanguage:(id)arg1;	// IMP=0x00100000000c35f4
- (void)_handleSiriVoiceUpdate;	// IMP=0x00100000000c3551
- (void)_deregisterForNotifications;	// IMP=0x00100000000c3515
- (void)_registerForNotifications;	// IMP=0x00100000000c33c7
- (void)dealloc;	// IMP=0x00100000000c3389
- (id)_init;	// IMP=0x00100000000c3323

@end

