//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, VOTAppLauncher, VOTElement;
@protocol VOTGesturedTextInputManagerDelegate;

@interface VOTGesturedTextInputManager : NSObject
{
    _Bool _active;	// 8 = 0x8
    id <VOTGesturedTextInputManagerDelegate> _delegate;	// 16 = 0x10
    long long _rotorType;	// 24 = 0x18
    NSDictionary *_localizedWebRotorMap;	// 32 = 0x20
    VOTAppLauncher *_appLauncher;	// 40 = 0x28
    VOTElement *_appLauncherManitorElement;	// 48 = 0x30
    NSString *_currentInputString;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x002000000005ee65
@property(copy, nonatomic) NSString *currentInputString; // @synthesize currentInputString=_currentInputString;
@property(retain, nonatomic) VOTElement *appLauncherManitorElement; // @synthesize appLauncherManitorElement=_appLauncherManitorElement;
@property(retain, nonatomic) VOTAppLauncher *appLauncher; // @synthesize appLauncher=_appLauncher;
@property(retain, nonatomic) NSDictionary *localizedWebRotorMap; // @synthesize localizedWebRotorMap=_localizedWebRotorMap;
@property(nonatomic) long long rotorType; // @synthesize rotorType=_rotorType;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(nonatomic) __weak id <VOTGesturedTextInputManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)appLauncher:(id)arg1 didLaunchAppOrNil:(id)arg2;	// IMP=0x001000000005ec2d
- (void)appLauncher:(id)arg1 didFilterApps:(id)arg2 didSwitchAppFocus:(id)arg3 withPrefix:(id)arg4;	// IMP=0x001000000005e92e
- (unsigned long long)_numberOfCharactersToDeleteStartingAtIndex:(unsigned long long)arg1 toDesiredLength:(unsigned long long)arg2 fromString:(id)arg3;	// IMP=0x001000000005e81f
- (unsigned long long)_numberOfCharactersToDeleteToDesiredLength:(unsigned long long)arg1 fromString:(id)arg2;	// IMP=0x001000000005e7b4
- (void)_updateLocalizedResources;	// IMP=0x001000000005e4e2
- (_Bool)_processLaunchEvent:(id)arg1 forElement:(id)arg2;	// IMP=0x001000000005e1a7
- (_Bool)_processRawInputEvent:(id)arg1 forElement:(id)arg2 withAttributes:(id)arg3;	// IMP=0x001000000005def4
- (_Bool)_performWordBackspaceForElement:(id)arg1;	// IMP=0x001000000005dd88
- (void)_deleteFromCurrentInputStringIfNeeded;	// IMP=0x001000000005dc6e
- (_Bool)_processWebRotorEvent:(id)arg1;	// IMP=0x001000000005db83
- (void)eventFactoryDidBeginSplitGesture:(id)arg1;	// IMP=0x001000000005db7d
- (id)hintForAppLaunch;	// IMP=0x001000000005db75
- (_Bool)shouldAllowRotorEvents;	// IMP=0x001000000005db6d
- (void)didInputWordBackspace;	// IMP=0x001000000005db67
- (void)didInputBackspace;	// IMP=0x001000000005db61
- (_Bool)performNextBrailleTableCommand;	// IMP=0x001000000005db59
- (_Bool)performNextKeyboardLanguage;	// IMP=0x001000000005db51
- (_Bool)performCustomWordBackspace;	// IMP=0x001000000005db49
- (_Bool)performCustomBackspace;	// IMP=0x001000000005db41
- (void)applyPreviousSuggestionToElement:(id)arg1;	// IMP=0x000000000011fa52
- (void)applyNextSuggestionToElement:(id)arg1;	// IMP=0x001000000011fa27
- (_Bool)isNextBrailleTableEvent:(id)arg1;	// IMP=0x001000000011f9f9
- (_Bool)isNextKeyboardLanguageEvent:(id)arg1;	// IMP=0x001000000011f9cb
- (_Bool)isLaunchAppEvent:(id)arg1;	// IMP=0x001000000011f99d
- (_Bool)isPreviousSuggestionEvent:(id)arg1;	// IMP=0x001000000011f96f
- (_Bool)isNextSuggestionEvent:(id)arg1;	// IMP=0x001000000011f941
- (_Bool)isReturnKeyEvent:(id)arg1;	// IMP=0x001000000011f913
- (_Bool)isWordBackspaceEvent:(id)arg1;	// IMP=0x001000000011f8e5
- (_Bool)isBackspaceEvent:(id)arg1;	// IMP=0x001000000011f8b7
- (_Bool)isSpaceEvent:(id)arg1;	// IMP=0x001000000011f889
- (void)clearCurrentString;	// IMP=0x001000000005db28
- (id)currentString;	// IMP=0x001000000005db16
- (void)sendCarriageReturnForElement:(id)arg1;	// IMP=0x001000000005dae5
- (void)pressReturnKeyForElement:(id)arg1;	// IMP=0x001000000005dab4
- (void)inputSpaceForElement:(id)arg1;	// IMP=0x001000000005da4c
- (_Bool)processEvent:(id)arg1;	// IMP=0x001000000005d3ec
- (id)currentElementAttributes;	// IMP=0x001000000005d267
- (void)updateWithString:(id)arg1;	// IMP=0x001000000005c982
- (long long)valueChangeOriginator;	// IMP=0x001000000011f85f
- (void)appendString:(id)arg1;	// IMP=0x001000000005c8d9
- (_Bool)processTapWithFingerCount:(unsigned long long)arg1;	// IMP=0x001000000005c862
- (id)init;	// IMP=0x001000000005c7e8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

