//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AVAudioPlayer, NSString, SCRCTargetSelectorTimer, SCRCThread, VOTOutputAction;

@interface VOTSound : NSObject
{
    VOTOutputAction *_action;	// 8 = 0x8
    struct OpaqueAudioFileID *_audioFileID;	// 16 = 0x10
    struct OpaqueAudioComponentInstance *_audioUnit;	// 24 = 0x18
    unsigned int _soundID;	// 32 = 0x20
    id _delegate;	// 40 = 0x28
    id _owner;	// 48 = 0x30
    CDUnknownBlockType _completionBlock;	// 56 = 0x38
    double _volume;	// 64 = 0x40
    NSString *_soundPath;	// 72 = 0x48
    AVAudioPlayer *_player;	// 80 = 0x50
    struct os_unfair_lock_s _completionBlockLock;	// 88 = 0x58
    long long _soundChannels;	// 96 = 0x60
    _Bool _hearingAidStreamSelected;	// 104 = 0x68
    unsigned long long _soundPlayGeneration;	// 112 = 0x70
    SCRCTargetSelectorTimer *_cancelHelperTimer;	// 120 = 0x78
    _Bool _isPlaying;	// 128 = 0x80
    _Bool _isVolumeSound;	// 129 = 0x81
    SCRCThread *_soundThread;	// 136 = 0x88
    NSString *_resolvedSoundPath;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x0020000000014e94
@property(copy, nonatomic) NSString *resolvedSoundPath; // @synthesize resolvedSoundPath=_resolvedSoundPath;
@property(nonatomic) _Bool isVolumeSound; // @synthesize isVolumeSound=_isVolumeSound;
@property(retain, nonatomic) SCRCThread *soundThread; // @synthesize soundThread=_soundThread;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;	// IMP=0x0010000000014daa
- (void)audioPlayerDecodeErrorDidOccur:(id)arg1 error:(id)arg2;	// IMP=0x0010000000014d2b
- (void)playAvoidingSSS;	// IMP=0x0010000000014d14
- (void)play;	// IMP=0x0010000000014d00
- (void)playAvoidingSSS:(_Bool)arg1;	// IMP=0x0010000000014967
- (void)_cancelHelperFired:(unsigned long long)arg1;	// IMP=0x001000000001488a
- (void)_sendFinishPlayingNotificationsWithCompletionBlock:(CDUnknownBlockType)arg1 delegate:(id)arg2;	// IMP=0x0010000000014805
- (void)_finishedPlaying;	// IMP=0x0010000000014672
- (id)action;	// IMP=0x0010000000014664
- (void)setAction:(id)arg1;	// IMP=0x0010000000014653
- (id)owner;	// IMP=0x0010000000014645
- (void)setOwner:(id)arg1;	// IMP=0x0010000000014634
- (id)delegate;	// IMP=0x0010000000014626
- (void)setDelegate:(id)arg1;	// IMP=0x0010000000014615
- (void)dealloc;	// IMP=0x001000000001451a
- (void)setVolume:(float)arg1;	// IMP=0x00100000000144fb
- (id)soundPath;	// IMP=0x00100000000144ed
- (void)_updateAudioSessionProperties;	// IMP=0x0010000000014492
- (void)__updateAudioSessionProperties;	// IMP=0x00100000000141e7
- (void)_updatePlayerWithAudioFile:(_Bool)arg1;	// IMP=0x0010000000013f78
- (_Bool)shouldUseAVAudioPlayer;	// IMP=0x0010000000013efb
- (void)resetSoundForLostMediaSession;	// IMP=0x0010000000013e93
- (void)_hearingAidRouteChange:(id)arg1;	// IMP=0x0010000000013e8d
- (id)initWithSoundPath:(id)arg1 thread:(id)arg2;	// IMP=0x0010000000013a69

@end

