//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface VOTUserEventManager : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00400000000c5859
- (void)userEventOccurred;	// IMP=0x00400000000c58ed
- (id)init;	// IMP=0x00100000000c58be

@end

