//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface EscrowLogRecoveryRequest
{
}

- (id)bodyDictionary;	// IMP=0x004000000001b5f9
- (id)command;	// IMP=0x001000000001b5ec
- (id)urlString;	// IMP=0x001000000001b595
- (Class)responseClass;	// IMP=0x001000000001b584

@end

