//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCAppleServicesPayloadHandler
{
}

- (_Bool)setAdditions:(id)arg1 outError:(id *)arg2;	// IMP=0x0040000000070a80
- (id)applicationID;	// IMP=0x00100000000708e6
- (void)_remove;	// IMP=0x00100000000708d0
- (_Bool)_installOutError:(id *)arg1;	// IMP=0x001000000007084d
- (void)unsetAside;	// IMP=0x0010000000070839
- (void)setAside;	// IMP=0x0010000000070827
- (void)remove;	// IMP=0x00100000000707bb
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x00100000000707a6

@end

