//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary;

@interface MCGmailAccountPayloadHandler
{
    NSDictionary *_setAsideAccountDictionary;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000006ebeb
@property(retain, nonatomic) NSDictionary *setAsideAccountDictionary; // @synthesize setAsideAccountDictionary=_setAsideAccountDictionary;
- (void)unsetAside;	// IMP=0x001000000006eb42
- (void)setAside;	// IMP=0x001000000006e79b
- (void)remove;	// IMP=0x001000000006e6f7
- (void)_remove;	// IMP=0x001000000006e049
- (_Bool)isInstalled;	// IMP=0x001000000006ddce
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x001000000006d8d4
- (id)_installWithAccountDictionary:(id)arg1;	// IMP=0x001000000006d3e5
- (id)accountDictionaryWithIsInstalledByMDM:(_Bool)arg1 personaID:(id)arg2 rmAccountIdentifier:(id)arg3;	// IMP=0x001000000006cfb8
- (id)MCACAccountIdentifier;	// IMP=0x001000000006cf68
- (id)unhashedAccountIdentifier;	// IMP=0x001000000006ced3
- (id)initWithPayload:(id)arg1 profileHandler:(id)arg2;	// IMP=0x001000000006cea4

@end

