//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface MCVPNPayloadHandlerBase
{
    struct __SCPreferences *_scPreferences;	// 32 = 0x20
    NSString *_originalName;	// 40 = 0x28
}

+ (id)managedServiceIDs;	// IMP=0x004000000007618b
- (void).cxx_destruct;	// IMP=0x00200000000761df
@property(retain, nonatomic) NSString *originalName; // @synthesize originalName=_originalName;
@property(nonatomic) struct __SCPreferences *scPreferences; // @synthesize scPreferences=_scPreferences;
- (void)didInstallOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x0010000000076185
- (void)unsetAside;	// IMP=0x001000000007617f
- (void)setAside;	// IMP=0x0010000000076179
- (void)remove;	// IMP=0x0010000000076173
- (_Bool)isInstalled;	// IMP=0x001000000007616b
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0010000000076163
- (id)installService:(id)arg1;	// IMP=0x001000000007615b
- (id)cannotInstallError;	// IMP=0x0010000000076089
- (id)PPTPDeprecatedError;	// IMP=0x0010000000076008
- (_Bool)preflightUserInputResponses:(id)arg1 outError:(id *)arg2;	// IMP=0x0010000000076000
- (id)userInputFields;	// IMP=0x0010000000075ff8
- (id)initWithPayload:(id)arg1 profileHandler:(id)arg2;	// IMP=0x0010000000075fea

@end

