//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCMContainerClassBackupPath
{
}

+ (id)systemGroupContainerBackupDirectoryWithUserIdentity:(id)arg1;	// IMP=0x0040000000042b32
+ (id)systemContainerBackupDirectoryWithUserIdentity:(id)arg1;	// IMP=0x0010000000042ad6
+ (id)systemContainerBackupBaseDirectoryWithUserIdentity:(id)arg1;	// IMP=0x00100000000429b3

@end

