//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSString.h>

@interface MCMLazyDescription : NSString
{
    CDUnknownBlockType _block;	// 8 = 0x8
    NSString *_value;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000006aaca
- (id)redactedDescription;	// IMP=0x001000000006aaaf
- (id)description;	// IMP=0x001000000006aa5f
- (void)getCharacters:(unsigned short *)arg1 range:(struct _NSRange)arg2;	// IMP=0x001000000006a9f5
- (unsigned short)characterAtIndex:(unsigned long long)arg1;	// IMP=0x001000000006a99f
- (unsigned long long)length;	// IMP=0x001000000006a958
- (id)initWithDescriber:(CDUnknownBlockType)arg1;	// IMP=0x001000000006a8e6

@end

