//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCMUserIdentitySharedCache
{
}

+ (id)sharedInstance;	// IMP=0x0040000000095847

@end

