//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC11FlusherUtil21FeedbackLoggerService : NSObject
{
    MISSING_TYPE *fbfAssembly;	// 8 = 0x8
    MISSING_TYPE *listener;	// 24 = 0x18
    MISSING_TYPE *openConnections;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0040000000036d97
- (id)init;	// IMP=0x0010000000036d61
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0010000000036cda

@end

