//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CKRecordID, CPLDerivativesFilter, NSString;
@protocol CPLEngineStoreUserIdentifier, CPLEngineTransportGroup;

@interface CPLCloudKitSetupTask
{
    CDUnknownBlockType _completionHandler;	// 8 = 0x8
    CPLDerivativesFilter *_derivativesFilter;	// 16 = 0x10
    CKRecordID *_fetchedUserRecordID;	// 24 = 0x18
    _Bool _shouldUpdateDisabledFeatures;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000092661
@property(readonly, nonatomic) _Bool shouldUpdateDisabledFeatures; // @synthesize shouldUpdateDisabledFeatures=_shouldUpdateDisabledFeatures;
- (void)runOperations;	// IMP=0x001000000009263f
- (void)fetchUserRecord;	// IMP=0x001000000009257e
- (void)fetchDerivativesFilter;	// IMP=0x00100000000922a0
- (void)fetchDisabledFeatures;	// IMP=0x0010000000091e60
- (id)initWithController:(id)arg1 updateDisabledFeatures:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000091dca

// Remaining properties
@property(nonatomic, getter=isBackgroundTask) _Bool backgroundTask;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic, getter=isForcedTask) _Bool forcedTask;
@property(nonatomic) _Bool foreground;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isHighPriorityBackground) _Bool highPriorityBackground;
@property(readonly) Class superclass;
@property(retain, nonatomic) id <CPLEngineTransportGroup> transportGroup;
@property(retain, nonatomic) id <CPLEngineStoreUserIdentifier> transportUserIdentifier;

@end

