//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CPLCloudKitLibraryZoneIdentification
{
}

+ (id)libraryInfoRecordName;	// IMP=0x00200000000cd503
+ (_Bool)supportsCloudKitScope:(id)arg1 engineScope:(id)arg2;	// IMP=0x00100000000cd498
+ (long long)scopeTypeForCloudKitScope:(id)arg1 proposedScopeType:(long long)arg2 fetchedRecords:(id)arg3;	// IMP=0x00100000000cd350
+ (long long)_scopeTypeForCloudKitScope:(id)arg1;	// IMP=0x00100000000cd345
+ (id)recordNamesForScopeInfo;	// IMP=0x00100000000cd2d3
+ (id)defaultZoneIDForMainScope;	// IMP=0x00100000000cd25d
+ (id)mainScopeZoneIDFromZoneIDs:(id)arg1;	// IMP=0x00100000000cd0b0
+ (_Bool)isZoneIDForLibrary:(id)arg1;	// IMP=0x00100000000ccf3a
+ (_Bool)isZoneIDForMainScopeIdentifier:(id)arg1;	// IMP=0x00100000000ccf17
+ (id)_validLibraryPrefixes;	// IMP=0x00100000000ccf0a
+ (long long)_zoneIndexFromZoneID:(id)arg1;	// IMP=0x00100000000cce40
- (_Bool)supportsZoneCreation;	// IMP=0x00400000000cd9b2
- (_Bool)supportsZoneDelete;	// IMP=0x00100000000cd9aa
- (id)updatedScopeChangeFromScopeChange:(id)arg1 currentUserID:(id)arg2 withCKRecord:(id)arg3;	// IMP=0x00100000000cd804
- (id)scopeChangeFromCKRecords:(id)arg1 currentUserID:(id)arg2;	// IMP=0x00100000000cd6aa
- (id)_libraryStateFromCKRecord:(id)arg1;	// IMP=0x00100000000cd510

@end

