//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, _CPLCloudKitOperationSession;

@interface CPLCloudKitOperationCounter : NSObject
{
    NSMutableArray *_sessions;	// 8 = 0x8
    _CPLCloudKitOperationSession *_currentSession;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000e6e25
- (id)status;	// IMP=0x00100000000e6af5
- (id)statusObject;	// IMP=0x00100000000e67fa
- (void)endTask:(id)arg1 withOperationClasses:(id)arg2 operationsAllowingCellular:(id)arg3;	// IMP=0x00100000000e6652
- (void)beginTask:(id)arg1;	// IMP=0x00100000000e63f8
- (id)init;	// IMP=0x00100000000e63a2

@end

