//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MICodeSigningInfo, MIExecutableBundle;

@interface MICodeSigningVerifier : NSObject
{
    _Bool _allowAdhocSigning;	// 8 = 0x8
    _Bool _logResourceVerificationErrors;	// 9 = 0x9
    _Bool _validateResources;	// 10 = 0xa
    _Bool _performOnlineAuthorization;	// 11 = 0xb
    _Bool _validateUsingDetachedSignature;	// 12 = 0xc
    _Bool _verifyTrustCachePresence;	// 13 = 0xd
    _Bool _skipProfileIDValidation;	// 14 = 0xe
    MICodeSigningInfo *_signingInfo;	// 16 = 0x10
    MIExecutableBundle *_bundle;	// 24 = 0x18
}

+ (id)codeSigningVerifierForBundle:(id)arg1;	// IMP=0x0040000000057ed6
- (void).cxx_destruct;	// IMP=0x0020000000058308
@property(readonly, nonatomic) MIExecutableBundle *bundle; // @synthesize bundle=_bundle;
@property(readonly, nonatomic) MICodeSigningInfo *signingInfo; // @synthesize signingInfo=_signingInfo;
@property(nonatomic) _Bool skipProfileIDValidation; // @synthesize skipProfileIDValidation=_skipProfileIDValidation;
@property(nonatomic) _Bool verifyTrustCachePresence; // @synthesize verifyTrustCachePresence=_verifyTrustCachePresence;
@property(nonatomic) _Bool validateUsingDetachedSignature; // @synthesize validateUsingDetachedSignature=_validateUsingDetachedSignature;
@property(nonatomic) _Bool performOnlineAuthorization; // @synthesize performOnlineAuthorization=_performOnlineAuthorization;
@property(nonatomic) _Bool validateResources; // @synthesize validateResources=_validateResources;
@property(nonatomic) _Bool logResourceVerificationErrors; // @synthesize logResourceVerificationErrors=_logResourceVerificationErrors;
@property(nonatomic) _Bool allowAdhocSigning; // @synthesize allowAdhocSigning=_allowAdhocSigning;
- (_Bool)performValidationWithError:(id *)arg1;	// IMP=0x0010000000057f27
- (id)initWithBundle:(id)arg1;	// IMP=0x0010000000057e67

@end

