//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MIBundleContainer, MIDataContainer, MIExecutableBundle, NSString, NSURL;

@interface MIInstalledInfoGatherer : NSObject
{
    MIExecutableBundle *_bundle;	// 8 = 0x8
    MIExecutableBundle *_builtInAppParallelPlaceholderBundle;	// 16 = 0x10
    MIBundleContainer *_bundleContainer;	// 24 = 0x18
    MIDataContainer *_dataContainer;	// 32 = 0x20
    NSString *_owningBundleIdentifier;	// 40 = 0x28
    NSURL *_parentBundleURL;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00200000000232e0
@property(readonly, nonatomic) NSURL *parentBundleURL; // @synthesize parentBundleURL=_parentBundleURL;
@property(readonly, nonatomic) NSString *owningBundleIdentifier; // @synthesize owningBundleIdentifier=_owningBundleIdentifier;
@property(readonly, nonatomic) MIDataContainer *dataContainer; // @synthesize dataContainer=_dataContainer;
@property(readonly, nonatomic) MIBundleContainer *bundleContainer; // @synthesize bundleContainer=_bundleContainer;
@property(readonly, nonatomic) MIExecutableBundle *builtInAppParallelPlaceholderBundle; // @synthesize builtInAppParallelPlaceholderBundle=_builtInAppParallelPlaceholderBundle;
@property(readonly, nonatomic) MIExecutableBundle *bundle; // @synthesize bundle=_bundle;
- (id)launchServicesDictionaryWithError:(id *)arg1;	// IMP=0x001000000001f134
- (id)_infoForStashedContainer:(id)arg1;	// IMP=0x001000000001eef0
- (id)_staticDiskUsage;	// IMP=0x001000000001eb46
- (id)_groupContainersDictionary;	// IMP=0x001000000001e8ec
- (id)_sandboxEnvironment;	// IMP=0x001000000001e708
- (id)_determineApplicationType;	// IMP=0x001000000001e630
- (id)initWithWatchKitAppBundle:(id)arg1 inBundle:(id)arg2;	// IMP=0x001000000001e555
- (id)initWithPluginBundle:(id)arg1 inBundleIdentifier:(id)arg2 dataContainer:(id)arg3;	// IMP=0x001000000001e49e
- (id)initWithBundleContainer:(id)arg1 dataContainer:(id)arg2;	// IMP=0x001000000001e3c6
- (id)initWithBundleContainer:(id)arg1;	// IMP=0x001000000001e320
- (id)initWithBundle:(id)arg1 dataContainer:(id)arg2;	// IMP=0x001000000001e277
- (void)_fixUpForBuiltInAppParallelPlaceholder;	// IMP=0x001000000001d828

@end

