//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, RTCActivitySchedulerOptions, RTCSelfReporter;
@protocol OS_dispatch_queue, RTCDiskCacheDelegate;

@interface RTCDiskCache : NSObject
{
    RTCActivitySchedulerOptions *_options;	// 8 = 0x8
    RTCSelfReporter *_selfReporter;	// 16 = 0x10
    NSString *_rootPath;	// 24 = 0x18
    NSString *_oldestCacheFile;	// 32 = 0x20
    NSString *_newestCacheFile;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_stateQueue;	// 48 = 0x30
    id <RTCDiskCacheDelegate> _delegate;	// 56 = 0x38
}

@property(readonly) RTCActivitySchedulerOptions *options; // @synthesize options=_options;
@property(readonly) NSString *newestCacheFile; // @synthesize newestCacheFile=_newestCacheFile;
@property(readonly) NSString *oldestCacheFile; // @synthesize oldestCacheFile=_oldestCacheFile;
- (void)removeFromCacheDispatched:(id)arg1;	// IMP=0x0010000000002fa0
- (id)copyFirstEvent;	// IMP=0x0010000000002e7e
- (void)addEvent:(id)arg1;	// IMP=0x0010000000002a7f
- (id)getOldestEventDispatched;	// IMP=0x0010000000002321
- (_Bool)searchForCacheFileWithOrder:(int)arg1;	// IMP=0x00100000000021fe
- (_Bool)searchForCacheFileWithOrderDispatched:(int)arg1;	// IMP=0x0010000000001ec0
- (void)setDiskCacheRootPath:(id)arg1;	// IMP=0x0010000000001e76
- (_Bool)isSizeORTimeLimitationExceededForFile:(id)arg1;	// IMP=0x0010000000001db4
- (_Bool)isSizeORTimeLimitationExceededForFileDispatched:(id)arg1;	// IMP=0x0010000000001cac
- (id)pruneFileIfExpired:(id)arg1;	// IMP=0x0010000000001b28
- (id)pruneFileIfExpiredDispatched:(id)arg1;	// IMP=0x0010000000001a05
- (void)deleteAllCacheFiles;	// IMP=0x001000000000195f
- (void)deleteCurrentNewestCacheFile;	// IMP=0x00100000000018f9
- (void)deleteCurrentOldestCacheFile;	// IMP=0x001000000000186c
- (void)deleteCurrentCacheFileWithOrderDispatched:(int)arg1;	// IMP=0x0010000000001805
@property(readonly, nonatomic) NSString *cacheFileExtention;
@property(readonly, nonatomic) NSString *diskCacheRootPath;
- (void)writeInitialHeaderToFile:(id)arg1;	// IMP=0x0010000000001792
- (_Bool)secureWriteDataForHandle:(id)arg1 data:(id)arg2;	// IMP=0x0010000000001756
- (void)syncUp;	// IMP=0x001000000000173b
- (void)setSelfReporter:(id)arg1;	// IMP=0x001000000000171e
- (id)delegate;	// IMP=0x0010000000001710
- (void)dealloc;	// IMP=0x0010000000001668
- (id)initWithOptions:(id)arg1 delegate:(id)arg2;	// IMP=0x00100000000014d1

@end

