//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class PDURLSessionProxyCredential, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyDidReceiveChallengeReply : PBCodable
{
    PDURLSessionProxyCredential *_credential;	// 8 = 0x8
    int _disposition;	// 16 = 0x10
    PDURLSessionProxyTaskMessage *_task;	// 24 = 0x18
    CDStruct_cc6d6311 _has;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000003842
@property(retain, nonatomic) PDURLSessionProxyCredential *credential; // @synthesize credential=_credential;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000003747
- (unsigned long long)hash;	// IMP=0x00100000000036d4
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000035df
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000351e
- (void)copyTo:(id)arg1;	// IMP=0x001000000000349b
- (void)writeTo:(id)arg1;	// IMP=0x001000000000341a
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000003190
- (id)dictionaryRepresentation;	// IMP=0x001000000000300b
- (id)description;	// IMP=0x0010000000002f5c
@property(readonly, nonatomic) _Bool hasCredential;
- (int)StringAsDisposition:(id)arg1;	// IMP=0x0010000000002e98
- (id)dispositionAsString:(int)arg1;	// IMP=0x0010000000002e18
@property(nonatomic) _Bool hasDisposition;
@property(nonatomic) int disposition; // @synthesize disposition=_disposition;
@property(readonly, nonatomic) _Bool hasTask;

@end

