//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class PDURLSessionProxyError, PDURLSessionProxySessionMessage;

@interface PDURLSessionProxySessionBecameInvalid : PBCodable
{
    PDURLSessionProxyError *_error;	// 8 = 0x8
    PDURLSessionProxySessionMessage *_session;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000004fd76
@property(retain, nonatomic) PDURLSessionProxyError *error; // @synthesize error=_error;
@property(retain, nonatomic) PDURLSessionProxySessionMessage *session; // @synthesize session=_session;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000004fc9b
- (unsigned long long)hash;	// IMP=0x001000000004fc4e
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000004fb86
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000004fae8
- (void)copyTo:(id)arg1;	// IMP=0x001000000004fa85
- (void)writeTo:(id)arg1;	// IMP=0x001000000004fa28
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000004f83b
- (id)dictionaryRepresentation;	// IMP=0x001000000004f766
- (id)description;	// IMP=0x001000000004f6b7
@property(readonly, nonatomic) _Bool hasError;
@property(readonly, nonatomic) _Bool hasSession;

@end

