//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface AppConduit : NSObject
{
}

+ (void)setUpdatesPendingForCompanionApps:(id)arg1;	// IMP=0x00400000002080ad
+ (void)setUpdatePendingForCompanionApp:(id)arg1;	// IMP=0x00100000002080a7
+ (void)cancelUpdatesPendingForCompanionApps:(id)arg1;	// IMP=0x00100000002080a1
+ (void)cancelUpdatePendingForCompanionApp:(id)arg1;	// IMP=0x001000000020809b

@end

