//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AppPackage
{
}

+ (id)_valueDictionaryWithSystemAppLookupItem:(id)arg1;	// IMP=0x00100000000148aa
+ (id)_valueDictionaryWithStoreAsset:(id)arg1;	// IMP=0x00100000000144ff
+ (id)_legacy_valueDictionaryWithAsset:(id)arg1;	// IMP=0x001000000010c0cc
+ (id)legacy_packageForAsset:(id)arg1;	// IMP=0x001000000010c066
- (id)initWithSystemAppLookupItem:(id)arg1;	// IMP=0x0040000000014463
- (id)initWithStoreAsset:(id)arg1;	// IMP=0x00100000000143c7

@end

