//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray;

@interface AppSchedulerDatabaseTransaction
{
    NSMutableArray *_jettisonCandidates;	// 8 = 0x8
}

+ (id)_queryJettisonCandidatesOnConnection:(id)arg1;	// IMP=0x00400000000ef242
+ (id)_queryActiveInstallationStatisticsOnConnection:(id)arg1;	// IMP=0x00100000000ef038
- (void).cxx_destruct;	// IMP=0x00200000000efb60
- (_Bool)_verifyBootstrapCompleteOrNotRequired:(id)arg1;	// IMP=0x00100000000ef94e
- (_Bool)_verifyActiveInstallation:(id)arg1;	// IMP=0x00100000000ef794
- (id)_findJettisonCandidateForPriority:(long long)arg1;	// IMP=0x00100000000ef61d
- (id)scheduleMaximumActiveCount:(unsigned long long)arg1 evaluateUsingBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ee445
- (id)jettisonActiveInstallationsToReduceActiveCountTo:(unsigned long long)arg1 forReason:(long long)arg2;	// IMP=0x00100000000ee134
- (void)bootstrapSourceType:(long long)arg1 enumerateUsingBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000edd4e
- (void)bootstrapResetSourceType:(long long)arg1 withError:(id)arg2;	// IMP=0x00100000000eda17

@end

