//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, SQLiteConnection;

@interface AppUpdatesDatabaseSession : NSObject
{
    SQLiteConnection *_connection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000024e95d
@property(readonly) SQLiteConnection *connection; // @synthesize connection=_connection;
- (void)_enumerateUpdatesMatchingPredicate:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000024e4d5
- (id)updateForBundleID:(id)arg1;	// IMP=0x001000000024e370
- (id)updateBuyParamsForBundleID:(id)arg1;	// IMP=0x001000000024e1cf
- (void)enumerateUpdatesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000024e1b8
- (id)initWithConnection:(id)arg1;	// IMP=0x001000000024e14d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

