//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface ArcadeCoordinator : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
}

+ (id)sharedCoordinator;	// IMP=0x002000000007c6c0
- (void).cxx_destruct;	// IMP=0x002000000007e231
- (_Bool)_removeBadgeIDs:(id)arg1 keepID:(_Bool)arg2 logKey:(id)arg3;	// IMP=0x001000000007de72
- (_Bool)_removeAllBadgeIDsWithLogKey:(id)arg1;	// IMP=0x001000000007dd9d
- (long long)_hardwareOfferCountWithLogKey:(id)arg1;	// IMP=0x001000000007dc98
- (id)_allBadgeIDsIDsWithLogKey:(id)arg1 logResults:(_Bool)arg2;	// IMP=0x001000000007db3f
- (_Bool)_addBadgeIDMetrics:(id)arg1 forOfferID:(id)arg2 logKey:(id)arg3;	// IMP=0x001000000007d929
- (void)_migrateBadgeIDsIfNeeded;	// IMP=0x001000000007d639
- (_Bool)removeMetricsForBadgeIDs:(id)arg1 logKey:(id)arg2;	// IMP=0x001000000007d502
- (_Bool)removeBadgeIDs:(id)arg1 logKey:(id)arg2;	// IMP=0x001000000007d3ce
- (_Bool)removeAllBadgeIDsWithLogKey:(id)arg1;	// IMP=0x001000000007d2d0
- (long long)badgeIDCountWithLogKey:(id)arg1;	// IMP=0x001000000007d1d0
- (id)allBadgeIDMetricsWithLogKey:(id)arg1;	// IMP=0x001000000007d0d6
- (id)allBadgeIDsWithLogKey:(id)arg1;	// IMP=0x001000000007cf6f
- (_Bool)addBadgeIDs:(id)arg1 logKey:(id)arg2;	// IMP=0x001000000007cd29
- (void)setupFollowingMigration;	// IMP=0x001000000007ccc8
- (void)pushService:(id)arg1 didReceiveMessage:(id)arg2;	// IMP=0x001000000007c85e
- (id)init;	// IMP=0x001000000007c745

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

