//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSOperationQueue, NSString, NSURLSession, NSURLSessionConfiguration;
@protocol OS_dispatch_queue;

@interface AssetSession : NSObject
{
    NSOperationQueue *_delegateQueue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    NSURLSession *_session;	// 24 = 0x18
    NSMutableDictionary *_sessions;	// 32 = 0x20
}

+ (void)obliterateBackgroundSessionsAndHandleEventStream;	// IMP=0x00200000001c2867
+ (id)defaultSession;	// IMP=0x00100000001c26c0
- (void).cxx_destruct;	// IMP=0x00200000001c9cdd
- (void)_startTaskUsingTaskInfo:(id)arg1 withRequest:(id)arg2;	// IMP=0x00100000001c8b30
- (void)_startNetworkActivityUsingTaskInfo:(id)arg1 withTask:(id)arg2;	// IMP=0x00100000001c882d
- (void)_prepareRequestUsingTaskInfo:(id)arg1;	// IMP=0x00100000001c82db
- (void)_prepareDataConsumerUsingTaskInfo:(id)arg1;	// IMP=0x00100000001c7ba6
- (void)_retryTaskUsingTaskInfo:(id)arg1;	// IMP=0x00100000001c7759
- (void)_reportMetricsForTaskInfo:(id)arg1 withCompletionError:(id)arg2;	// IMP=0x00100000001c73b5
- (void)_finishPromiseUsingTaskInfo:(id)arg1;	// IMP=0x00100000001c6fde
- (id)_findSessionUsingTaskInfo:(id)arg1 withProperties:(id)arg2;	// IMP=0x00100000001c693a
- (void)_completeNetworkActivityWithReason:(int)arg1 usingTaskInfo:(id)arg2;	// IMP=0x00100000001c68c5
- (void)URLSession:(id)arg1 task:(id)arg2 _willSendRequestForEstablishedConnection:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000001c6652
- (void)URLSession:(id)arg1 task:(id)arg2 didFinishCollectingMetrics:(id)arg3;	// IMP=0x00100000001c625b
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x00100000001c5949
- (void)URLSession:(id)arg1 _willRetryBackgroundDataTask:(id)arg2 withError:(id)arg3;	// IMP=0x00100000001c54b3
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000001c39e3
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;	// IMP=0x00100000001c3168
- (id)assetPromiseWithRequest:(id)arg1;	// IMP=0x00100000001c29f1
@property(readonly) NSURLSessionConfiguration *configuration;
- (id)initWithConfiguration:(id)arg1;	// IMP=0x00100000001c27de
- (id)init;	// IMP=0x00100000001c2715

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

