//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class BufferedStream, NSError, NSString;
@protocol StreamDelegate;

@interface BufferedStreamWriter
{
    BufferedStream *_bufferedStream;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000000fcd4
- (long long)writeBytes:(const char *)arg1 length:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x001000000000fcb7
- (void)close;	// IMP=0x001000000000fc0e
@property(readonly) _Bool hasSpaceAvailable;
- (void)dealloc;	// IMP=0x001000000000fb38
- (id)_initWithBufferedStream:(id)arg1;	// IMP=0x001000000000faca

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property __weak id <StreamDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) NSError *streamError;
@property(readonly) unsigned long long streamStatus;
@property(readonly) Class superclass;

@end

