//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CoordinatorUtility : NSObject
{
}

+ (void)enumerateCoordinatorsWithIntent:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0040000000046132
+ (_Bool)enumerateCoordinatorsWithIntent:(unsigned long long)arg1 error:(id *)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000045d86
+ (_Bool)enumerateCoordinatorsWithError:(id *)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000045d6c
+ (id)coordinatorForBundleID:(id)arg1 withIntent:(unsigned long long)arg2 createIfNotExisting:(_Bool)arg3 wasCreated:(_Bool *)arg4 error:(id *)arg5;	// IMP=0x0010000000045bf6
+ (id)coordinatorForBundleID:(id)arg1 hasIntent:(unsigned long long *)arg2 error:(id *)arg3;	// IMP=0x0010000000045a1d
+ (_Bool)cancelCoordinatorWithBundleID:(id)arg1 cancelError:(id)arg2 error:(id *)arg3;	// IMP=0x001000000004553c

@end

