//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface FetchImageUploadURLsTask
{
    NSArray *_signedURLs;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000002052c7
@property(readonly, nonatomic) NSArray *signedURLs; // @synthesize signedURLs=_signedURLs;
- (void)_handleResult:(id)arg1;	// IMP=0x0010000000204db6
- (id)_fetchImageURLsRequest;	// IMP=0x0010000000204c6a
- (void)main;	// IMP=0x001000000020494a

@end

