//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <InstallCoordination/IXAppInstallCoordinator.h>

@class lib_IXAppInstallCoordinatorTag;

@interface IXAppInstallCoordinator (LibAppStoreDaemon)
+ (id)_lib_userPresentableErrorForFailure:(id)arg1 alertUser:(_Bool)arg2 allowHardFail:(_Bool)arg3 underlyingError:(id)arg4;	// IMP=0x0020000000089fd3
+ (id)lib_userPresentableErrorForFailure:(id)arg1 alertUser:(_Bool)arg2 allowHardFail:(_Bool)arg3;	// IMP=0x0010000000088dbd
+ (_Bool)lib_cancelOwnedCoordinatorForAppWithBundleID:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000088b94
+ (id)lib_activeCoordinatorStatesWithError:(id *)arg1;	// IMP=0x00100000000889f8
+ (id)lib_coordinatorWithTag:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000882f3
+ (id)lib_coordinatorWithIdentifier:(id)arg1 forBundleID:(id)arg2 error:(id *)arg3;	// IMP=0x00100000000880bd
+ (id)lib_coordinatorWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000087ed8
+ (id)lib_coordinatorForAppWithBundleID:(id)arg1 withClientID:(unsigned long long)arg2 withIntent:(unsigned long long)arg3 createIfNotExisting:(_Bool)arg4 wasCreated:(_Bool *)arg5 withError:(id *)arg6;	// IMP=0x0010000000087d9e
+ (id)lib_coordinatorForAppWithBundleID:(id)arg1 withIntent:(unsigned long long)arg2 createIfNotExisting:(_Bool)arg3 wasCreated:(_Bool *)arg4 withError:(id *)arg5;	// IMP=0x0010000000087d75
+ (id)lib_coordinatorForAppWithBundleID:(id)arg1 withIntent:(unsigned long long)arg2 importance:(unsigned long long)arg3 createIfNotExisting:(_Bool)arg4 withError:(id *)arg5;	// IMP=0x0010000000087b90
+ (unsigned long long)ASD_intentForClass:(Class)arg1;	// IMP=0x00100000001d0dc4
+ (Class)ASD_classForIntent:(unsigned long long)arg1;	// IMP=0x00100000001d0d48
- (id)_lib_establishAppQuitPromiseWithError:(id *)arg1;	// IMP=0x0010000000089f5f
- (_Bool)lib_setPlaceholderPromise:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000089e39
- (_Bool)lib_setInstallOptions:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000089d13
- (_Bool)lib_setInitialODRAssetPromises:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000089bb0
- (_Bool)lib_setAppStoreAsDRIWithError:(id *)arg1;	// IMP=0x0010000000089b68
- (_Bool)lib_setAppAssetPromise:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000089a95
- (_Bool)lib_setImportance:(unsigned long long)arg1 withError:(id *)arg2;	// IMP=0x00100000000899da
- (_Bool)lib_setGizmoPairingID:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000089907
- (_Bool)lib_satisfyDeviceSecurityPromiseWithError:(id *)arg1;	// IMP=0x0010000000089782
- (_Bool)lib_satisfyAppQuitPromiseWithError:(id *)arg1;	// IMP=0x001000000008970e
- (_Bool)lib_rejectAppQuitPromiseWithReason:(id)arg1 error:(id *)arg2;	// IMP=0x001000000008969a
- (_Bool)lib_failWithReason:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000089433
- (_Bool)lib_establishDeviceSecurityPromiseWithError:(id *)arg1;	// IMP=0x00100000000892e2
- (_Bool)lib_establishAppQuitPromiseWithError:(id *)arg1;	// IMP=0x00100000000892af
- (_Bool)lib_completeUserDataPromiseWithError:(id *)arg1;	// IMP=0x001000000008919e
- (_Bool)lib_completeInitialODRPromisesWithError:(id *)arg1;	// IMP=0x00100000000890f1
- (_Bool)lib_appStoreIsResponsibleClientWithError:(id *)arg1;	// IMP=0x0010000000088f46
@property(readonly) _Bool lib_appStoreIsDoneWithRestore;
- (_Bool)lib_addFeedbackPromiseWithError:(id *)arg1;	// IMP=0x0010000000088dd2
@property(readonly) lib_IXAppInstallCoordinatorTag *lib_tag;
@property(readonly) _Bool lib_hasInstallOptions;
@property(readonly) _Bool lib_hasInitialODRAssetPromises;
@property(readonly) _Bool lib_hasDeviceSecurityPromise;
@property(readonly) _Bool lib_hasCompletedPlaceholder;
@property(readonly) _Bool lib_hasCompletedDeviceSecurityPromise;
@property(readonly) _Bool lib_hasCompletedAppQuitPromise;
@property(readonly) _Bool lib_hasCompletedAppAssetPromise;
@property(readonly) _Bool lib_hasAppQuitPromise;
@property(readonly) _Bool lib_hasAppAssetPromise;
@property(readonly) _Bool lib_expectsPlaceholderPromise;
@property(readonly) _Bool lib_expectsInitialODRPromises;
@property(readonly) _Bool lib_expectsDeviceSecurityPromise;
@property(readonly) _Bool lib_expectsAppQuitPromise;
@property(readonly) _Bool lib_expectsAppAssetPromise;
@property(readonly) unsigned long long lib_coordinatorState;
@property(readonly) unsigned long long lib_coordinatorIntent;
@property(readonly) _Bool lib_appStoreIsOwningClient;
- (unsigned long long)ASD_intent;	// IMP=0x00100000001d0e4c
@end

