//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface LaunchEventEntity
{
}

+ (Class)memoryEntityClass;	// IMP=0x00400000001bcc14
+ (id)defaultProperties;	// IMP=0x00100000001bcb6b
+ (id)databaseTable;	// IMP=0x00100000001bcb5e

@end

