//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface NSObject (TypeCheckedObjectReader)
+ (id)lib_copyPropertyGetterNames;	// IMP=0x00100000001bcda4
@property(readonly) NSDictionary *tcr_dictionary;
- (id)_tcr_associatedReader;	// IMP=0x00100000000ead3c
- (void)_tcr_associateWithReader:(id)arg1;	// IMP=0x00100000000ead20
@end

