//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSRecursiveLock, PromiseResult;

@interface Promise : NSObject
{
    MISSING_TYPE *_observers;	// 8 = 0x8
    long long _state;	// 16 = 0x10
    NSRecursiveLock *_stateLock;	// 24 = 0x18
    PromiseResult *_result;	// 32 = 0x20
}

+ (id)promiseWithError:(id)arg1;	// IMP=0x004000000000d4f3
+ (id)promiseWithValue:(id)arg1;	// IMP=0x001000000000d4aa
+ (id)onScheduler:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000000d43e
- (void).cxx_destruct;	// IMP=0x001000000000e96c
@property(readonly) PromiseResult *result; // @synthesize result=_result;
- (void)_invokeExecutor:(CDUnknownBlockType)arg1 onScheduler:(id)arg2;	// IMP=0x001000000000e81f
- (void)rejectWithError:(id)arg1;	// IMP=0x001000000000e5d9
- (void)resolveWithValue:(id)arg1;	// IMP=0x001000000000e393
- (CDUnknownBlockType)completionHandlerAdapter;	// IMP=0x001000000000e316
- (id)joinWithPromise:(id)arg1;	// IMP=0x001000000000dff2
- (id)flatMapUsingTransformer:(CDUnknownBlockType)arg1 onScheduler:(id)arg2;	// IMP=0x001000000000dd2e
- (id)mapUsingTransformer:(CDUnknownBlockType)arg1 onScheduler:(id)arg2;	// IMP=0x001000000000db5f
- (void)thenPerform:(CDUnknownBlockType)arg1 orCatchError:(CDUnknownBlockType)arg2 onScheduler:(id)arg3;	// IMP=0x001000000000d917
- (void)catchError:(CDUnknownBlockType)arg1 onScheduler:(id)arg2;	// IMP=0x001000000000d8f2
- (void)alwaysPerform:(CDUnknownBlockType)arg1 onScheduler:(id)arg2;	// IMP=0x001000000000d7f3
@property(readonly, getter=isResolved) _Bool resolved;
- (id)initWithState:(long long)arg1 result:(id)arg2;	// IMP=0x001000000000d687
- (id)initOnScheduler:(id)arg1 withExecutor:(CDUnknownBlockType)arg2;	// IMP=0x001000000000d610
- (id)initWithError:(id)arg1;	// IMP=0x001000000000d5b1
- (id)initWithValue:(id)arg1;	// IMP=0x001000000000d552
- (id)init;	// IMP=0x001000000000d53c
- (void)resolveWithAMSPromise:(id)arg1;	// IMP=0x00100000001ca675
- (id)initWithAMSPromise:(id)arg1;	// IMP=0x00100000001ca60d

@end

