//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AMSPurchaseQueue, NSHashTable, NSString, TaskQueue;
@protocol OS_dispatch_queue;

@interface PurchaseManager : NSObject
{
    NSHashTable *_activeBatches;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    TaskQueue *_taskQueue;	// 24 = 0x18
    AMSPurchaseQueue *_purchaseQueue;	// 32 = 0x20
}

+ (id)sharedManager;	// IMP=0x002000000001fc6e
- (void).cxx_destruct;	// IMP=0x002000000002033f
@property(retain, nonatomic) AMSPurchaseQueue *purchaseQueue; // @synthesize purchaseQueue=_purchaseQueue;
- (void)pushService:(id)arg1 didReceiveMessage:(id)arg2;	// IMP=0x001000000002031e
- (void)processPurchases:(id)arg1 requestToken:(id)arg2 withReplyHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000202b5
- (void)processPurchaseInfos:(id)arg1 requestToken:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000002024c
- (void)processPurchaseInfo:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000201e3
- (_Bool)isPurchaseInFlightForBundleID:(id)arg1;	// IMP=0x001000000001fe2e
- (id)prepareAndGroupPurchaseInfos:(id)arg1;	// IMP=0x001000000001fe15
- (void)checkStoreQueue:(long long)arg1;	// IMP=0x001000000001fe0f
- (id)init;	// IMP=0x001000000001fcc3

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

