//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSURL;
@protocol OS_dispatch_source;

@interface RequestThrottlePersistence : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    NSURL *_url;	// 16 = 0x10
    NSMutableDictionary *_records;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_timer;	// 32 = 0x20
}

+ (_Bool)_writeRecords:(id)arg1 toURL:(id)arg2 error:(id *)arg3;	// IMP=0x0040000000199b6e
+ (id)_readRecordsFromURL:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000199a98
+ (_Bool)_deleteRecordsAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000199a17
- (void).cxx_destruct;	// IMP=0x002000000019a3c6
- (void)_writeRecords;	// IMP=0x001000000019a21a
- (void)_readRecords;	// IMP=0x0010000000199ebc
- (void)_deleteRecords;	// IMP=0x0010000000199d7a
- (void)_dirtyRecords;	// IMP=0x0010000000199bfc
- (void)filterRecordsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000199859
- (id)fetchRecordForItemID:(id)arg1;	// IMP=0x00100000001997e4
- (void)deleteRecords;	// IMP=0x0010000000199797
- (_Bool)deleteRecordForItemID:(id)arg1;	// IMP=0x00100000001996f5
- (void)addRecord:(id)arg1;	// IMP=0x0010000000199634
- (id)initWithURL:(id)arg1;	// IMP=0x00100000001995b2
- (id)initWithPath:(id)arg1;	// IMP=0x0010000000199558

@end

