//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, SQLiteConnection;

@interface SQLiteTransporter : NSObject
{
    SQLiteConnection *_connection;	// 8 = 0x8
    NSString *_databasePath;	// 16 = 0x10
}

+ (void)_removeKnownDatabasePath:(id)arg1;	// IMP=0x00400000000f02f4
+ (_Bool)_isKnownDatabasePath:(id)arg1;	// IMP=0x00100000000f0102
+ (void)_addKnownDatabasePath:(id)arg1;	// IMP=0x00100000000effbb
- (void).cxx_destruct;	// IMP=0x00200000000f0409
- (void)performTransportationUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000eff09
- (_Bool)endTransporationAndRemoveDatabase;	// IMP=0x00100000000efe2a
- (_Bool)canBeginTransportation;	// IMP=0x00100000000efc25
- (id)initWithDatabasePath:(id)arg1;	// IMP=0x00100000000efbba

@end

