//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, SQLiteConnection;

@interface SQLiteDatabaseStoreSchema : NSObject
{
    SQLiteConnection *_connection;	// 8 = 0x8
    NSString *_schemaName;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000009dbec
- (_Bool)tableExists:(id)arg1;	// IMP=0x001000000009da82
- (_Bool)migrateToVersion:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000009d89f
- (_Bool)column:(id)arg1 existsInTable:(id)arg2;	// IMP=0x001000000009d67d
@property(readonly) long long currentSchemaVersion;
- (id)initWithConnection:(id)arg1 schemaName:(id)arg2;	// IMP=0x001000000009d408

@end

