//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, XDCDevice;
@protocol OS_dispatch_queue;

@interface XDCDeviceManager : NSObject
{
    NSMutableDictionary *_devices;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00400000000fc29d
- (void).cxx_destruct;	// IMP=0x00200000000fd11c
- (void)updateDevicesWithArray:(id)arg1;	// IMP=0x00100000000fccfb
- (id)deviceForPairingID:(id)arg1;	// IMP=0x00100000000fc992
- (id)deviceForFromID:(id)arg1 usingService:(id)arg2;	// IMP=0x00100000000fc663
- (id)deviceForDestinationID:(id)arg1;	// IMP=0x00100000000fc522
@property(readonly) XDCDevice *activePairedDevice;
- (id)init;	// IMP=0x00100000000fc2f2

@end

