//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, ZipDataStreamStatus;
@protocol OS_dispatch_group, OS_dispatch_semaphore, SZExtractor;

@interface ZipDataStreamAdapter : NSObject
{
    _Bool _dataComplete;	// 8 = 0x8
    id <SZExtractor> _extractor;	// 16 = 0x10
    _Bool _hasConsumedData;	// 24 = 0x18
    NSString *_path;	// 32 = 0x20
    unsigned long long _resumptionOffset;	// 40 = 0x28
    NSObject<OS_dispatch_semaphore> *_backpressureSemaphore;	// 48 = 0x30
    NSObject<OS_dispatch_group> *_consistencyGroup;	// 56 = 0x38
    struct os_unfair_lock_s _lock;	// 64 = 0x40
    ZipDataStreamStatus *_locked_streamStatus;	// 72 = 0x48
}

+ (void)_prepareExtractor:(id)arg1 toPath:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x002000000002f1a2
- (void).cxx_destruct;	// IMP=0x002000000002f24f
- (MISSING_TYPE *)_setStreamStatus: /* Error: Ran out of types for this method. */;	// IMP=0x001000000002f20a
- (id)_streamStatus;	// IMP=0x001000000002f1d3
@property(readonly, copy) NSString *description;
- (void)truncateWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000002f151
- (void)resetWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000002f141
- (void)suspendWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000002f03f
- (void)prepareWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ef3c
- (void)finishWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000002ee15
- (void)consumeData:(id)arg1 andWait:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000002e858
- (void)consumeData:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000002e841
- (void)consumeData:(id)arg1 andWaitWithCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000002e827
- (unsigned long long)diskUsage;	// IMP=0x001000000002e765
- (id)initWithExtractor:(id)arg1 toPath:(id)arg2;	// IMP=0x001000000002e672

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

