//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableSet;

@interface VCPFaceLibraryProcessingTask : NSObject
{
    struct atomic<bool> _cancel;	// 8 = 0x8
    struct atomic<bool> _started;	// 9 = 0x9
    NSArray *_photoLibraries;	// 16 = 0x10
    NSDictionary *_options;	// 24 = 0x18
    unsigned long long _subtasks;	// 32 = 0x20
    NSMutableSet *_assetBatch;	// 40 = 0x28
    CDUnknownBlockType _progressHandler;	// 48 = 0x30
    CDUnknownBlockType _completionHandler;	// 56 = 0x38
    CDUnknownBlockType _cancelBlock;	// 64 = 0x40
}

+ (void)_logSubtasks:(unsigned long long)arg1;	// IMP=0x0020000000058074
+ (id)taskWithPhotoLibraries:(id)arg1 andOptions:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4 andCancelBlock:(CDUnknownBlockType)arg5;	// IMP=0x0010000000057f81
- (void).cxx_destruct;	// IMP=0x0020000000061cc0
- (_Bool)autoCancellable;	// IMP=0x0010000000061cb8
- (int)run;	// IMP=0x0010000000060f96
- (int)_processAutoCounterForPhotoLibrary:(id)arg1;	// IMP=0x001000000006070b
- (int)_clusterAndProcessPersonsForPhotoLibrary:(id)arg1 withContext:(id)arg2 progressMade:(_Bool *)arg3;	// IMP=0x0010000000060081
- (int)_promotePersonsForPhotoLibrary:(id)arg1;	// IMP=0x001000000005fc56
- (int)_buildPersonsForPhotoLibrary:(id)arg1 withClusterer:(id)arg2 andContext:(id)arg3;	// IMP=0x001000000005f6d4
- (int)_clusterFacesWithClusterer:(id)arg1;	// IMP=0x001000000005f2a1
- (int)_updateQuickFaceIDModelForPhotoLibrary:(id)arg1 withContext:(id)arg2 andQuickFaceIDManager:(id)arg3;	// IMP=0x001000000005ee90
- (int)_generateAndDetectFaceCropsForPhotoLibrary:(id)arg1 withContext:(id)arg2;	// IMP=0x001000000005e976
- (int)_detectFacesForPhotoLibrary:(id)arg1 withContext:(id)arg2;	// IMP=0x001000000005e6f1
- (_Bool)_readyToProcessProcessLibrary:(id)arg1;	// IMP=0x001000000005e41e
- (int)completeSceneProcessing;	// IMP=0x001000000005e18a
- (int)_processingLibraryWithTask:(id)arg1;	// IMP=0x001000000005da6a
- (int)_maintainProcessingStatusWithTask:(id)arg1;	// IMP=0x001000000005d461
- (int)_analyzeAssetsWithChangeToken:(id)arg1 withTask:(id)arg2;	// IMP=0x001000000005c017
- (int)_queryChangeTokenCountSince:(id)arg1 count:(unsigned long long *)arg2 withTask:(id)arg3;	// IMP=0x001000000005bd53
- (int)_processLocalIdentifiers:(id)arg1 change:(id)arg2 insert:(_Bool)arg3 withTask:(id)arg4;	// IMP=0x001000000005b658
- (int)_analyzeAllAssetsWithTask:(id)arg1;	// IMP=0x001000000005acae
- (int)_processFetchedAssets:(id)arg1 withProcessingTask:(id)arg2 andProgressReporter:(id)arg3;	// IMP=0x001000000005a8d2
- (int)_retryFailedAssetsWithTask:(id)arg1;	// IMP=0x001000000005a5a2
- (int)_retryEligibleAssetsWithTask:(id)arg1 andStatus:(unsigned long long)arg2 andReporter:(id)arg3;	// IMP=0x0010000000059de3
- (int)_streamAnalysisWithTask:(id)arg1 andProcessingStatus:(unsigned long long)arg2;	// IMP=0x00100000000596a2
- (int)_screenLocalIdentifiers:(id)arg1 withTask:(id)arg2 andPreviousStatus:(unsigned long long)arg3 andProgressReporter:(id)arg4;	// IMP=0x0010000000058b32
- (int)_addBatchWithAsset:(id)arg1 isRetry:(_Bool)arg2 withTask:(id)arg3;	// IMP=0x0010000000058148
- (_Bool)isCancelled;	// IMP=0x0010000000058124
- (void)cancel;	// IMP=0x0010000000058119
- (float)resourceRequirement;	// IMP=0x001000000005810b
- (void)dealloc;	// IMP=0x001000000005807a
- (id)initWithPhotoLibraries:(id)arg1 andOptions:(id)arg2 andProgressHandler:(CDUnknownBlockType)arg3 andCompletionHandler:(CDUnknownBlockType)arg4 andCancelBlock:(CDUnknownBlockType)arg5;	// IMP=0x0010000000057cde
- (id)init;	// IMP=0x0010000000057cd0

@end

