//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface HBCollectionComparator : NSObject
{
}

- (id)changesFromObjects:(id)arg1 toObjects:(id)arg2 withIdentifierBlock:(CDUnknownBlockType)arg3;	// IMP=0x004000000007b0cb
- (id)_changeForInsertingObjectsIntoCollection:(id)arg1 availableInCollection:(id)arg2;	// IMP=0x001000000007aeff
- (id)_changeForRemovingObjectsFromCollection:(id)arg1 missingFromCollection:(id)arg2;	// IMP=0x001000000007ad30

@end

