//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface HBIconCacheItemConfiguration : NSObject
{
    double _displayScale;	// 8 = 0x8
    long long _layoutDirection;	// 16 = 0x10
}

@property(readonly, nonatomic) long long layoutDirection; // @synthesize layoutDirection=_layoutDirection;
@property(readonly, nonatomic) double displayScale; // @synthesize displayScale=_displayScale;
- (id)initWithTraitCollection:(id)arg1;	// IMP=0x0010000000040050

@end

