//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface HBItemOrderTether : NSObject
{
}

+ (id)tetherWithLeadingApplication:(id)arg1 distance:(unsigned long long)arg2 trailingApplication:(id)arg3 distance:(unsigned long long)arg4;	// IMP=0x004000000005df9f

@end

