//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface HBItemOrderArcadeApplicationRule
{
}

- (id)insertApplications:(id)arg1 into:(id)arg2;	// IMP=0x0020000000046fdf
- (_Bool)evaluateWithApplication:(id)arg1;	// IMP=0x0010000000046f4a
@property(readonly, nonatomic) unsigned long long processingLimit;
- (id)initWithProvisionedBundleIdentifiers:(id)arg1;	// IMP=0x0010000000046f10

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

