//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface BMMultiStreamVectorClock : NSObject
{
    NSMutableDictionary *_vectorClock;	// 8 = 0x8
}

+ (id)deserialize:(id)arg1 error:(id *)arg2;	// IMP=0x002000000001c28d
+ (_Bool)supportsSecureCoding;	// IMP=0x001000000001c0da
- (void).cxx_destruct;	// IMP=0x002000000001c303
- (id)serialize:(id *)arg1;	// IMP=0x001000000001c269
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000001c105
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000001c0e2
- (id)description;	// IMP=0x001000000001c067
- (id)vectorClockForStreamIdentifier:(id)arg1;	// IMP=0x001000000001c035
- (void)setVectorClockTo:(id)arg1 forStreamIdentifier:(id)arg2;	// IMP=0x001000000001c013
- (id)init;	// IMP=0x001000000001bfbd

@end

