//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BMDistributedSyncMultiStreamManager, BMRapportManager, BMSyncDevicePeerStatusTracker, BMSyncSessionMetricsCollector, NSMutableDictionary, NSString;
@protocol BMAtomBatchChunkerPolicy, OS_dispatch_queue;

@interface BMRapportSyncEngine : NSObject
{
    BMDistributedSyncMultiStreamManager *_syncManager;	// 8 = 0x8
    BMRapportManager *_rapportManager;	// 16 = 0x10
    NSMutableDictionary *_requestQueue;	// 24 = 0x18
    NSString *_localDeviceIdentifier;	// 32 = 0x20
    NSObject<BMAtomBatchChunkerPolicy> *_atomBatchChunkerPolicy;	// 40 = 0x28
    BMSyncDevicePeerStatusTracker *_peerStatusTracker;	// 48 = 0x30
    BMSyncSessionMetricsCollector *_metricsCollector;	// 56 = 0x38
    CDUnknownBlockType _reciprocalCompletionBlock;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_queue;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0020000000008f47
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) CDUnknownBlockType reciprocalCompletionBlock; // @synthesize reciprocalCompletionBlock=_reciprocalCompletionBlock;
@property(retain, nonatomic) BMSyncSessionMetricsCollector *metricsCollector; // @synthesize metricsCollector=_metricsCollector;
@property(readonly, nonatomic) BMSyncDevicePeerStatusTracker *peerStatusTracker; // @synthesize peerStatusTracker=_peerStatusTracker;
- (id)siteSuffix;	// IMP=0x0010000000008ef2
- (unsigned int)protocolVersion;	// IMP=0x0010000000008ee7
- (id)localDeviceUpdatingIfNecessary;	// IMP=0x0010000000008eb6
- (void)finishRequest:(id)arg1 toDevice:(id)arg2 withError:(id)arg3 peerInfo:(id)arg4;	// IMP=0x0010000000008d91
- (void)handleFetchAtomBatchesResponse:(id)arg1 options:(id)arg2 error:(id)arg3 fromDevice:(id)arg4 forRequest:(id)arg5 isReciprocal:(_Bool)arg6;	// IMP=0x001000000000850c
- (CDUnknownBlockType)fetchAtomBatchesRequestHandler;	// IMP=0x0010000000007948
- (void)rapportManagerDiscoveryTimedOut:(id)arg1;	// IMP=0x00100000000076bb
- (void)rapportManager:(id)arg1 didLoseNearbyBMRapportDevice:(id)arg2;	// IMP=0x00100000000076b5
- (void)rapportManager:(id)arg1 didDiscoverBMRapportDevice:(id)arg2;	// IMP=0x0010000000007543
- (_Bool)rapportManager:(id)arg1 isDeviceSupported:(id)arg2;	// IMP=0x0010000000007506
- (void)registerRequests;	// IMP=0x00100000000074a3
- (id)buildAtomBatchRequestWithIsReciprocal:(_Bool)arg1 sequenceNumber:(unsigned long long)arg2;	// IMP=0x001000000000737e
- (void)sendFetchAtomBatchesRequest:(id)arg1 toDevice:(id)arg2 forRequest:(id)arg3;	// IMP=0x0010000000007133
- (void)fetchAtomBatchesIsReciprocal:(_Bool)arg1 reason:(unsigned long long)arg2 activity:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000068e2
- (void)runRequest:(id)arg1 onDevice:(id)arg2;	// IMP=0x0010000000006804
- (void)completeRequest:(id)arg1 deliveredToDevices:(id)arg2 withErrors:(id)arg3;	// IMP=0x00100000000065ea
- (void)completeRequestIfDeliveredToAllNearbyDevices:(id)arg1;	// IMP=0x001000000000606b
- (void)syncNowWithReason:(unsigned long long)arg1 activity:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000005f11
- (void)startServer;	// IMP=0x0010000000005e8f
- (void)startClient;	// IMP=0x0010000000005e10
- (id)initWithDistributedSyncMultiStreamManager:(id)arg1 rapportManager:(id)arg2 atomBatchChunkerPolicy:(id)arg3 queue:(id)arg4;	// IMP=0x0010000000005c4c
- (id)initWithDistributedSyncMultiStreamManager:(id)arg1 queue:(id)arg2;	// IMP=0x0010000000005a89

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

