//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface UAClientController
{
}

- (double)intervalToDelaySuspensionOfAdvertisingForItem:(id)arg1;	// IMP=0x004000000002ab94
- (id)recentEligibleItemsInOrder:(double)arg1;	// IMP=0x001000000002ab8c
- (id)eligibleAdvertiseableItemsInOrder;	// IMP=0x001000000002aafe
- (id)userActivityInfoForUUID:(id)arg1;	// IMP=0x001000000002a92b
- (id)items;	// IMP=0x001000000002a923
- (id)initWithManager:(id)arg1 name:(id)arg2;	// IMP=0x001000000002a8f4

@end

