//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class ALCLMotionActivity;

@interface ALActivityOverrideMsg : PBCodable
{
    ALCLMotionActivity *_activity;	// 8 = 0x8
    int _overrideAction;	// 16 = 0x10
}

@property(retain, nonatomic) ALCLMotionActivity *activity; // @synthesize activity=_activity;
@property(nonatomic) int overrideAction; // @synthesize overrideAction=_overrideAction;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000df916
- (unsigned long long)hash;	// IMP=0x00100000000df8da
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000df866
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000df7e0
- (void)copyTo:(id)arg1;	// IMP=0x00100000000df7b0
- (void)writeTo:(id)arg1;	// IMP=0x00100000000df766
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000df759
- (id)dictionaryRepresentation;	// IMP=0x00100000000df42d
- (id)description;	// IMP=0x00100000000df3b6
- (int)StringAsOverrideAction:(id)arg1;	// IMP=0x00100000000df34d
- (id)overrideActionAsString:(int)arg1;	// IMP=0x00100000000df300
- (void)dealloc;	// IMP=0x00100000000df2c0

@end

