//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol CLDurianSystemMonitorDelegate, CLIntersiloUniverse;

@interface CLDurianSystemMonitor : NSObject
{
    struct unique_ptr<CLAppMonitor_Type::Client, std::default_delete<CLAppMonitor_Type::Client>> _appMonitorClient;	// 8 = 0x8
    struct unique_ptr<CLDaemonStatus_Type::Client, std::default_delete<CLDaemonStatus_Type::Client>> _daemonStatusClient;	// 16 = 0x10
    struct unique_ptr<CLWifiService_Type::Client, std::default_delete<CLWifiService_Type::Client>> _wifiServiceClient;	// 24 = 0x18
    _Bool _btStreaming;	// 32 = 0x20
    _Bool _wifiNetworkCritical;	// 33 = 0x21
    int _isCoexImpacted;	// 36 = 0x24
    _Bool _isAssociatedTo2GHzWiFi;	// 40 = 0x28
    int _audioStreamNotificationToken;	// 44 = 0x2c
    id <CLDurianSystemMonitorDelegate> _delegate;	// 48 = 0x30
    id <CLIntersiloUniverse> _universe;	// 56 = 0x38
}

- (id).cxx_construct;	// IMP=0x002000000099b3d4
- (void).cxx_destruct;	// IMP=0x001000000099b379
@property(retain) id <CLIntersiloUniverse> universe; // @synthesize universe=_universe;
@property(nonatomic) id <CLDurianSystemMonitorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_onWifiServiceNotification:(int)arg1 data:(struct NotificationData)arg2;	// IMP=0x001000000099b219
- (void)_onDaemonStatusNotification:(int)arg1 data:(union NotificationData)arg2;	// IMP=0x001000000099af41
- (void)_onAppMonitorNotification:(int)arg1 data:(struct NotificationData)arg2;	// IMP=0x001000000099ae08
- (void)_unregisterForNotifications;	// IMP=0x001000000099ad29
- (void)_registerForNotifications;	// IMP=0x001000000099a8b3
- (void)_checkAudioStreamState;	// IMP=0x001000000099a7c0
- (void)_recomputeCoexImpactedStateAndNotifyClients;	// IMP=0x001000000099a683
@property(readonly) int coexImpactState;
- (void)dealloc;	// IMP=0x001000000099a632
- (id)initWithUniverse:(id)arg1;	// IMP=0x001000000099a55b
- (id)init;	// IMP=0x001000000099a530

@end

