//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLFitnessTrackingNotifierAdapter
{
}

+ (id)getSilo;	// IMP=0x0020000000311196
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000031117d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000311120
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x0020000000311380
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000311353
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x001000000031132b
- (void *)adaptee;	// IMP=0x00100000003112f8
- (void)endService;	// IMP=0x00100000003112dd
- (void)beginService;	// IMP=0x001000000031122f
- (id)init;	// IMP=0x00100000003111f2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

