//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLGnssProviderAdapter
{
}

+ (id)getSilo;	// IMP=0x00100000005d0ebe
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000005d0ea5
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000005d0e48
+ (_Bool)isSupported;	// IMP=0x00100000005d0e40
- (void)shouldLockoutNilr:(_Bool)arg1;	// IMP=0x00200000005d11bf
- (void)emergencySettingsChange:(CDUnknownBlockType)arg1 withReason:(int)arg2;	// IMP=0x00100000005d119c
- (void)emergencyStateChange:(CDUnknownBlockType)arg1;	// IMP=0x00100000005d1179
- (_Bool)syncgetIonosphereParameters:(struct ThinShellIonosphereParameters *)arg1;	// IMP=0x00100000005d100f
- (void)cacheEmergencyAWDStatistics:(struct CLDaemonLocation)arg1;	// IMP=0x00100000005d0fec
- (_Bool)syncgetActiveGnssBands:(void *)arg1;	// IMP=0x00100000005d0fc9
- (_Bool)syncgetControlPlaneStatusReport:(struct CLGnssControlPlaneStatusReport *)arg1;	// IMP=0x00100000005d0fa6
- (void)resetControlPlaneStatus;	// IMP=0x00100000005d0f83
- (void)endService;	// IMP=0x00100000005d0f60
- (void)beginService;	// IMP=0x00100000005d0f3d
- (id)init;	// IMP=0x00100000005d0f1a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

