//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CLHarvestDataMotionActivity : NSObject
{
    struct CLMotionActivity _activity;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000019d7a2
@property(nonatomic) struct CLMotionActivity activity; // @synthesize activity=_activity;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000019d994
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000019d821
- (id)initWithMotionActivity:(struct CLMotionActivity)arg1;	// IMP=0x001000000019d7aa

@end

