//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class CLTimer, NSString;
@protocol CLLocationStreamingConnectionManagerServiceProtocol;

@interface CLLocationStreamer : CLIntersiloService
{
    struct unique_ptr<CLLocationController_Type::Client, std::default_delete<CLLocationController_Type::Client>> _locationClient;	// 8 = 0x8
    struct unique_ptr<CLRollingPowerAssertion, std::default_delete<CLRollingPowerAssertion>> _locationAssertion;	// 16 = 0x10
    struct unique_ptr<CLMotionState_Type::Client, std::default_delete<CLMotionState_Type::Client>> _motionStateClient;	// 24 = 0x18
    struct unique_ptr<CLRollingPowerAssertion, std::default_delete<CLRollingPowerAssertion>> _motionAlarmAssertion;	// 32 = 0x20
    struct unique_ptr<CLMotionActivity, std::default_delete<CLMotionActivity>> _lastMotionActivity;	// 40 = 0x28
    _Bool _locationUpdatesIncludeMotionState;	// 48 = 0x30
    _Bool _clientActivityTypeFitnessActive;	// 49 = 0x31
    _Bool _clientActivityTypeAirborneActive;	// 50 = 0x32
    _Bool _motionAlarmActive;	// 51 = 0x33
    _Bool _isSubscribedForMotion;	// 52 = 0x34
    _Bool _emergencyEnablementAssertionActive;	// 53 = 0x35
    _Bool _clientMapMatchingActive;	// 54 = 0x36
    int _currentGranularity;	// 56 = 0x38
    CLTimer *_resendMotionStateTimer;	// 64 = 0x40
    id <CLLocationStreamingConnectionManagerServiceProtocol> _streamingConnection;	// 72 = 0x48
    CLTimer *_aliveAgainThrottleTimer;	// 80 = 0x50
}

+ (_Bool)isSupported;	// IMP=0x00200000002f74a2
+ (id)getSilo;	// IMP=0x00100000002f7446
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000002f742d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000002f73d0
- (id).cxx_construct;	// IMP=0x00200000002fa1f0
- (void).cxx_destruct;	// IMP=0x00100000002fa15f
@property(retain, nonatomic) CLTimer *aliveAgainThrottleTimer; // @synthesize aliveAgainThrottleTimer=_aliveAgainThrottleTimer;
@property(retain, nonatomic) id <CLLocationStreamingConnectionManagerServiceProtocol> streamingConnection; // @synthesize streamingConnection=_streamingConnection;
@property(nonatomic, getter=isClientMapMatchingActive) _Bool clientMapMatchingActive; // @synthesize clientMapMatchingActive=_clientMapMatchingActive;
@property(nonatomic) _Bool emergencyEnablementAssertionActive; // @synthesize emergencyEnablementAssertionActive=_emergencyEnablementAssertionActive;
@property(retain, nonatomic) CLTimer *resendMotionStateTimer; // @synthesize resendMotionStateTimer=_resendMotionStateTimer;
@property(nonatomic) _Bool isSubscribedForMotion; // @synthesize isSubscribedForMotion=_isSubscribedForMotion;
@property(nonatomic) _Bool motionAlarmActive; // @synthesize motionAlarmActive=_motionAlarmActive;
@property(nonatomic, getter=isClientActivityTypeAirborneActive) _Bool clientActivityTypeAirborneActive; // @synthesize clientActivityTypeAirborneActive=_clientActivityTypeAirborneActive;
@property(nonatomic, getter=isClientActivityTypeFitnessActive) _Bool clientActivityTypeFitnessActive; // @synthesize clientActivityTypeFitnessActive=_clientActivityTypeFitnessActive;
@property(nonatomic) _Bool locationUpdatesIncludeMotionState; // @synthesize locationUpdatesIncludeMotionState=_locationUpdatesIncludeMotionState;
@property(nonatomic) int currentGranularity; // @synthesize currentGranularity=_currentGranularity;
- (void)pairedDeviceIsNearby:(_Bool)arg1;	// IMP=0x00100000002f9ee8
- (void)successfullySentMessage:(id)arg1;	// IMP=0x00100000002f9e02
- (void)failedToSendMessage:(id)arg1 withError:(id)arg2 isFatal:(_Bool)arg3;	// IMP=0x00100000002f9cf6
- (void)receivedMessageOfType:(id)arg1 withPayload:(id)arg2;	// IMP=0x00100000002f9990
- (void)onMotionStateNotification:(const int *)arg1 withData:(const union NotificationData *)arg2;	// IMP=0x00100000002f973a
- (void)sendMotionState;	// IMP=0x00100000002f958f
- (void)stopMotionAlarm;	// IMP=0x00100000002f9462
- (void)startMotionAlarm;	// IMP=0x00100000002f933d
- (void)reevaluateMotionSubscription;	// IMP=0x00100000002f9160
- (void)onLocationNotification:(const int *)arg1 withData:(const void *)arg2;	// IMP=0x00100000002f8ca5
- (void)startUpdatingLocationWithGranularity:(int)arg1 includeMotion:(_Bool)arg2 inFitnessSession:(_Bool)arg3 inAirborneSession:(_Bool)arg4 emergencyEnablementAssertionActive:(_Bool)arg5 hasMapMatching:(_Bool)arg6;	// IMP=0x00100000002f8904
- (void)stopLocation;	// IMP=0x00100000002f8314
- (void)unregisterAllLocationNotifications;	// IMP=0x00100000002f828e
- (void)sendAliveAgainMessage;	// IMP=0x00100000002f80fc
- (void)endService;	// IMP=0x00100000002f7fd7
- (void)beginService;	// IMP=0x00100000002f7547
- (id)init;	// IMP=0x00100000002f750a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

