//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLMotionStateAdapter
{
}

+ (id)getSilo;	// IMP=0x002000000016becc
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000016beb3
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x001000000016be56
- (void)queryMotionStatesWithStartTime:(double)arg1 endTime:(double)arg2 isFromInternalClient:(_Bool)arg3 withReply:(CDUnknownBlockType)arg4;	// IMP=0x002000000016c0de
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x001000000016c0b6
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x001000000016c089
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x001000000016c061
- (void *)adaptee;	// IMP=0x001000000016c02e
- (void)endService;	// IMP=0x001000000016c013
- (void)beginService;	// IMP=0x001000000016bf65
- (id)init;	// IMP=0x001000000016bf28

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

