//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIResponder.h>

@class MISSING_TYPE, UIWindow;

@interface _TtC10IdleScreen13SceneDelegate : UIResponder
{
    MISSING_TYPE *window;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0040000000001f60
- (id)init;	// IMP=0x0010000000001ef0
- (void)scene:(id)arg1 openURLContexts:(id)arg2;	// IMP=0x0010000000001e30
- (void)sceneDidEnterBackground:(id)arg1;	// IMP=0x0010000000001e20
- (void)sceneWillEnterForeground:(id)arg1;	// IMP=0x0010000000001e10
- (void)sceneWillResignActive:(id)arg1;	// IMP=0x0010000000001e00
- (void)sceneDidBecomeActive:(id)arg1;	// IMP=0x0010000000001db0
- (void)sceneDidDisconnect:(id)arg1;	// IMP=0x0010000000001da0
- (void)scene:(id)arg1 willConnectToSession:(id)arg2 options:(id)arg3;	// IMP=0x0010000000001d20
@property(nonatomic, retain) UIWindow *window; // @synthesize window;

@end

