//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface _TVSettingsPreferenceInvalidKeyValue
{
}

- (void)setValue:(id)arg1;	// IMP=0x00400000000fb0a0
- (id)value;	// IMP=0x00100000000fb090
- (id)key;	// IMP=0x00100000000faff0

@end

