//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@class TSKAppIconPreviewViewController, TSKSettingItem, TVSettingsAppsFacade;

@interface TVSettingsAppsViewController : TSKViewController
{
    TVSettingsAppsFacade *_appsFacade;	// 8 = 0x8
    TSKSettingItem *_lastFocusedItem;	// 16 = 0x10
    TSKAppIconPreviewViewController *_appIconPreviewViewController;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000d3940
@property(retain, nonatomic) TSKAppIconPreviewViewController *appIconPreviewViewController; // @synthesize appIconPreviewViewController=_appIconPreviewViewController;
@property(retain, nonatomic) TSKSettingItem *lastFocusedItem; // @synthesize lastFocusedItem=_lastFocusedItem;
@property(retain, nonatomic) TVSettingsAppsFacade *appsFacade; // @synthesize appsFacade=_appsFacade;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00100000000d3050
- (void)tableView:(id)arg1 didReceivePhysicalPlayForItemAtIndexPath:(id)arg2;	// IMP=0x00100000000d2f60
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x00100000000d2c90
- (id)loadSettingGroups;	// IMP=0x00100000000d1bf0
- (void)dealloc;	// IMP=0x00100000000d1b80
- (id)initWithStyle:(long long)arg1;	// IMP=0x00100000000d1a80

@end

