//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKRadioSettingGroup.h>

@protocol TVSettingsScreenSaverRadioSettingGroupDelegate;

@interface TVSettingsScreenSaverRadioSettingGroup : TSKRadioSettingGroup
{
    id <TVSettingsScreenSaverRadioSettingGroupDelegate> _delegate;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000001e7f0
@property(nonatomic) __weak id <TVSettingsScreenSaverRadioSettingGroupDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_itemSelected:(id)arg1;	// IMP=0x001000000001e6b0

@end

