//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@class TSKPreviewViewController;

@interface TVSettingsMusicViewController : TSKViewController
{
    TSKPreviewViewController *_appPreviewViewController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000002d0d0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x001000000002cfd0
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x001000000002ceb0
- (id)loadSettingGroups;	// IMP=0x001000000002b3a0
- (void)dealloc;	// IMP=0x001000000002b310
- (id)initWithStyle:(long long)arg1;	// IMP=0x001000000002b220

@end

