//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@class NSArray;

@interface TVSettingsRegionViewController : TSKViewController
{
    NSArray *_filteredSectionIndexTitles;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000734a0
@property(copy, nonatomic) NSArray *filteredSectionIndexTitles; // @synthesize filteredSectionIndexTitles=_filteredSectionIndexTitles;
- (id)_localeFormatter;	// IMP=0x0010000000073340
- (void)setRegion:(id)arg1;	// IMP=0x0010000000072bb0
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;	// IMP=0x0010000000072b30
- (id)sectionIndexTitlesForTableView:(id)arg1;	// IMP=0x0010000000072ac0
- (id)loadSettingGroups;	// IMP=0x0010000000071e90

@end

