//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TVSettingsLicenseUtilities : NSObject
{
}

+ (id)acknowledgementsPath;	// IMP=0x00400000000cf4c0
+ (id)legalSafetyText;	// IMP=0x00100000000cf440
+ (id)iTunesTermsText;	// IMP=0x00100000000cf3b0
+ (id)iCloudTermsText;	// IMP=0x00100000000cf330
+ (id)gameCenterTermsText;	// IMP=0x00100000000cf2b0
+ (id)warrantyText;	// IMP=0x00100000000cf230
+ (id)softwareLicenseText;	// IMP=0x00100000000cf1b0
+ (void)initialize;	// IMP=0x00100000000cf120
+ (void)_downloadTerms;	// IMP=0x00100000000cedc0
+ (void)_getBuiltinTerms;	// IMP=0x00100000000cec10
+ (void)_decodeTermsData:(id)arg1;	// IMP=0x00100000000ce880
+ (id)_termsRequest;	// IMP=0x00100000000ce4a0

@end

