//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ACAccountStore;

@interface TVSettingsUserProfilesValidator : NSObject
{
    long long _userActionType;	// 8 = 0x8
    ACAccountStore *_accountStore;	// 16 = 0x10
}

+ (id)_userProfiles;	// IMP=0x0040000000177110
- (void).cxx_destruct;	// IMP=0x0020000000177210
@property(readonly, nonatomic) ACAccountStore *accountStore; // @synthesize accountStore=_accountStore;
@property(nonatomic) long long userActionType; // @synthesize userActionType=_userActionType;
- (_Bool)_canSignInWithiCloudAltDSID:(id)arg1 gameCenterAltDSID:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000175c20
- (_Bool)canSignInUserWithGameCenterAltDSID:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000175ba0
- (_Bool)canSignInUserWithiCloudAltDSID:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000175b20
- (_Bool)canAddUserWithiCloudAltDSID:(id)arg1 gameCenterAltDSID:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000175a80
- (_Bool)canAddUserWithAltDSID:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000175a00
- (id)init;	// IMP=0x0010000000175940

@end

