//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface BKAccelerometerClientBKSAccelerometer
{
}

- (void)handleOrientationEvent:(long long)arg1 orientationLocked:(_Bool)arg2;	// IMP=0x004000000001e7ca
- (void)handleAccelerometerEventWithTimestamp:(double)arg1 x:(float)arg2 y:(float)arg3 z:(float)arg4 samplingInterval:(double)arg5;	// IMP=0x001000000001e6e9
- (void)_queue_invalidate;	// IMP=0x001000000001e6ba
- (_Bool)_deathBySendRight;	// IMP=0x001000000001e6b2
- (_Bool)_deathByPid;	// IMP=0x001000000001e6aa

@end

