//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKNamespaceNode, CAContext, CADisplay, CALayer, NSMutableArray, NSString;

@interface BKDisplayAnnotationController : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    NSMutableArray *_annotations;	// 16 = 0x10
    BKNamespaceNode *_rootNode;	// 24 = 0x18
    CADisplay *_display;	// 32 = 0x20
    CAContext *_context;	// 40 = 0x28
    CALayer *_rootLayer;	// 48 = 0x30
    CALayer *_transformLayer;	// 56 = 0x38
}

+ (void)performBlockForEveryAnnotationController:(CDUnknownBlockType)arg1;	// IMP=0x002000000003b679
+ (id)annotationControllerForDisplay:(id)arg1;	// IMP=0x001000000003b53c
- (void).cxx_destruct;	// IMP=0x002000000003a95a
@property(retain, nonatomic) CALayer *transformLayer; // @synthesize transformLayer=_transformLayer;
@property(retain, nonatomic) CALayer *rootLayer; // @synthesize rootLayer=_rootLayer;
@property(retain, nonatomic) CAContext *context; // @synthesize context=_context;
@property(retain, nonatomic) CADisplay *display; // @synthesize display=_display;
@property(retain, nonatomic) BKNamespaceNode *rootNode; // @synthesize rootNode=_rootNode;
@property(retain, nonatomic) NSMutableArray *annotations; // @synthesize annotations=_annotations;
- (void)_locked_updateTransform;	// IMP=0x001000000003a184
- (void)_locked_locationDidChanges;	// IMP=0x001000000003a14f
- (void)_locked_removeAnnotation:(id)arg1;	// IMP=0x001000000003a0d1
- (void)_locked_CATransaction:(CDUnknownBlockType)arg1;	// IMP=0x001000000003a061
- (id)_locked_supernodeForRenderingAtKeyPath:(id)arg1;	// IMP=0x0010000000039f4b
- (void)performSynchronizedWithCATransaction:(CDUnknownBlockType)arg1;	// IMP=0x0010000000039ea5
- (void)performSynchronized:(CDUnknownBlockType)arg1;	// IMP=0x0010000000039e68
- (void)orientationManager:(id)arg1 deviceOrientationMayHaveChanged:(long long)arg2 changeSource:(long long)arg3 isDeviceOrientationLocked:(_Bool)arg4;	// IMP=0x0010000000039e1c
- (void)removeAnnotationsForKeyPath:(id)arg1 afterDelay:(double)arg2;	// IMP=0x0010000000039cff
- (void)removeAnnotationsForKeyPath:(id)arg1;	// IMP=0x0010000000039cea
- (void)setAnnotation:(id)arg1 forKeyPath:(id)arg2;	// IMP=0x0010000000039c2f
- (id)allAnnotationsForKeyPath:(id)arg1;	// IMP=0x0010000000039b4d
- (id)annotationForKeyPath:(id)arg1;	// IMP=0x0010000000039a38
- (id)initWithDisplay:(id)arg1;	// IMP=0x00100000000394bb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

