//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface BackgroundTasksIdleSM
{
}

- (void)__notifyIdleTasksEnabledDidChange;	// IMP=0x004000000000c060
- (void)_enterOffStateAutomatically;	// IMP=0x001000000000bff0
- (void)_enterOnStateAutomatically;	// IMP=0x001000000000bf80
- (_Bool)_canBeInOnStateAutomatically;	// IMP=0x001000000000bc00
- (_Bool)isAutomaticEnabled;	// IMP=0x001000000000bb90
- (id)init;	// IMP=0x001000000000bac0

@end

