//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRDSM
{
}

- (void)_enterOffStateForced;	// IMP=0x004000000000f2d0
- (void)_enterOnStateForced;	// IMP=0x001000000000f290
- (void)_enterOffStateAutomatically;	// IMP=0x001000000000f280
- (void)_enterOnStateAutomatically;	// IMP=0x001000000000f200
- (_Bool)_canBeInOnStateAutomatically;	// IMP=0x001000000000edf0
- (id)init;	// IMP=0x001000000000eb40

@end

