//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSTimer, TVSStateMachine;

@interface PBAXFeatureManager : NSObject
{
    NSArray *_pendingUpdates;	// 8 = 0x8
    CDUnknownBlockType _updateCompletion;	// 16 = 0x10
    NSTimer *_updateTimer;	// 24 = 0x18
    TVSStateMachine *_stateMachine;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0040000000232570
- (void).cxx_destruct;	// IMP=0x0020000000237370
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(copy, nonatomic) NSTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
@property(copy, nonatomic) CDUnknownBlockType updateCompletion; // @synthesize updateCompletion=_updateCompletion;
@property(copy, nonatomic) NSArray *pendingUpdates; // @synthesize pendingUpdates=_pendingUpdates;
- (void)_cancelPendingUpdates;	// IMP=0x0010000000237180
- (void)_servicePendingUpdates;	// IMP=0x0010000000236cf0
- (void)_applyUpdatesWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000236bf0
- (id)_updatesForConfigurationOptions:(id)arg1;	// IMP=0x00100000002353b0
- (id)_currentConfigOptions;	// IMP=0x0010000000234c70
- (id)_handleSetDefaultConfiguration:(id)arg1;	// IMP=0x0010000000234890
- (id)_handleSetSingleAppConfiguration:(id)arg1;	// IMP=0x00100000002344a0
- (void)_initialzeStateMachine;	// IMP=0x0010000000233c30
- (void)updateWithConfiguration:(id)arg1;	// IMP=0x0010000000233b20
- (_Bool)handleAXShortcutEvent;	// IMP=0x0010000000232700
- (id)init;	// IMP=0x0010000000232660

@end

