//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMapTable;

@interface PBDependencyCoordinator : NSObject
{
    NSMapTable *_classesToInstances;	// 8 = 0x8
}

+ (void)registerInstance:(id)arg1 dependencyBlock:(CDUnknownBlockType)arg2;	// IMP=0x00400000000d0460
+ (id)sharedInstance;	// IMP=0x00100000000d03a0
- (void).cxx_destruct;	// IMP=0x00200000000d1000
@property(retain, nonatomic) NSMapTable *classesToInstances; // @synthesize classesToInstances=_classesToInstances;
- (void)_registerInstance:(id)arg1 dependencyBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d05c0
- (id)init;	// IMP=0x00100000000d0510

@end

