//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface PBMediaRemoteClient : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
}

+ (id)defaultClient;	// IMP=0x002000000011fda0
- (void).cxx_destruct;	// IMP=0x0020000000120510
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)getPictureInPictureStatusForPlayer:(void *)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000120350
- (void)getActivePlayersForOrigin:(void *)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000120200
- (void)getActivePlayersForLocalOriginWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001201a0
- (void)getSupportedCommandsForPlayer:(void *)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000011ffc0
- (id)initWithQueue:(id)arg1;	// IMP=0x001000000011fef0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

