//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MRPlayerPath, NSString;

@interface PBMRPictureInPicturePlayerTransaction
{
    MRPlayerPath *_pictureInPicturePlayerPath;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000271b20
@property(readonly, nonatomic) MRPlayerPath *pictureInPicturePlayerPath; // @synthesize pictureInPicturePlayerPath=_pictureInPicturePlayerPath;
- (void)_begin;	// IMP=0x0010000000271420
- (_Bool)_canBeInterrupted;	// IMP=0x0010000000271400
- (id)init;	// IMP=0x0010000000271370
- (id)initWithClient:(id)arg1;	// IMP=0x00100000002712a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

