//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface PBOverlayLayoutOffsetList : NSObject
{
    unsigned long long _capacity;	// 8 = 0x8
    double *_storage;	// 16 = 0x10
    unsigned long long _count;	// 24 = 0x18
}

@property(readonly, nonatomic) unsigned long long count; // @synthesize count=_count;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x00100000000bae90
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x00100000000bae00
- (id)succinctDescriptionBuilder;	// IMP=0x00100000000bada0
- (id)succinctDescription;	// IMP=0x00100000000bad30
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *description;
- (void)_maintainSortFromIndex:(unsigned long long)arg1;	// IMP=0x00100000000bac10
- (_Bool)getValues:(double *)arg1 range:(struct _NSRange)arg2;	// IMP=0x00100000000bab60
- (void)enumerateValuesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000baa90
- (void)addValue:(double)arg1;	// IMP=0x00100000000ba960
- (void)dealloc;	// IMP=0x00100000000ba8f0
- (id)initWithCapacity:(unsigned long long)arg1;	// IMP=0x00100000000ba7c0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

