//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, PBSMediaRemoteSiriContext, RPSiriAudioSession;
@protocol OS_dispatch_queue, PBSMediaRemoteServiceInterface, RPMessageable;

@interface RPSiriDaemon : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    RPSiriAudioSession *_siriAudioSession;	// 16 = 0x10
    NSString *_siriSenderIDS;	// 24 = 0x18
    PBSMediaRemoteSiriContext *_siriContext;	// 32 = 0x20
    id <PBSMediaRemoteServiceInterface> _siriProxy;	// 40 = 0x28
    _Bool _siriStarted;	// 48 = 0x30
    id <RPMessageable> _messenger;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000065590
@property(retain, nonatomic) id <RPMessageable> messenger; // @synthesize messenger=_messenger;
- (void)siriAudioSessionDidReceiveStopRecordingWithDeviceId:(id)arg1;	// IMP=0x0010000000065373
- (void)_handleSiriStartWhileRecording:(id)arg1 options:(id)arg2 responseHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000000006505c
- (void)_handleSiriStop:(id)arg1 options:(id)arg2 responseHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000064e6d
- (void)_handleSiriStart:(id)arg1 options:(id)arg2 responseHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000006478d
- (void)_handleSiriAudio:(id)arg1;	// IMP=0x0010000000064707
- (void)invalidate;	// IMP=0x0010000000064615
- (_Bool)activateAndReturnError:(id *)arg1;	// IMP=0x00100000000641ee
- (id)init;	// IMP=0x001000000006417e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

