//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDRemoveProfileOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0040000000064204
+ (id)requiredEntitlements;	// IMP=0x00100000000641f7
+ (id)whitelistedClassesForRequest;	// IMP=0x00100000000641c5
- (void)removeProfileWithIdentifier:(id)arg1 installationType:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000064651
- (void)runWithRequest:(id)arg1;	// IMP=0x001000000006432e

@end

