//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13appleaccountd24CustodianRecoverySession : _TtCs12_SwiftObject
{
    MISSING_TYPE *sessionID;	// 1953718111 = 0x74735f5f
    MISSING_TYPE *recoveryData;	// 0 = 0x0
    MISSING_TYPE *terminateTask;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *validationCompletion;	// 0 = 0x0
    MISSING_TYPE *verifier;	// 1233406 = 0x12d1fe
    MISSING_TYPE *lock;	// 0 = 0x0
    MISSING_TYPE *transaction;	// 0 = 0x0
}

@end

