//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface GKFriendRecommendationInternal
{
    NSString *_reason;	// 224 = 0xe0
    NSString *_reason2;	// 232 = 0xe8
    unsigned int _rid;	// 240 = 0xf0
    int _source;	// 244 = 0xf4
}

+ (id)secureCodedPropertyKeys;	// IMP=0x00200000001629dc
+ (_Bool)supportsSecureCoding;	// IMP=0x00100000001629d4
+ (int)familiarity;	// IMP=0x0010000000172271
- (void).cxx_destruct;	// IMP=0x0020000000162c29
@property(nonatomic) int source; // @synthesize source=_source;
@property(nonatomic) unsigned int rid; // @synthesize rid=_rid;
@property(retain, nonatomic) NSString *reason2; // @synthesize reason2=_reason2;
@property(retain, nonatomic) NSString *reason; // @synthesize reason=_reason;
- (int)defaultFamiliarity;	// IMP=0x0010000000162b94

@end

