//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString;
@protocol OS_dispatch_semaphore;

@interface GKResourceIdentifier : NSObject
{
    NSArray *_keys;	// 8 = 0x8
    NSObject<OS_dispatch_semaphore> *_semaphore;	// 16 = 0x10
    NSString *_queueName;	// 24 = 0x18
}

+ (id)resourceIdentifierForKeys:(id)arg1;	// IMP=0x002000000009ea73
+ (id)resourceIdentifiersForBagKeys:(id)arg1;	// IMP=0x001000000009e955
- (void).cxx_destruct;	// IMP=0x002000000009ecbd
@property(readonly, nonatomic) NSString *queueName; // @synthesize queueName=_queueName;
@property(readonly, nonatomic) NSObject<OS_dispatch_semaphore> *semaphore; // @synthesize semaphore=_semaphore;
@property(retain, nonatomic) NSArray *keys; // @synthesize keys=_keys;
- (id)description;	// IMP=0x001000000009ec08
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000009ebb1
- (unsigned long long)hash;	// IMP=0x001000000009eac0
- (void)signal;	// IMP=0x001000000009e947
- (_Bool)wait:(double)arg1;	// IMP=0x001000000009e8fc
- (id)initWithKeys:(id)arg1;	// IMP=0x001000000009e664
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000009e62b

@end

