//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKSpoofingClientProxy
{
}

- (id)externalVersion;	// IMP=0x0040000000123eb3
- (id)adamID;	// IMP=0x0010000000123e5c
- (id)bundleShortVersion;	// IMP=0x0010000000123e05
- (id)bundleVersion;	// IMP=0x0010000000123dae
- (id)bundleIdentifier;	// IMP=0x0010000000123d57
- (id)transportWithCredential:(id)arg1;	// IMP=0x0010000000123cd0

@end

