//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSArray.h>

@interface NSArray (GKAdditions)
+ (id)_gkArrayWithIndexSet:(id)arg1;	// IMP=0x002000000008b288
- (id)_gkOrderedSet;	// IMP=0x002000000008b26c
- (id)_gkDescriptionWithChildren:(long long)arg1;	// IMP=0x001000000008bebf
- (id)_gkFoldWithInitialValue:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x00100000000f36bb
- (id)_gkFirstObject;	// IMP=0x00100000000f36a9
- (id)_gkDistinctValuesForKeyPath:(id)arg1;	// IMP=0x00100000000f34d6
- (id)_gkValuesForKeyPath:(id)arg1;	// IMP=0x00100000000f3303
- (id)_gkMapDictionaryWithKeyPath:(id)arg1 valueKeyPath:(id)arg2;	// IMP=0x00100000000f302e
- (id)_gkMapDictionaryWithKeyPath:(id)arg1;	// IMP=0x00100000000f301a
- (id)_gkSubarraysByKeyWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000f2e34
- (id)_gkFilterWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000f2cfc
- (id)_gkMapWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000f2bc4
- (id)_gkMapConcurrentlyWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000f2a79
@end

