//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SYDKeychainSchedulingParameters
{
}

- (double)appSyncLimitInterval;	// IMP=0x004000000005f7d8
- (unsigned long long)appSyncLimitCount;	// IMP=0x001000000005f7cd
- (double)soonInterval;	// IMP=0x001000000005f7bf

@end

