//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary;

@interface SYDSyncTaskMap : NSObject
{
    NSMutableDictionary *_tasksByStoreIdentifierByBundleIdentifier;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000051200
@property(retain, nonatomic) NSMutableDictionary *tasksByStoreIdentifierByBundleIdentifier; // @synthesize tasksByStoreIdentifierByBundleIdentifier=_tasksByStoreIdentifierByBundleIdentifier;
@property(readonly, nonatomic) unsigned long long count;
@property(readonly, nonatomic) NSArray *allApplications;
@property(readonly, nonatomic) NSArray *allSyncTasks;
- (void)enumerateSyncTasksWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000509ff
- (id)syncTaskWithBundleIdentifier:(id)arg1 storeIdentifier:(id)arg2;	// IMP=0x0010000000050976
- (void)removeSyncTask:(id)arg1;	// IMP=0x00100000000504e8
- (void)addSyncTask:(id)arg1;	// IMP=0x00100000000503db
- (id)init;	// IMP=0x0010000000050385

@end

