//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface PAMediaConversionServiceImageMetadataPolicy : NSObject
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000001fa5
+ (id)standardPolicy;	// IMP=0x0010000000001ea8
- (id)processMetadata:(id)arg1;	// IMP=0x0040000000001e9b
- (_Bool)metadataNeedsProcessing:(id)arg1;	// IMP=0x0010000000001e93
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000001e8d
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000001e84

@end

