//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class PKDServer, PKDXpcClient;
@protocol OS_xpc_object;

@interface Transaction : NSObject
{
    const char *_type;	// 8 = 0x8
    unsigned long long _interval;	// 16 = 0x10
    PKDXpcClient *_client;	// 24 = 0x18
    NSObject<OS_xpc_object> *_request;	// 32 = 0x20
    NSObject<OS_xpc_object> *_reply;	// 40 = 0x28
    unsigned long long _version;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000011e15
@property unsigned long long version; // @synthesize version=_version;
@property(retain) NSObject<OS_xpc_object> *reply; // @synthesize reply=_reply;
@property(retain) NSObject<OS_xpc_object> *request; // @synthesize request=_request;
@property(retain) PKDXpcClient *client; // @synthesize client=_client;
- (void)fail:(long long)arg1 error:(id)arg2;	// IMP=0x0010000000011c7c
- (void)fail:(long long)arg1 message:(id)arg2;	// IMP=0x0010000000011ba4
- (void)done;	// IMP=0x0010000000011a5b
- (void)addAnnotationForPlugIn:(id)arg1 in:(id)arg2;	// IMP=0x001000000001191a
- (_Bool)pluginShouldBeAutoEnabled:(id)arg1;	// IMP=0x0010000000011912
- (void)matchPlugIns;	// IMP=0x001000000000da48
- (void)findPlugIn;	// IMP=0x001000000000d631
- (id)findPlugInByPathURL:(id)arg1;	// IMP=0x001000000000d54d
- (id)findPlugInByUUID:(id)arg1;	// IMP=0x001000000000d475
- (void)fetchAppStoreReceipt;	// IMP=0x001000000000d17e
- (void)lockDownPlugIns;	// IMP=0x001000000000c2a1
- (void)bulkAnnotatePlugIns;	// IMP=0x001000000000bbfc
- (void)annotatePlugIns;	// IMP=0x001000000000b55e
- (void)accessPlugIns;	// IMP=0x001000000000b2d2
- (void)readyPlugIns;	// IMP=0x001000000000a5f0
- (_Bool)processUuidList:(CDUnknownBlockType)arg1;	// IMP=0x0010000000009e01
- (void)bulkPlugIns;	// IMP=0x0010000000009d6a
- (void)removePlugIns;	// IMP=0x0010000000009ad7
- (void)addPlugIns;	// IMP=0x0010000000009813
- (_Bool)processPaths:(CDUnknownBlockType)arg1;	// IMP=0x001000000000974c
- (_Bool)marshalPaths:(CDUnknownBlockType)arg1;	// IMP=0x0010000000009514
- (void)dispatch;	// IMP=0x0010000000009206
- (CDStruct_4c969caf)auditToken;	// IMP=0x00100000000091a8
@property(readonly) NSObject<OS_xpc_object> *connection;
@property(readonly) PKDServer *server;
- (id)initWithRequest:(id)arg1 forClient:(id)arg2;	// IMP=0x0010000000008df6

@end

