//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;
@protocol ASDownload, OS_dispatch_queue;

@interface ASStoreServicesDownloadDelegate : NSObject
{
    long long _downloadPersistentIdentifier;	// 8 = 0x8
    NSDictionary *_downloadOptions;	// 16 = 0x10
    id <ASDownload> _download;	// 24 = 0x18
    id _strongDownload;	// 32 = 0x20
    _Bool _isObserving;	// 40 = 0x28
    _Bool _downloadDidEnd;	// 41 = 0x29
    NSObject<OS_dispatch_queue> *_observationQueue;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000002ce84
@property(nonatomic) _Bool downloadDidEnd; // @synthesize downloadDidEnd=_downloadDidEnd;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *observationQueue; // @synthesize observationQueue=_observationQueue;
@property(nonatomic) _Bool isObserving; // @synthesize isObserving=_isObserving;
@property(retain, nonatomic) NSDictionary *downloadOptions; // @synthesize downloadOptions=_downloadOptions;
@property(nonatomic) __weak id <ASDownload> download; // @synthesize download=_download;
@property(readonly, nonatomic, getter=isStalled) _Bool stalled;
- (_Bool)downloadIsStalled:(id)arg1;	// IMP=0x001000000002cd75
- (_Bool)downloadIsInFlight:(id)arg1;	// IMP=0x001000000002cc93
- (void)cancelAndFinishDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002cc7e
- (void)cancelAndFinishDownload:(id)arg1 completion:(CDUnknownBlockType)arg2 attempts:(int)arg3;	// IMP=0x001000000002c9dc
- (id)findDownloadInManager;	// IMP=0x001000000002c84b
- (long long)downloadPersistentIdentifierFoundOnDownload:(id *)arg1;	// IMP=0x001000000002c36b
- (id)errorForDownloadError:(id)arg1;	// IMP=0x001000000002c080
- (void)updateOptionsForDownload:(id)arg1 options:(id)arg2;	// IMP=0x001000000002bfaa
- (void)moveDownloadToFrontOfQueue:(id)arg1;	// IMP=0x001000000002be65
- (void)cancelDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002ba5f
- (void)resumeDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002b90f
- (void)pauseDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002b7c9
- (_Bool)insertDownloadWithOptions:(id)arg1 error:(id *)arg2;	// IMP=0x001000000002b401
- (void)applyDownloadOptions:(id)arg1 toDownload:(id)arg2 withSize:(id)arg3 moveToFront:(_Bool *)arg4;	// IMP=0x001000000002af9a
- (id)buildSSDownload:(_Bool *)arg1 withOptions:(id)arg2 error:(id *)arg3;	// IMP=0x001000000002ad9c
- (_Bool)_addDownloadURL:(id)arg1 withSize:(id)arg2 useStreamingZip:(_Bool)arg3 toDownload:(id)arg4 isLocalCacheServer:(_Bool)arg5 error:(id *)arg6;	// IMP=0x001000000002a6b0
- (void)startDownload:(id)arg1 withOptions:(id)arg2 inState:(id)arg3;	// IMP=0x001000000002a1ca
- (void)downloadManager:(id)arg1 downloadStatesDidChange:(id)arg2;	// IMP=0x0010000000029faf
- (void)reportProgressOnDownload:(id)arg1;	// IMP=0x0010000000029861
- (void)stopProgressAndFailDownload:(id)arg1 withError:(id)arg2;	// IMP=0x00100000000296e4
- (long long)readDownloadPersistentIdentifierFromRepository:(id)arg1 error:(id *)arg2;	// IMP=0x001000000002942e
- (_Bool)writeDownloadPersistentIdentifier:(long long)arg1 intoAssetRepository:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000029295
- (id)downloadManager;	// IMP=0x0010000000029118
- (void)stopObservingDownloadManager;	// IMP=0x0010000000029046
- (void)beginObservingDownloadManager;	// IMP=0x0010000000028f75
- (void)dealloc;	// IMP=0x0010000000028f1a
- (id)init;	// IMP=0x0010000000028ec4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

