//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MADownloadConfig : NSObject
{
    _Bool _discretionary;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000002deb6
@property(nonatomic) _Bool discretionary; // @synthesize discretionary=_discretionary;
- (void)logConfig;	// IMP=0x001000000002dfec
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000002dfa6
- (void)dealloc;	// IMP=0x001000000002df77
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000002def6
- (id)init;	// IMP=0x001000000002debe

@end

