//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CKKSWrappedAESSIVKey, NSData, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface CKKSItem
{
    NSString *_uuid;	// 8 = 0x8
    NSString *_parentKeyUUID;	// 16 = 0x10
    NSData *_encitem;	// 24 = 0x18
    CKKSWrappedAESSIVKey *_wrappedkey;	// 32 = 0x20
    unsigned long long _generationCount;	// 40 = 0x28
    unsigned long long _encver;	// 48 = 0x30
    NSNumber *_plaintextPCSServiceIdentifier;	// 56 = 0x38
    NSData *_plaintextPCSPublicKey;	// 64 = 0x40
    NSData *_plaintextPCSPublicIdentity;	// 72 = 0x48
}

+ (_Bool)intransactionRecordDeleted:(id)arg1 resync:(_Bool)arg2 error:(id *)arg3;	// IMP=0x004000000005f639
+ (_Bool)intransactionRecordChanged:(id)arg1 resync:(_Bool)arg2 error:(id *)arg3;	// IMP=0x001000000005df1a
+ (id)fromDatabaseRow:(id)arg1;	// IMP=0x001000000005dac6
+ (id)sqlColumns;	// IMP=0x001000000005dab9
+ (void)setOSVersionInRecord:(id)arg1;	// IMP=0x001000000005da5a
- (void).cxx_destruct;	// IMP=0x002000000005d9d4
@property(retain) NSData *plaintextPCSPublicIdentity; // @synthesize plaintextPCSPublicIdentity=_plaintextPCSPublicIdentity;
@property(retain) NSData *plaintextPCSPublicKey; // @synthesize plaintextPCSPublicKey=_plaintextPCSPublicKey;
@property(retain) NSNumber *plaintextPCSServiceIdentifier; // @synthesize plaintextPCSServiceIdentifier=_plaintextPCSServiceIdentifier;
@property unsigned long long encver; // @synthesize encver=_encver;
@property unsigned long long generationCount; // @synthesize generationCount=_generationCount;
@property(copy) CKKSWrappedAESSIVKey *wrappedkey; // @synthesize wrappedkey=_wrappedkey;
@property(copy) NSData *encitem; // @synthesize encitem=_encitem;
@property(copy) NSString *parentKeyUUID; // @synthesize parentKeyUUID=_parentKeyUUID;
@property(copy) NSString *uuid; // @synthesize uuid=_uuid;
- (id)sqlValues;	// IMP=0x001000000005d354
- (id)whereClauseToFindSelf;	// IMP=0x001000000005d250
@property(retain, getter=base64Item, setter=setBase64Item:) NSString *base64encitem;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000005d0ef
- (id)debugDescription;	// IMP=0x001000000005d04d
- (id)description;	// IMP=0x001000000005cfb7
- (id)makeAuthenticatedDataDictionaryUpdatingCKKSItemEncVer2:(id)arg1;	// IMP=0x001000000005c7e7
- (id)makeAuthenticatedDataDictionaryUpdatingCKKSItemEncVer1;	// IMP=0x001000000005c606
- (id)makeAuthenticatedDataDictionaryUpdatingCKKSItem:(id)arg1 encryptionVersion:(unsigned long long)arg2;	// IMP=0x001000000005c518
- (_Bool)matchesCKRecord:(id)arg1;	// IMP=0x001000000005bcf6
- (id)updateCKRecord:(id)arg1 zoneID:(id)arg2;	// IMP=0x001000000005b936
- (void)setFromCKRecord:(id)arg1;	// IMP=0x001000000005b45b
- (id)CKRecordName;	// IMP=0x001000000005b449
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000005b09c
- (id)initWithUUID:(id)arg1 parentKeyUUID:(id)arg2 zoneID:(id)arg3 encodedCKRecord:(id)arg4 encItem:(id)arg5 wrappedkey:(id)arg6 generationCount:(unsigned long long)arg7 encver:(unsigned long long)arg8 plaintextPCSServiceIdentifier:(id)arg9 plaintextPCSPublicKey:(id)arg10 plaintextPCSPublicIdentity:(id)arg11;	// IMP=0x001000000005af01
- (id)initWithUUID:(id)arg1 parentKeyUUID:(id)arg2 zoneID:(id)arg3 encodedCKRecord:(id)arg4 encItem:(id)arg5 wrappedkey:(id)arg6 generationCount:(unsigned long long)arg7 encver:(unsigned long long)arg8;	// IMP=0x001000000005aec4
- (id)initWithUUID:(id)arg1 parentKeyUUID:(id)arg2 zoneID:(id)arg3 encItem:(id)arg4 wrappedkey:(id)arg5 generationCount:(unsigned long long)arg6 encver:(unsigned long long)arg7;	// IMP=0x001000000005ae90
- (id)initWithUUID:(id)arg1 parentKeyUUID:(id)arg2 zoneID:(id)arg3;	// IMP=0x001000000005ae66
- (id)initCopyingCKKSItem:(id)arg1;	// IMP=0x001000000005ac3b
- (id)initWithCKRecord:(id)arg1;	// IMP=0x001000000005ac0c

@end

