//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSOperation.h>

@interface NSOperation (CKKSUsefulPrintingOperation)
- (void)removeDependenciesUponCompletion;	// IMP=0x0010000000148e47
- (void)addNullableDependency:(id)arg1;	// IMP=0x0010000000148e2e
- (_Bool)isPending;	// IMP=0x0010000000148de3
- (id)debugDescription;	// IMP=0x0010000000148ca4
- (id)description;	// IMP=0x0010000000148b6c
- (id)pendingDependenciesString:(id)arg1;	// IMP=0x0010000000148a37
- (void)linearDependenciesWithSelfFirst:(id)arg1;	// IMP=0x0010000000148807
- (void)linearDependencies:(id)arg1;	// IMP=0x001000000014866b
- (id)selfname;	// IMP=0x0010000000148587
@end

