//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface SecC2DeviceInfo : NSObject
{
}

+ (id)processUUID;	// IMP=0x00400000001679b3
+ (id)processVersion;	// IMP=0x0010000000167962
+ (id)processName;	// IMP=0x0010000000167911
+ (id)productVersion;	// IMP=0x0010000000167900
+ (id)productType;	// IMP=0x00100000001678ef
+ (id)productName;	// IMP=0x00100000001678de
+ (id)buildVersion;	// IMP=0x00100000001678cd
+ (_Bool)isAppleInternal;	// IMP=0x00100000001678bc

@end

