//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface IXSDataPromiseManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSMutableDictionary *_uuidToPromiseMap;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x002000000004e75f
+ (id)saveDir;	// IMP=0x001000000004e6d2
+ (id)savePathForPromise:(id)arg1;	// IMP=0x001000000004e5f2
- (void).cxx_destruct;	// IMP=0x002000000005099a
@property(readonly, nonatomic) NSMutableDictionary *uuidToPromiseMap; // @synthesize uuidToPromiseMap=_uuidToPromiseMap;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)promise:(id)arg1 didCancelForReason:(id)arg2 client:(unsigned long long)arg3;	// IMP=0x0010000000050805
- (void)promise:(id)arg1 didUpdateProgress:(double)arg2;	// IMP=0x001000000005072d
- (void)promiseDidReset:(id)arg1;	// IMP=0x001000000005066c
- (void)promiseDidComplete:(id)arg1;	// IMP=0x00100000000505ab
- (void)promiseDidBegin:(id)arg1;	// IMP=0x00100000000504ea
- (void)clearAllPromisesForCreator:(unsigned long long)arg1;	// IMP=0x001000000005007a
- (void)decommissionPromise:(id)arg1;	// IMP=0x001000000004ff54
- (void)enumeratePromises:(CDUnknownBlockType)arg1;	// IMP=0x001000000004fdae
- (void)registerPromise:(id)arg1;	// IMP=0x001000000004fb05
- (id)promiseForUUID:(id)arg1;	// IMP=0x001000000004f8f7
- (id)promiseForUUID:(id)arg1 ofType:(Class)arg2;	// IMP=0x001000000004f8df
- (id)_promiseForUUID:(id)arg1 ofType:(Class)arg2 useQueue:(_Bool)arg3;	// IMP=0x001000000004f70f
- (void)_onQueue_restoreSavedPromises;	// IMP=0x001000000004e8f9
- (id)init;	// IMP=0x001000000004e7ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

