//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UINavigationController.h>

@class PBSOverlayLayoutElementHandle;

@interface TVSMButtonGridNavigationController : UINavigationController
{
    PBSOverlayLayoutElementHandle *_layoutElement;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000023d50
@property(nonatomic) __weak PBSOverlayLayoutElementHandle *layoutElement; // @synthesize layoutElement=_layoutElement;
- (id)tvsm_layoutElement;	// IMP=0x0010000000023cb0
- (void)viewDidLoad;	// IMP=0x0010000000023c30

@end

