//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ApplicationWorkspaceInstallPlaceholderOperation
{
}

- (id)_download;	// IMP=0x00400000001cb2fd
- (void)runWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001cb260
- (_Bool)blocksAppInstallation;	// IMP=0x00100000001cb258
- (id)initWithApplicationHandle:(id)arg1 iconData:(id)arg2;	// IMP=0x00100000001cb229
- (id)initWithApplicationHandle:(id)arg1 forceUpdate:(_Bool)arg2;	// IMP=0x00100000001cb1fa

@end

