//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;

@interface ErrorHandlerSession : NSObject
{
    long long _sessionID;	// 8 = 0x8
    NSMutableDictionary *_sessionProperties;	// 16 = 0x10
}

@property(copy, nonatomic) NSDictionary *sessionProperties; // @synthesize sessionProperties=_sessionProperties;
@property(readonly, nonatomic) long long sessionIdentifier; // @synthesize sessionIdentifier=_sessionID;
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001a2306
- (unsigned long long)hash;	// IMP=0x00100000001a22fc
- (id)valueForSessionProperty:(id)arg1;	// IMP=0x00100000001a22d5
- (void)setValue:(id)arg1 forSessionProperty:(id)arg2;	// IMP=0x00100000001a2266
- (void)dealloc;	// IMP=0x00100000001a222b
- (id)init;	// IMP=0x00100000001a21c5

@end

