//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface FairPlayDecryptSession : NSObject
{
    NSData *_dpInfo;	// 8 = 0x8
    void *_decryptSession;	// 16 = 0x10
    NSString *_identifier;	// 24 = 0x18
}

- (id)identifier;	// IMP=0x00200000001b43e6
- (id)decryptBytes:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001b4124
- (void)dealloc;	// IMP=0x00100000001b40c4
- (id)initWithDPInfo:(id)arg1;	// IMP=0x00100000001b3eee

@end

