//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesStore/ISOperation.h>

@class NSArray, NSNumber, NSString, SSDownloadPolicy, SSMemoryEntity;

@interface PrepareDownloadOperation : ISOperation
{
    SSMemoryEntity *_download;	// 96 = 0x60
    _Bool _ignoresDownloadHandler;	// 104 = 0x68
    NSArray *_mediaAssets;	// 112 = 0x70
    CDUnknownBlockType _outputBlock;	// 120 = 0x78
    SSDownloadPolicy *_policy;	// 128 = 0x80
}

+ (long long)_URLSessionTaskPriorityForDownloadPriority:(long long)arg1;	// IMP=0x002000000016b7f6
+ (long long)_URLSessionTaskPriorityForDownload:(id)arg1;	// IMP=0x001000000016b6b6
+ (id)_mediaAssetsForDownloadIdentifier:(long long)arg1 session:(id)arg2;	// IMP=0x001000000016575d
+ (_Bool)_isDTServiceHubIssuedRequest:(id)arg1;	// IMP=0x00100000001656c2
+ (void)enumerateOperationsWithDownloadQuery:(id)arg1 session:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000161dc0
- (void).cxx_destruct;	// IMP=0x002000000016b95e
- (_Bool)_usesStreamingZipDataConsumerForAsset:(id)arg1;	// IMP=0x001000000016b818
- (double)_transferProgressFractionWithAsset:(id)arg1;	// IMP=0x001000000016b434
- (_Bool)_shouldFailForDiskSpaceWithAsset:(id)arg1 dataConsumer:(id)arg2;	// IMP=0x001000000016a6c1
- (_Bool)_shouldFailForFinishedDownload;	// IMP=0x001000000016a671
- (_Bool)_shouldCancelAutomaticDownload;	// IMP=0x001000000016a3e8
- (_Bool)_shouldCancelAsDuplicate;	// IMP=0x001000000016a30b
- (_Bool)_sendsStoreHeadersForAsset:(id)arg1;	// IMP=0x001000000016a24d
- (_Bool)_requiresPoweredPluggedIn;	// IMP=0x001000000016a0e1
- (void)_recordCoreAnalyticsEventForClient:(id)arg1 downloadKind:(id)arg2 url:(id)arg3;	// IMP=0x0010000000169e28
- (id)_newURLRequestWithAsset:(id)arg1;	// IMP=0x0010000000169815
- (id)_newDataConsumerWithAsset:(id)arg1 destinationPath:(id)arg2;	// IMP=0x001000000016947d
- (id)_newAVContentInfoDictionary;	// IMP=0x001000000016909a
- (id)_newAVAssetDownloadSessionOptionsWithAsset:(id)arg1 URLRequest:(id)arg2;	// IMP=0x0010000000168559
- (long long)_loadSizeForAsset:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000167c9c
- (long long)_loadSizeIfNecessaryForAsset:(id)arg1;	// IMP=0x0010000000167bf3
- (_Bool)_itemIsInSoftwareLibrary;	// IMP=0x0010000000167aee
- (_Bool)_itemIsInMediaLibrary;	// IMP=0x001000000016783a
- (id)_clientIdentifier;	// IMP=0x001000000016761e
- (id)_bestMediaAsset;	// IMP=0x0010000000166d07
- (long long)_assetSizeFromURLResponse:(id)arg1;	// IMP=0x0010000000166b3d
- (_Bool)_assetNeedsDecryption:(id)arg1;	// IMP=0x0010000000166a9e
- (_Bool)_isPodcast;	// IMP=0x0010000000166a4e
- (_Bool)_isPodcastRestore;	// IMP=0x00100000001669dd
- (_Bool)_allowsCellularAccessForAsset:(id)arg1;	// IMP=0x0010000000165db3
- (void)operation:(id)arg1 didReceiveResponse:(id)arg2;	// IMP=0x00100000001656ad
- (long long)operation:(id)arg1 dispositionForAuthenticationChallenge:(id)arg2;	// IMP=0x00100000001656a2
- (void)run;	// IMP=0x00100000001624f0
@property(copy) CDUnknownBlockType outputBlock;
@property _Bool ignoresDownloadHandler;
@property(readonly, nonatomic) long long downloadIdentifier;
- (id)_initWithDownload:(id)arg1 mediaAssets:(id)arg2 policy:(id)arg3;	// IMP=0x0010000000161cdd

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentage;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentageCachedResponses;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSessionDuration;
@property(readonly) Class superclass;

@end

