//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesStore/ISOperation.h>

@class NSDictionary, SSRemoteNotification;

@interface PushNotificationDisplayOperation : ISOperation
{
    SSRemoteNotification *_notification;	// 96 = 0x60
}

+ (_Bool)_shouldUseBulletinBoardForNotification:(id)arg1;	// IMP=0x00400000000a11f4
- (void).cxx_destruct;	// IMP=0x00200000000a13bd
- (_Bool)_URLHandlerExists;	// IMP=0x00100000000a12d9
- (void)_performNotificationAction:(_Bool)arg1;	// IMP=0x001000000009ff74
- (void)_openNotificationURL;	// IMP=0x001000000009fe4a
- (long long)_notificationClass;	// IMP=0x001000000009fdf1
- (void)_loadNotificationDownloadManifest;	// IMP=0x001000000009fc98
- (void)_displayBadge;	// IMP=0x001000000009fbdc
- (void)_displayAlert;	// IMP=0x001000000009f4b5
- (id)_clientIdentifierForDownloadKinds:(id)arg1;	// IMP=0x001000000009f309
- (_Bool)_clientExistsWithIdentifier:(id)arg1;	// IMP=0x001000000009f2bc
- (void)run;	// IMP=0x001000000009ead5
@property(readonly) _Bool requiresClientIdentifier;
@property(readonly) NSDictionary *notificationUserInfo;
- (id)initWithNotificationUserInfo:(id)arg1;	// IMP=0x001000000009e988
- (id)init;	// IMP=0x001000000009e974

@end

