//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSOperationQueue, NSString;
@protocol ICDHandlerProviding;

@interface CloudService : NSObject
{
    NSString *_requestingBundleID;	// 8 = 0x8
    id <ICDHandlerProviding> _handlerProvider;	// 16 = 0x10
    NSOperationQueue *_operationQueue;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000071782
@property(readonly, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(readonly, nonatomic) __weak id <ICDHandlerProviding> handlerProvider; // @synthesize handlerProvider=_handlerProvider;
@property(copy, nonatomic) NSString *requestingBundleID; // @synthesize requestingBundleID=_requestingBundleID;
- (void)_updateSagaLibraryWithReason:(long long)arg1 allowNoisyAuthPrompt:(_Bool)arg2 forConfiguration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000714fc
- (void)listCloudServerOperations;	// IMP=0x00100000000714b8
- (void)fetchEnhancedAudioOfflineKeys;	// IMP=0x0010000000071474
- (void)refreshEnhancedAudioSharedKeys;	// IMP=0x0010000000071430
- (void)importSubscriptionContainerArtworkForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000007123e
- (void)updatePinnedSubscribedPlaylistsWithConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000071078
- (void)disableCloudLibraryWithReason:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000070eff
- (void)authenticateForConfiguration:(id)arg1 startInitialImport:(_Bool)arg2 enableCloudLibraryPolicy:(long long)arg3 isExplicitUserAction:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000070ded
- (void)loadMissingArtworkForConfiguration:(id)arg1;	// IMP=0x0010000000070b3c
- (void)loadUpdateProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000070973
- (void)loadIsUpdateInProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000707a4
- (void)loadArtworkInfoForSubscriptionContainerPersistentIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000070571
- (void)loadScreenshotInfoForSubscriptionPersistentIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000007033e
- (void)loadArtworkInfoForSubscriptionItemPersistentIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000700fb
- (void)deprioritizeSubscriptionContainerArtworkForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000006ff9a
- (void)deprioritizeSubscriptionScreenshotForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000006fe39
- (void)deprioritizeSubscriptionItemArtworkForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000006fcd8
- (void)importSubscriptionScreenshotForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006fae6
- (void)importSubscriptionItemArtworkForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006f8f4
- (void)importAlbumArtistHeroImageForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006f5ee
- (void)importArtistHeroImageForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006f2e8
- (void)updateArtistHeroImagesForConfiguration:(id)arg1;	// IMP=0x001000000006f0b7
- (void)deprioritizeAlbumArtistHeroImageForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000006ef56
- (void)deprioritizeArtistHeroImageForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000006edf5
- (void)setItemProperties:(id)arg1 forPurchaseHistoryID:(unsigned long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000006ec0c
- (void)hideItemsWithPurchaseHistoryIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006ea36
- (void)loadBooksForStoreIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006e64d
- (void)loadScreenshotInfoForPurchaseHistoryIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006e414
- (void)loadArtworkInfoForPurchaseHistoryIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006e1db
- (void)deprioritizeScreenshotForPurchaseHistoryID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x001000000006e081
- (void)deprioritizeItemArtworkForPurchaseHistoryID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x001000000006df27
- (void)importScreenshotForPurchaseHistoryID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006dd69
- (void)importItemArtworkForPurchaseHistoryID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006dbab
- (void)loadJaliscoUpdateProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006d9cf
- (void)loadIsJaliscoUpdateInProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006d800
- (void)isMediaKindDisabledForJaliscoLibrary:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006d5ec
- (void)removeJaliscoLibraryForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006d3e8
- (void)setupInitialJaliscoPoolingForConfiguration:(id)arg1;	// IMP=0x001000000006d0d0
- (void)sdk_addStoreItemWithOpaqueID:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006cfc6
- (void)sdk_addStoreItemWithOpaqueID:(id)arg1 toPlaylistWithPersistentID:(long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000006cd55
- (void)sdk_createPlaylistWithPersistentID:(long long)arg1 properties:(id)arg2 trackList:(id)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000006cae0
- (void)setAlbumProperties:(id)arg1 forAlbumPersistentID:(long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000006c8f7
- (void)uploadCloudPlaylistPropertiesForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006c74a
- (void)uploadCloudItemPropertiesForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006c59d
- (void)setItemProperties:(id)arg1 forSagaID:(unsigned long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000006c3b4
- (void)loadLastKnownEnableICMLErrorStatusForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006c1ec
- (void)removeItemsWithSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006c016
- (void)addStorePlaylistWithGlobalID:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006bde3
- (void)addStoreItemWithAdamID:(long long)arg1 referral:(id)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000006bb90
- (void)updateSubscribedPlaylistsWithSagaIDs:(id)arg1 ignoreMinRefreshInterval:(_Bool)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000006b983
- (void)uploadArtworkForPlaylistWithPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006b7c5
- (void)removePlaylistsWithSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006b5ef
- (void)publishPlaylistWithSagaID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006b3ca
- (void)addItemWithSagaID:(long long)arg1 toPlaylistWithPersistentID:(long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000006b1f3
- (void)addStoreItemWithAdamID:(long long)arg1 referral:(id)arg2 toPlaylistWithPersistentID:(long long)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000006afc2
- (void)setPlaylistProperties:(id)arg1 trackList:(id)arg2 forPlaylistPersistentID:(long long)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000006ad82
- (void)createPlaylistWithPersistentID:(long long)arg1 properties:(id)arg2 trackList:(id)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000006aaea
- (void)addGeniusPlaylistWithPersistentID:(long long)arg1 name:(id)arg2 seedItemSagaIDs:(id)arg3 itemSagaIDs:(id)arg4 configuration:(id)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x001000000006a860
- (void)loadGeniusItemsForSagaID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006a63d
- (void)loadScreenshotInfoForSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006a404
- (void)loadArtworkInfoForContainerSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006a1cb
- (void)loadArtworkInfoForSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000069f92
- (void)deprioritizeContainerArtworkForSagaID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x0010000000069e38
- (void)deprioritizeScreenshotForSagaID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x0010000000069cde
- (void)deprioritizeItemArtworkForSagaID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x0010000000069b84
- (void)importContainerArtworkForSagaID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000699c6
- (void)importScreenshotForSagaID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000069808
- (void)importItemArtworkForSagaID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000006964a
- (void)loadSagaUpdateProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006946b
- (void)loadIsSagaUpdateInProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006929c
- (void)setCloudAddToPlaylistBehavior:(long long)arg1 forConfiguration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000690dd
- (void)deauthenticateForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000068f29
- (void)updateJaliscoLibraryWithReason:(long long)arg1 forConfiguration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000068d6a
- (void)isSagaAuthenticatedForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000068c7d
- (void)setPreferredVideoQuality:(long long)arg1 forConfiguration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000068bd5
- (void)updateSagaLibraryWithReason:(long long)arg1 forConfiguration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000068a0a
- (void)setupInitialSagaPoolingForConfiguration:(id)arg1;	// IMP=0x0010000000068801
- (id)initWithHandlerProvider:(id)arg1;	// IMP=0x001000000006873d

@end

