//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ICPlayActivityController, NSOperationQueue, NSString, NSXPCListener;
@protocol OS_dispatch_queue;

@interface CloudPlayActivityRequestListener : NSObject
{
    NSXPCListener *_listener;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSOperationQueue *_flushOperationQueue;	// 24 = 0x18
    long long _flushOperationCount;	// 32 = 0x20
    double _nextFlushPlayActivityFireSyncInterval;	// 40 = 0x28
    double _testNextFlushPlayActivityFireSyncInterval;	// 48 = 0x30
    ICPlayActivityController *_playActivityController;	// 56 = 0x38
}

+ (id)sharedInstance;	// IMP=0x002000000009d8ee
- (void).cxx_destruct;	// IMP=0x002000000009b28e
- (void)_scheduleNextPlayActivityFlushOperationWithCriteria:(id)arg1;	// IMP=0x001000000009b1f6
- (_Bool)_isValidTimeInterval:(double)arg1;	// IMP=0x000000000009b189
- (id)_criteriaDictionaryForEndPointIdentifier:(id)arg1 withPostFrequency:(double)arg2;	// IMP=0x001000000009ae70
- (void)_timeIntervalForNextFlushOperationWithReplyBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000009ac32
- (void)_playActivityControllerDidRecordEventsNotification:(id)arg1;	// IMP=0x001000000009abe7
- (void)_playActivityControllerEndpointRevisionInformationDidChangeNotification:(id)arg1;	// IMP=0x001000000009aa7b
- (void)_flushPlayActivityEventsForEndPointIdentifier:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000009a779
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000009a3a7
- (void)completePendingPlayActivityEvents:(id)arg1 forSessionToken:(unsigned long long)arg2 result:(unsigned long long)arg3 withReplyBlock:(CDUnknownBlockType)arg4;	// IMP=0x001000000009a2d4
- (void)insertPlayActivityEvents:(id)arg1 withReplyBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000009a21c
- (void)removePlayActivityEventsUptoRevision:(unsigned long long)arg1 withReplyBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000009a185
- (void)setRevision:(unsigned long long)arg1 revisionVersionToken:(id)arg2 forEndpointIdentifier:(id)arg3 withReplyBlock:(CDUnknownBlockType)arg4;	// IMP=0x001000000009a094
- (void)acquirePendingPlayActivityEventsForEndpointIdentifier:(id)arg1 storeAccountID:(unsigned long long)arg2 shouldFilterStoreAccountID:(_Bool)arg3 withReplyBlock:(CDUnknownBlockType)arg4;	// IMP=0x0010000000099fc2
- (void)flushPlayActivityEventsForEndPointIdentifier:(id)arg1 withReplyBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000099f0a
- (void)removePlayActivityEventsUpToRevision:(unsigned long long)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000099ef4
- (void)getHasPendingPlayEventsForEndpointIdentifier:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000099ede
- (void)setCurrentRevision:(unsigned long long)arg1 revisionVersionToken:(id)arg2 forEndpointIdentifier:(id)arg3 withCompletionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0010000000099ec8
- (void)recordPlayActivityEvents:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000099eb2
- (void)flushPendingPlayActivityEventsForEndpointIdentifier:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000099e9c
- (void)completePendingPlayActivityEvents:(id)arg1 forSessionToken:(unsigned long long)arg2 withResult:(unsigned long long)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0010000000099e86
- (void)acquirePendingPlayActivityEventsForEndpointIdentifier:(id)arg1 withStoreAccountID:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000099e70
- (void)acquirePendingPlayActivityEventsForEndpointIdentifier:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000099e5a
- (void)stop;	// IMP=0x0010000000099d6c
- (void)start;	// IMP=0x0010000000099c41
- (id)_init;	// IMP=0x0010000000099b00
- (id)init;	// IMP=0x0010000000099abe

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

