//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ICConnectionConfiguration, MISSING_TYPE, NSString;
@protocol OS_dispatch_queue;

@interface CloudPendingChangesCoordinator : NSObject
{
    NSString *_name;	// 8 = 0x8
    MISSING_TYPE *_pendingChangesPath;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    Class _loggable;	// 32 = 0x20
    ICConnectionConfiguration *_configuration;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000000a522b
@property(readonly, copy, nonatomic) ICConnectionConfiguration *configuration; // @synthesize configuration=_configuration;
- (_Bool)_savePendingChanges:(id)arg1;	// IMP=0x00100000000a500e
- (id)_pendingChanges;	// IMP=0x00100000000a4d09
- (void)removeAllPendingChanges;	// IMP=0x00100000000a4cf5
- (void)removeAllPendingChangesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000a4b42
- (void)processPendingChangesUsingLibrary:(id)arg1;	// IMP=0x00100000000a495d
- (void)addPendingChange:(id)arg1;	// IMP=0x00100000000a478f
- (id)initWithConfiguration:(id)arg1 prefix:(id)arg2 loggable:(Class)arg3;	// IMP=0x00100000000a4474

@end

