//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSOperationQueue, NSString;

@interface ICDEnhancedAudioKeyManager : NSObject
{
    NSOperationQueue *_hlsKeyRefreshOperationQueue;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000009df46
- (void)contentKeySession:(id)arg1 didFinishProcessingKey:(id)arg2 withResponse:(id)arg3 error:(id)arg4;	// IMP=0x001000000009ddfb
- (id)_storeRequestContext;	// IMP=0x001000000009ddcb
- (void)fetchMissingOfflineKeys;	// IMP=0x001000000009db4a
- (void)refreshSharedKeys;	// IMP=0x001000000009da02
- (id)init;	// IMP=0x001000000009d966

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

